# GENERATED by stonepy._generator. Do not edit by hand.
"""Resource method: DeleteClientPreference v2."""

from __future__ import annotations

from stonepy._core.resource import BaseResource
from stonepy._endpoints import client_preference as _ep
from stonepy.models import ApiUpdateDeleteClientPreferenceResponseDTO


class _DeleteClientPreferenceMixin(BaseResource):
    def delete_client_preference(
        self, client_account_id: int, key: str
    ) -> ApiUpdateDeleteClientPreferenceResponseDTO:
        """Deletes the client's preferences."""
        return _ep.delete_client_preference(self._ctx, client_account_id, key)
