# GENERATED by stonepy._generator. Do not edit by hand.
"""Resource method: GetClientPreferencesKeyList v2."""

from __future__ import annotations

from stonepy._core.resource import BaseResource
from stonepy._endpoints import client_preference as _ep
from stonepy.models import ApiGetKeyListClientPreferenceResponseDTO


class _GetClientPreferencesKeyListMixin(BaseResource):
    def get_client_preferences_key_list(
        self, client_account_id: int
    ) -> ApiGetKeyListClientPreferenceResponseDTO:
        """Returns the list of keys for client's preferences."""
        return _ep.get_client_preferences_key_list(self._ctx, client_account_id)
