# GENERATED by stonepy._generator. Do not edit by hand.
"""Synchronous and asynchronous cfd resource group classes."""

from __future__ import annotations

from stonepy._core.resource import BaseResource

from ._sync.list_cfd_markets import _ListCfdMarketsMixin as _SyncListCfdMarketsMixin
from .list_cfd_markets import _ListCfdMarketsMixin as _AsyncListCfdMarketsMixin


class CfdResource(_SyncListCfdMarketsMixin, BaseResource):
    """
    Synchronous `cfd` resource group; access it via `StoneXClient.cfd`. Each method maps to
    one StoneX CIAPI v2 endpoint.
    """


class AsyncCfdResource(_AsyncListCfdMarketsMixin, BaseResource):
    """
    Asynchronous `cfd` resource group; access it via `AsyncStoneXClient.cfd`. Each method is
    the awaitable twin of the synchronous resource's method.
    """


__all__ = [
    "AsyncCfdResource",
    "CfdResource",
]
