# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from stonepy._core.resource import BaseResource

from ._sync.delete_pa import _DeletePaMixin as _SyncDeletePaMixin
from ._sync.get_pa import _GetPaMixin as _SyncGetPaMixin
from ._sync.save_pa import _SavePaMixin as _SyncSavePaMixin
from ._sync.save_price_alert import _SavePriceAlertMixin as _SyncSavePriceAlertMixin
from .delete_pa import _DeletePaMixin as _AsyncDeletePaMixin
from .get_pa import _GetPaMixin as _AsyncGetPaMixin
from .save_pa import _SavePaMixin as _AsyncSavePaMixin
from .save_price_alert import _SavePriceAlertMixin as _AsyncSavePriceAlertMixin


class PriceAlertResource(
    _SyncDeletePaMixin, _SyncGetPaMixin, _SyncSavePaMixin, _SyncSavePriceAlertMixin, BaseResource
):
    pass


class AsyncPriceAlertResource(
    _AsyncDeletePaMixin,
    _AsyncGetPaMixin,
    _AsyncSavePaMixin,
    _AsyncSavePriceAlertMixin,
    BaseResource,
):
    pass


__all__ = [
    "AsyncPriceAlertResource",
    "PriceAlertResource",
]
