# GENERATED by stonepy._generator. Do not edit by hand.
"""Synchronous and asynchronous fixedmargin resource group classes."""

from __future__ import annotations

from stonepy._core.resource import BaseResource

from ._sync.get_free_cash_to_trade import _GetFreeCashToTradeMixin as _SyncGetFreeCashToTradeMixin
from ._sync.trade_fm import _TradeFmMixin as _SyncTradeFmMixin
from ._sync.update_trade_fm import _UpdateTradeFmMixin as _SyncUpdateTradeFmMixin
from .get_free_cash_to_trade import _GetFreeCashToTradeMixin as _AsyncGetFreeCashToTradeMixin
from .trade_fm import _TradeFmMixin as _AsyncTradeFmMixin
from .update_trade_fm import _UpdateTradeFmMixin as _AsyncUpdateTradeFmMixin


class FixedmarginResource(
    _SyncGetFreeCashToTradeMixin, _SyncTradeFmMixin, _SyncUpdateTradeFmMixin, BaseResource
):
    """
    Synchronous `fixedmargin` resource group; access it via `StoneXClient.fixedmargin`. Each
    method maps to one StoneX CIAPI v2 endpoint.
    """


class AsyncFixedmarginResource(
    _AsyncGetFreeCashToTradeMixin, _AsyncTradeFmMixin, _AsyncUpdateTradeFmMixin, BaseResource
):
    """
    Asynchronous `fixedmargin` resource group; access it via `AsyncStoneXClient.fixedmargin`.
    Each method is the awaitable twin of the synchronous resource's method.
    """


__all__ = [
    "AsyncFixedmarginResource",
    "FixedmarginResource",
]
