# GENERATED by stonepy._generator. Do not edit by hand.
"""Resource method: GetVersionInformation."""

from __future__ import annotations

from stonepy._core.resource import BaseResource
from stonepy._endpoints import clientapplication as _ep
from stonepy.models import GetVersionInformationResponseDTO


class _GetVersionInformationMixin(BaseResource):
    def get_version_information(
        self, app_key: str, account_operator_id: int
    ) -> GetVersionInformationResponseDTO:
        """
        Gets version information for a specific client application and (optionally)
        account operator.
        """
        return _ep.get_version_information(self._ctx, app_key, account_operator_id)
