"""Render generated model source text from catalog records."""

from __future__ import annotations

import json
import keyword
import re
import subprocess
import tempfile
import textwrap
from collections.abc import Collection, Mapping
from importlib import import_module
from pathlib import Path
from typing import Any, cast

from stonepy._generator.catalog import JsonObject, TypeRecord, python_name, python_type

BANNER = "# GENERATED by stonepy._generator. Do not edit by hand.\n"

_IDENTIFIER_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")
_LOWER_TO_UPPER_RE = re.compile(r"([a-z0-9])([A-Z])")
_WORD_BOUNDARY_RE = re.compile(r"(.)([A-Z][a-z]+)")

# Wire names of credential/token fields; emitted with repr=False so logging a DTO (or its
# repr in a traceback) never echoes a secret. Matched case-insensitively on the raw name.
_SECRET_FIELD_RAW_NAMES = frozenset({"appkey", "newpassword", "password", "session", "twofatoken"})

# Width of a docstring text line, leaving room for the indent and surrounding quotes so the
# generated source stays within the project's 100-column ``ruff`` line limit (E501).
_DOCSTRING_BUDGET = 94


def _clean_doc_text(text: str) -> str:
    """Collapse whitespace and escape a catalog description for use as a docstring body."""

    collapsed = " ".join(text.split())
    collapsed = collapsed.replace("\\", "\\\\")
    return collapsed.replace('"""', '\\"\\"\\"')


def render_docstring(text: str | None, *, indent: int, fallback: str | None = None) -> str:
    """Render a safe, line-length-bounded docstring block indented by *indent* spaces.

    The catalog description is normalized to a single paragraph, escaped so embedded quotes
    or backslashes cannot break out of the literal, and wrapped so no physical line exceeds
    the project line limit. Returns an empty string when neither *text* nor *fallback* has
    content, letting callers omit the docstring entirely.
    """

    source = text if text and text.strip() else fallback
    if not source or not source.strip():
        return ""
    cleaned = _clean_doc_text(source)
    pad = " " * indent
    width = max(40, _DOCSTRING_BUDGET - indent)
    wrapped = textwrap.wrap(cleaned, width=width) or [""]
    if len(wrapped) == 1 and not wrapped[0].endswith('"'):
        return f'{pad}"""{wrapped[0]}"""\n'
    body = "".join(f"{pad}{line}\n" for line in wrapped)
    return f'{pad}"""\n{body}{pad}"""\n'


def _model_fallback(rec: TypeRecord) -> str:
    return f"StoneX CIAPI v2 {rec.catalog_name} model."


def _enum_fallback(rec: TypeRecord) -> str:
    return f"StoneX CIAPI v2 {rec.catalog_name} enumeration."


def format_python(source: str) -> str:
    """Return Ruff-formatted and import-sorted Python source."""

    try:
        ruff = cast(Any, import_module("ruff"))
    except ImportError as exc:
        raise RuntimeError("ruff is required to format generated source") from exc

    ruff_bin = ruff.find_ruff_bin()
    formatted = _format_with_ruff(source, ruff_bin)
    formatted = _sort_imports_with_ruff(formatted, ruff_bin)
    return _format_with_ruff(formatted, ruff_bin)


def _format_with_ruff(source: str, ruff_bin: str) -> str:
    with tempfile.TemporaryDirectory() as tmp:
        path = Path(tmp) / "generated.py"
        path.write_text(source, encoding="utf-8")
        result = subprocess.run(
            [ruff_bin, "format", str(path)],
            check=False,
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            detail = result.stderr or result.stdout
            raise RuntimeError(f"ruff failed to format generated source:\n{detail}")
        return path.read_text(encoding="utf-8")


def _sort_imports_with_ruff(source: str, ruff_bin: str) -> str:
    with tempfile.TemporaryDirectory() as tmp:
        path = Path(tmp) / "generated.py"
        path.write_text(source, encoding="utf-8")
        result = subprocess.run(
            [ruff_bin, "check", "--fix", "--select", "I", str(path)],
            check=False,
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            detail = result.stderr or result.stdout
            raise RuntimeError(f"ruff failed to sort generated imports:\n{detail}")
        return path.read_text(encoding="utf-8")


def field_name(catalog_name: str) -> str | None:
    """Return a snake_case Python field name, or None for blank placeholders."""

    stripped = catalog_name.strip()
    if not stripped:
        return None

    candidate = re.sub(r"[^0-9A-Za-z_]+", "_", stripped)
    candidate = _WORD_BOUNDARY_RE.sub(r"\1_\2", candidate)
    candidate = _LOWER_TO_UPPER_RE.sub(r"\1_\2", candidate)
    candidate = re.sub(r"_+", "_", candidate).strip("_").lower()
    if not candidate:
        return None
    if candidate[0].isdigit():
        candidate = f"_{candidate}"
    if keyword.iskeyword(candidate):
        candidate = f"{candidate}_"
    return candidate


def render_model(
    rec: TypeRecord,
    known_names: set[str],
    *,
    request_types: Collection[str] | None = None,
    enum_names: Collection[str] | None = None,
    force_optional: Collection[str] | None = None,
) -> str:
    """Render a generated Pydantic model class for a datatype record."""

    base_model = _base_model(rec, request_types)
    # Response payloads from the (WCF) API serialize absent reference members as ``null`` and may
    # omit fields entirely, so response-model fields must all tolerate None/missing. Request models
    # keep catalog optionality so required inputs are still enforced for callers.
    fields = _model_fields(
        rec,
        known_names,
        force_optional=set(force_optional) if force_optional is not None else None,
        all_optional=base_model == "ResponseModel",
    )
    annotations = [field.annotation for field in fields]
    imports = _model_imports(
        annotations=annotations,
        base_model=base_model,
        uses_field=bool(fields),
        uses_unresolved=any(field.uses_unresolved for field in fields),
        enum_names=set(enum_names) if enum_names is not None else None,
        known_names=known_names,
        owner=rec.name,
    )

    fallback = _model_fallback(rec)
    lines: list[str] = [BANNER]
    module_doc = render_docstring(rec.description, indent=0, fallback=fallback)
    if module_doc:
        lines.append(module_doc)
    lines.append("from __future__ import annotations\n\n")
    if imports:
        lines.extend(imports)
        lines.append("\n")

    if any(field.uses_unresolved for field in fields):
        lines.append("Unresolved = Any\n\n")

    lines.append(f"class {rec.name}({base_model}):\n")
    # A class docstring (always present via the fallback) keeps the body non-empty, so models
    # with no renderable fields need no ``pass``.
    lines.append(render_docstring(rec.description, indent=4, fallback=fallback))
    for field in fields:
        lines.append(f"    {field.name}: {field.annotation} = {field.field_expr}\n")
        if field.doc:
            lines.append(field.doc)

    lines.append(f"\n\n{rec.name}.model_rebuild(raise_errors=False)\n")
    return format_python("".join(lines))


def render_enum(rec: TypeRecord) -> str:
    """Render a standalone IntEnum module for one enum-shaped datatype record."""

    lines = [BANNER]
    module_doc = render_docstring(rec.description, indent=0, fallback=_enum_fallback(rec))
    if module_doc:
        lines.append(module_doc)
    lines.extend(
        [
            "from __future__ import annotations\n\n",
            "from enum import IntEnum\n\n",
            _render_enum_class(rec),
        ]
    )
    return format_python("".join(lines))


def render_enums(records: list[TypeRecord]) -> str:
    """Render all enum-shaped datatype records into one enums.py module."""

    lines = [
        BANNER,
        render_docstring("Generated IntEnum types for the StoneX CIAPI v2 catalog.", indent=0),
        "from __future__ import annotations\n\n",
    ]
    if records:
        lines.append("from enum import IntEnum\n\n")
        lines.append("\n\n".join(_render_enum_class(rec).rstrip() for rec in records))
        lines.append("\n")
    return format_python("".join(lines))


class _RenderedField:
    def __init__(
        self,
        *,
        name: str,
        annotation: str,
        field_expr: str,
        uses_unresolved: bool,
        doc: str = "",
    ) -> None:
        self.name = name
        self.annotation = annotation
        self.field_expr = field_expr
        self.uses_unresolved = uses_unresolved
        self.doc = doc


# Field-type corrections for catalog data-type errors confirmed against the live API. The frozen
# catalog mistypes these response and request fields; each value is the real wire type observed
# live by the contract suite (optionality is applied separately, so give the base type). Keyed by
# (catalog type name, property name). See https://github.com/aaronmgn/stonepy/issues/24.
_FIELD_TYPE_OVERRIDES: dict[tuple[str, str], str] = {
    # News story ids are Reuters URN strings (e.g. "urn:newsml:reuters.com:..."), not ints.
    ("NewsHeadlineDTO", "StoryId"): "str",
    # The news payload is an array of stories, not a single one.
    ("NewsResponseDTO", "News"): "list[NewsDTO]",
    # A market carries a list of spreads (by time), not a single spread. Both the full market-info
    # DTO and the search-result DTO embed the same field.
    ("ApiMarketInformationDTOv2", "MarketSpreads"): "list[ApiMarketSpreadDTO]",
    ("MarketSearchResultDTO", "MarketSpreads"): "list[ApiMarketSpreadDTO]",
    # Market state is a single enum value, not a list.
    ("MarketPricesDTO", "MarketState"): "MarketState",
    # The Save* request bodies wrap a single object, not a list: the live API rejects an array with
    # HTTP 400 ("The JSON value could not be converted to ... ClientPreferenceKeyDTO / Watchlist").
    ("ApiSaveClientPreferenceRequestDTO", "ClientPreference"): "ClientPreferenceKeyDTO",
    ("SaveClientPreferenceRequestDTO", "ClientPreference"): "ClientPreferenceKeyDTO",
    ("SaveWatchlistRequestDTO", "Watchlist"): "ApiClientAccountWatchlistDTO",
}


def resolved_field_annotation(
    type_name: str, prop: Mapping[str, Any], known_names: set[str]
) -> str:
    """Return a field's base annotation, applying confirmed catalog field-type corrections.

    Shared by model rendering and contract-test sample generation so the corrected models and the
    samples that exercise them agree on the field type.
    """

    raw_name = prop.get("name")
    if isinstance(raw_name, str):
        override = _FIELD_TYPE_OVERRIDES.get((type_name, raw_name))
        if override is not None:
            return override
    return python_type(prop, known_names)


def _model_fields(
    rec: TypeRecord,
    known_names: set[str],
    *,
    force_optional: set[str] | None = None,
    all_optional: bool = False,
) -> list[_RenderedField]:
    rendered: list[_RenderedField] = []
    used_names: set[str] = set()
    for prop in rec.properties:
        raw_name = prop.get("name")
        if not isinstance(raw_name, str):
            continue
        name = field_name(raw_name)
        if name is None:
            continue

        name = _unique_field_name(name, used_names)
        annotation = resolved_field_annotation(rec.name, prop, known_names)
        optional = (
            all_optional
            or _is_optional_property(prop)
            or (force_optional is not None and raw_name in force_optional)
        )
        alias = _string_literal(raw_name)
        secret_suffix = ", repr=False" if raw_name.lower() in _SECRET_FIELD_RAW_NAMES else ""
        if optional:
            annotation = f"{annotation} | None"
            field_expr = f"Field(default=None, alias={alias}{secret_suffix})"
        else:
            field_expr = f"Field(alias={alias}{secret_suffix})"
        description = prop.get("description")
        rendered.append(
            _RenderedField(
                name=name,
                annotation=annotation,
                field_expr=field_expr,
                uses_unresolved="Unresolved" in _annotation_tokens(annotation),
                doc=render_docstring(
                    description if isinstance(description, str) else None, indent=4
                ),
            )
        )
    return rendered


def _unique_field_name(name: str, used_names: set[str]) -> str:
    if name not in used_names:
        used_names.add(name)
        return name

    suffix = 2
    while f"{name}_{suffix}" in used_names:
        suffix += 1
    unique = f"{name}_{suffix}"
    used_names.add(unique)
    return unique


def _is_optional_property(prop: Mapping[str, Any]) -> bool:
    if prop.get("required") is False or prop.get("nullable") is True:
        return True

    raw_type = prop.get("type")
    if not isinstance(raw_type, str) or not raw_type:
        return True

    normalized = " ".join(raw_type.lower().split())
    return "nullable true" in normalized or "required false" in normalized


def _string_literal(value: str) -> str:
    return json.dumps(value)


def _base_model(rec: TypeRecord, request_types: Collection[str] | None) -> str:
    if request_types is not None:
        return "RequestModel" if rec.name in request_types else "ResponseModel"
    return "RequestModel" if "RequestDTO" in rec.name else "ResponseModel"


def _model_imports(
    *,
    annotations: list[str],
    base_model: str,
    uses_field: bool,
    uses_unresolved: bool,
    enum_names: set[str] | None,
    known_names: set[str],
    owner: str,
) -> list[str]:
    lines: list[str] = []
    tokens = set().union(*(_annotation_tokens(annotation) for annotation in annotations))

    if "Decimal" in tokens:
        lines.append("from decimal import Decimal\n")

    known_deps = (tokens & known_names) - {owner}
    known_model_deps = sorted(known_deps - enum_names) if enum_names is not None else []
    guessed_enum_deps = sorted(known_deps) if enum_names is None else []
    typing_imports: list[str] = []
    if uses_unresolved or guessed_enum_deps:
        typing_imports.append("Any")
    if known_model_deps:
        typing_imports.append("TYPE_CHECKING")
    if typing_imports:
        lines.append(f"from typing import {', '.join(typing_imports)}\n")

    if uses_field:
        lines.append("from pydantic import Field\n")

    enum_deps = sorted((tokens & (enum_names or set())) - {owner})
    if enum_deps:
        lines.append(f"from .enums import {', '.join(enum_deps)}\n")

    for dependency in guessed_enum_deps:
        lines.append(
            f"try:\n"
            f"    from .enums import {dependency}\n"
            f"except ImportError:\n"
            f"    {dependency} = Any\n"
        )

    core_imports = [base_model]
    if "StoneXDateTime" in tokens:
        core_imports.append("StoneXDateTime")
    lines.append(f"from stonepy._core.models import {', '.join(core_imports)}\n")

    if known_model_deps:
        lines.append("\nif TYPE_CHECKING:\n")
        for dependency in known_model_deps:
            lines.append(f"    from .{dependency} import {dependency}\n")

    return lines


def _annotation_tokens(annotation: str) -> set[str]:
    return set(_IDENTIFIER_RE.findall(annotation))


def _render_enum_class(rec: TypeRecord) -> str:
    # The class docstring (always present via the fallback) keeps the body non-empty, so an
    # enum with no decodable members needs no ``pass``.
    lines = [
        f"class {rec.name}(IntEnum):\n",
        render_docstring(rec.description, indent=4, fallback=_enum_fallback(rec)),
    ]
    members = _enum_members(rec.properties)
    if not members:
        return "".join(lines)

    used_names: set[str] = set()
    for label, code in members:
        member_name = _unique_field_name(python_name(label), used_names)
        lines.append(f"    {member_name} = {code}\n")
    return "".join(lines)


def _enum_members(properties: list[JsonObject]) -> list[tuple[str, int]]:
    members: list[tuple[str, int]] = []
    for prop in properties:
        raw_name = prop.get("name")
        raw_type = prop.get("type")
        if _is_integer_code(raw_type) and isinstance(raw_name, str) and raw_name.strip():
            type_code = cast(str, raw_type)
            members.append((raw_name, int(type_code.strip())))
        elif _is_integer_code(raw_name) and isinstance(raw_type, str) and raw_type.strip():
            name_code = cast(str, raw_name)
            members.append((raw_type, int(name_code.strip())))
    return members


def _is_integer_code(value: object) -> bool:
    return isinstance(value, str) and value.strip().isdigit()
