# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from collections.abc import Awaitable, Callable
from types import TracebackType

from stonepy._core.clock import Clock, SystemClock
from stonepy._core.config import ClientConfig
from stonepy._core.pipeline import CallContext
from stonepy._core.plugins import discover_plugin_resources
from stonepy._core.ratelimit import BucketedSlidingWindowLimiter
from stonepy._core.resource import BaseResource
from stonepy._core.retry import RetryPolicy
from stonepy._core.session import AsyncSessionManager, SessionManager
from stonepy._core.transport import AsyncTransport, SyncTransport
from stonepy._endpoints import session as _session_ep
from stonepy.models import ApiLogOnRequestDTO
from stonepy.resources.cfd import AsyncCfdResource, CfdResource
from stonepy.resources.clientapplication import (
    AsyncClientapplicationResource,
    ClientapplicationResource,
)
from stonepy.resources.clientpreference import (
    AsyncClientpreferenceResource,
    ClientpreferenceResource,
)
from stonepy.resources.margin import AsyncMarginResource, MarginResource
from stonepy.resources.market import AsyncMarketResource, MarketResource
from stonepy.resources.message import AsyncMessageResource, MessageResource
from stonepy.resources.news import AsyncNewsResource, NewsResource
from stonepy.resources.order import AsyncOrderResource, OrderResource
from stonepy.resources.preference import AsyncPreferenceResource, PreferenceResource
from stonepy.resources.price_alert import AsyncPriceAlertResource, PriceAlertResource
from stonepy.resources.session import AsyncSessionResource, SessionResource
from stonepy.resources.spread import AsyncSpreadResource, SpreadResource
from stonepy.resources.user_account import AsyncUserAccountResource, UserAccountResource
from stonepy.resources.watchlist import AsyncWatchlistResource, WatchlistResource


def _missing_logon() -> tuple[str, str]:
    raise RuntimeError("session refresh is not configured")


def _has_config_credentials(config: ClientConfig) -> bool:
    return bool(config.username and config.password and config.app_key)


def _logon_request(config: ClientConfig) -> ApiLogOnRequestDTO:
    return ApiLogOnRequestDTO(
        UserName=config.username,
        Password=config.password,
        AppKey=config.app_key,
        AppVersion=config.app_version,
        AppComments="",
    )


def _config_logon(ctx: CallContext, config: ClientConfig) -> Callable[[], tuple[str, str]]:
    if not _has_config_credentials(config):
        return _missing_logon

    def logon() -> tuple[str, str]:
        return (
            _session_ep.log_on(ctx, _logon_request(config)).session or "",
            config.username,
        )

    return logon


def _async_config_logon(
    ctx: CallContext, config: ClientConfig
) -> Callable[[], Awaitable[tuple[str, str]]] | None:
    if not _has_config_credentials(config):
        return None

    async def alogon() -> tuple[str, str]:
        return (
            await _session_ep.alog_on(ctx, _logon_request(config))
        ).session or "", config.username

    return alogon


def _load_plugin_resources(config: ClientConfig, known: set[str]) -> dict[str, type[BaseResource]]:
    return discover_plugin_resources(
        enable=config.enable_plugins,
        allow_overrides=config.allow_overrides,
        known=known,
    )


def _build_context(
    config: ClientConfig, clock: Clock | None = None
) -> tuple[CallContext, SyncTransport]:
    real_clock = clock or SystemClock()
    transport = SyncTransport(config)
    session = SessionManager(real_clock, config.proactive_refresh_seconds)
    ctx = CallContext(
        config=config,
        transport=transport,
        session=session,
        limiter=BucketedSlidingWindowLimiter(
            config.rate_limit_max,
            config.rate_limit_window_seconds,
            real_clock,
        ),
        retry=RetryPolicy(config.max_retries),
        clock=real_clock,
        logon=_missing_logon,
    )
    ctx.logon = _config_logon(ctx, config)
    return ctx, transport


def _build_async_context(
    config: ClientConfig, clock: Clock | None = None
) -> tuple[CallContext, AsyncTransport]:
    real_clock = clock or SystemClock()
    transport = AsyncTransport(config)
    session = AsyncSessionManager(real_clock, config.proactive_refresh_seconds)
    ctx = CallContext(
        config=config,
        transport=transport,
        session=session,
        limiter=BucketedSlidingWindowLimiter(
            config.rate_limit_max,
            config.rate_limit_window_seconds,
            real_clock,
        ),
        retry=RetryPolicy(config.max_retries),
        clock=real_clock,
        logon=_missing_logon,
    )
    ctx.logon = _config_logon(ctx, config)
    ctx.alogon = _async_config_logon(ctx, config)
    return ctx, transport


class StoneXClient:
    """Synchronous StoneX CIAPI v2 client.

    Use as a context manager or call ``close()`` when finished. Resource properties
    lazily construct typed API resource groups.
    """

    def __init__(self, config: ClientConfig) -> None:
        self._ctx, self._transport = _build_context(config)
        self._plugins: dict[str, BaseResource] = {
            name: resource(self._ctx)
            for name, resource in _load_plugin_resources(
                config,
                {
                    "cfd",
                    "clientapplication",
                    "clientpreference",
                    "margin",
                    "market",
                    "message",
                    "news",
                    "order",
                    "preference",
                    "price_alert",
                    "session",
                    "spread",
                    "user_account",
                    "watchlist",
                },
            ).items()
        }
        self._cfd: CfdResource | None = None
        self._clientapplication: ClientapplicationResource | None = None
        self._clientpreference: ClientpreferenceResource | None = None
        self._margin: MarginResource | None = None
        self._market: MarketResource | None = None
        self._message: MessageResource | None = None
        self._news: NewsResource | None = None
        self._order: OrderResource | None = None
        self._preference: PreferenceResource | None = None
        self._price_alert: PriceAlertResource | None = None
        self._session: SessionResource | None = None
        self._spread: SpreadResource | None = None
        self._user_account: UserAccountResource | None = None
        self._watchlist: WatchlistResource | None = None

    @property
    def cfd(self) -> CfdResource:
        """Return the cfd resource group."""
        if self._cfd is None:
            self._cfd = CfdResource(self._ctx)
        return self._cfd

    @property
    def clientapplication(self) -> ClientapplicationResource:
        """Return the clientapplication resource group."""
        if self._clientapplication is None:
            self._clientapplication = ClientapplicationResource(self._ctx)
        return self._clientapplication

    @property
    def clientpreference(self) -> ClientpreferenceResource:
        """Return the clientpreference resource group."""
        if self._clientpreference is None:
            self._clientpreference = ClientpreferenceResource(self._ctx)
        return self._clientpreference

    @property
    def margin(self) -> MarginResource:
        """Return the margin resource group."""
        if self._margin is None:
            self._margin = MarginResource(self._ctx)
        return self._margin

    @property
    def market(self) -> MarketResource:
        """Return the market resource group."""
        if self._market is None:
            self._market = MarketResource(self._ctx)
        return self._market

    @property
    def message(self) -> MessageResource:
        """Return the message resource group."""
        if self._message is None:
            self._message = MessageResource(self._ctx)
        return self._message

    @property
    def news(self) -> NewsResource:
        """Return the news resource group."""
        if self._news is None:
            self._news = NewsResource(self._ctx)
        return self._news

    @property
    def order(self) -> OrderResource:
        """Return the order resource group."""
        if self._order is None:
            self._order = OrderResource(self._ctx)
        return self._order

    @property
    def preference(self) -> PreferenceResource:
        """Return the preference resource group."""
        if self._preference is None:
            self._preference = PreferenceResource(self._ctx)
        return self._preference

    @property
    def price_alert(self) -> PriceAlertResource:
        """Return the price_alert resource group."""
        if self._price_alert is None:
            self._price_alert = PriceAlertResource(self._ctx)
        return self._price_alert

    @property
    def session(self) -> SessionResource:
        """Return the session resource group."""
        if self._session is None:
            self._session = SessionResource(self._ctx)
        return self._session

    @property
    def spread(self) -> SpreadResource:
        """Return the spread resource group."""
        if self._spread is None:
            self._spread = SpreadResource(self._ctx)
        return self._spread

    @property
    def user_account(self) -> UserAccountResource:
        """Return the user_account resource group."""
        if self._user_account is None:
            self._user_account = UserAccountResource(self._ctx)
        return self._user_account

    @property
    def watchlist(self) -> WatchlistResource:
        """Return the watchlist resource group."""
        if self._watchlist is None:
            self._watchlist = WatchlistResource(self._ctx)
        return self._watchlist

    def plugin(self, name: str) -> BaseResource:
        """Return a loaded plugin resource by name."""
        return self._plugins[name]

    def __enter__(self) -> StoneXClient:
        """Enter the synchronous client context."""
        return self

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        traceback: TracebackType | None,
    ) -> None:
        """Close the synchronous client context."""
        self.close()

    def close(self) -> None:
        """Close the underlying synchronous HTTP transport."""
        self._transport.close()


class AsyncStoneXClient:
    """Asynchronous StoneX CIAPI v2 client.

    Use with ``async with`` or call ``aclose()`` when finished. Resource properties
    mirror the synchronous client and expose awaitable methods.
    """

    def __init__(self, config: ClientConfig) -> None:
        self._ctx, self._transport = _build_async_context(config)
        self._plugins: dict[str, BaseResource] = {
            name: resource(self._ctx)
            for name, resource in _load_plugin_resources(
                config,
                {
                    "cfd",
                    "clientapplication",
                    "clientpreference",
                    "margin",
                    "market",
                    "message",
                    "news",
                    "order",
                    "preference",
                    "price_alert",
                    "session",
                    "spread",
                    "user_account",
                    "watchlist",
                },
            ).items()
        }
        self._cfd: AsyncCfdResource | None = None
        self._clientapplication: AsyncClientapplicationResource | None = None
        self._clientpreference: AsyncClientpreferenceResource | None = None
        self._margin: AsyncMarginResource | None = None
        self._market: AsyncMarketResource | None = None
        self._message: AsyncMessageResource | None = None
        self._news: AsyncNewsResource | None = None
        self._order: AsyncOrderResource | None = None
        self._preference: AsyncPreferenceResource | None = None
        self._price_alert: AsyncPriceAlertResource | None = None
        self._session: AsyncSessionResource | None = None
        self._spread: AsyncSpreadResource | None = None
        self._user_account: AsyncUserAccountResource | None = None
        self._watchlist: AsyncWatchlistResource | None = None

    @property
    def cfd(self) -> AsyncCfdResource:
        """Return the cfd resource group."""
        if self._cfd is None:
            self._cfd = AsyncCfdResource(self._ctx)
        return self._cfd

    @property
    def clientapplication(self) -> AsyncClientapplicationResource:
        """Return the clientapplication resource group."""
        if self._clientapplication is None:
            self._clientapplication = AsyncClientapplicationResource(self._ctx)
        return self._clientapplication

    @property
    def clientpreference(self) -> AsyncClientpreferenceResource:
        """Return the clientpreference resource group."""
        if self._clientpreference is None:
            self._clientpreference = AsyncClientpreferenceResource(self._ctx)
        return self._clientpreference

    @property
    def margin(self) -> AsyncMarginResource:
        """Return the margin resource group."""
        if self._margin is None:
            self._margin = AsyncMarginResource(self._ctx)
        return self._margin

    @property
    def market(self) -> AsyncMarketResource:
        """Return the market resource group."""
        if self._market is None:
            self._market = AsyncMarketResource(self._ctx)
        return self._market

    @property
    def message(self) -> AsyncMessageResource:
        """Return the message resource group."""
        if self._message is None:
            self._message = AsyncMessageResource(self._ctx)
        return self._message

    @property
    def news(self) -> AsyncNewsResource:
        """Return the news resource group."""
        if self._news is None:
            self._news = AsyncNewsResource(self._ctx)
        return self._news

    @property
    def order(self) -> AsyncOrderResource:
        """Return the order resource group."""
        if self._order is None:
            self._order = AsyncOrderResource(self._ctx)
        return self._order

    @property
    def preference(self) -> AsyncPreferenceResource:
        """Return the preference resource group."""
        if self._preference is None:
            self._preference = AsyncPreferenceResource(self._ctx)
        return self._preference

    @property
    def price_alert(self) -> AsyncPriceAlertResource:
        """Return the price_alert resource group."""
        if self._price_alert is None:
            self._price_alert = AsyncPriceAlertResource(self._ctx)
        return self._price_alert

    @property
    def session(self) -> AsyncSessionResource:
        """Return the session resource group."""
        if self._session is None:
            self._session = AsyncSessionResource(self._ctx)
        return self._session

    @property
    def spread(self) -> AsyncSpreadResource:
        """Return the spread resource group."""
        if self._spread is None:
            self._spread = AsyncSpreadResource(self._ctx)
        return self._spread

    @property
    def user_account(self) -> AsyncUserAccountResource:
        """Return the user_account resource group."""
        if self._user_account is None:
            self._user_account = AsyncUserAccountResource(self._ctx)
        return self._user_account

    @property
    def watchlist(self) -> AsyncWatchlistResource:
        """Return the watchlist resource group."""
        if self._watchlist is None:
            self._watchlist = AsyncWatchlistResource(self._ctx)
        return self._watchlist

    def plugin(self, name: str) -> BaseResource:
        """Return a loaded plugin resource by name."""
        return self._plugins[name]

    async def __aenter__(self) -> AsyncStoneXClient:
        """Enter the asynchronous client context."""
        return self

    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        traceback: TracebackType | None,
    ) -> None:
        """Close the asynchronous client context."""
        await self.aclose()

    async def aclose(self) -> None:
        """Close the underlying asynchronous HTTP transport."""
        await self._transport.aclose()
