# GENERATED by stonepy._generator. Do not edit by hand.
"""Synchronous and asynchronous order_including_closed resource group classes."""

from __future__ import annotations

from stonepy._core.resource import BaseResource

from ._sync.get_order_including_closed import (
    _GetOrderIncludingClosedMixin as _SyncGetOrderIncludingClosedMixin,
)
from .get_order_including_closed import (
    _GetOrderIncludingClosedMixin as _AsyncGetOrderIncludingClosedMixin,
)


class OrderIncludingClosedResource(_SyncGetOrderIncludingClosedMixin, BaseResource):
    """
    Synchronous `order_including_closed` resource group; access it via
    `StoneXClient.order_including_closed`. Each method maps to one StoneX CIAPI v2 endpoint.
    """


class AsyncOrderIncludingClosedResource(_AsyncGetOrderIncludingClosedMixin, BaseResource):
    """
    Asynchronous `order_including_closed` resource group; access it via
    `AsyncStoneXClient.order_including_closed`. Each method is the awaitable twin of the
    synchronous resource's method.
    """


__all__ = [
    "AsyncOrderIncludingClosedResource",
    "OrderIncludingClosedResource",
]
