# GENERATED by stonepy._generator. Do not edit by hand.
"""Generated StoneX CIAPI v2 endpoint binding modules, one per API target."""

from __future__ import annotations

from . import (
    cfd,
    clientapplication,
    clientpreference,
    margin,
    market,
    message,
    news,
    order,
    preference,
    price_alert,
    session,
    spread,
    user_account,
    watchlist,
)

__all__ = [
    "cfd",
    "clientapplication",
    "clientpreference",
    "margin",
    "market",
    "message",
    "news",
    "order",
    "preference",
    "price_alert",
    "session",
    "spread",
    "user_account",
    "watchlist",
]
