# GENERATED by stonepy._generator. Do not edit by hand.
"""Generated endpoint bindings for the StoneX CIAPI v2 margin target."""

from __future__ import annotations

from stonepy._core.endpoint import AuthPolicy, EndpointSpec, Param
from stonepy._core.pipeline import CallContext
from stonepy.models import ClientAccountMarginResponseDTO

GET_CLIENT_ACCOUNT_MARGIN_SPEC: EndpointSpec[ClientAccountMarginResponseDTO] = EndpointSpec(
    name="GetClientAccountMargin v2",
    method="GET",
    path="/margin/v2/margin/clientAccountMargin?clientAccountId={clientAccountId}",
    idempotent=True,
    auth_policy=AuthPolicy.SESSION,
    rate_limit_bucket="margin",
    response_model=ClientAccountMarginResponseDTO,
    params=(Param(name="ClientAccountId", location="query", python_name="client_account_id"),),
)


def get_client_account_margin(
    ctx: CallContext, client_account_id: int
) -> ClientAccountMarginResponseDTO:
    """Returns the information about client account margin."""
    return ctx.invoke(GET_CLIENT_ACCOUNT_MARGIN_SPEC, query={"ClientAccountId": client_account_id})


async def aget_client_account_margin(
    ctx: CallContext, client_account_id: int
) -> ClientAccountMarginResponseDTO:
    """Returns the information about client account margin."""
    return await ctx.ainvoke(
        GET_CLIENT_ACCOUNT_MARGIN_SPEC, query={"ClientAccountId": client_account_id}
    )


__all__ = [
    "GET_CLIENT_ACCOUNT_MARGIN_SPEC",
    "get_client_account_margin",
    "aget_client_account_margin",
]
