# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from stonepy._core.endpoint import AuthPolicy, EndpointSpec, Param
from stonepy._core.pipeline import CallContext
from stonepy.models import (
    ApiSimulateTradeOrderResponseDTO,
    ApiTradeOrderResponseDTO,
    CancelOrderRequestDTO,
    GetActiveStopLimitOrderResponseDTOv2,
    GetOpenPositionResponseDTOv2,
    GetOrderResponseDTOv2,
    ListActiveOrdersRequestDTO,
    ListActiveOrdersResponseDTO,
    ListActiveStopLimitOrderResponseDTO,
    ListOpenPositionsResponseDTO,
    ListStopLimitOrderHistoryResponseDTO,
    ListTradeHistoryResponseDTO,
    NewStopLimitOrderRequestDTO,
    NewTradeOrderRequestDTO,
)

CANCEL_ORDER_SPEC: EndpointSpec[ApiTradeOrderResponseDTO] = EndpointSpec(
    name="CancelOrder",
    method="POST",
    path="/order/cancel",
    idempotent=False,
    auth_policy=AuthPolicy.SESSION,
    rate_limit_bucket="order",
    response_model=ApiTradeOrderResponseDTO,
    request_model=CancelOrderRequestDTO,
    params=(Param(name="cancelOrder", location="body", python_name="cancel_order"),),
)


def cancel_order(ctx: CallContext, request: CancelOrderRequestDTO) -> ApiTradeOrderResponseDTO:
    return ctx.invoke(CANCEL_ORDER_SPEC, body=request)


async def acancel_order(
    ctx: CallContext, request: CancelOrderRequestDTO
) -> ApiTradeOrderResponseDTO:
    return await ctx.ainvoke(CANCEL_ORDER_SPEC, body=request)


GET_ACTIVE_STOP_LIMIT_ORDER_SPEC: EndpointSpec[GetActiveStopLimitOrderResponseDTOv2] = EndpointSpec(
    name="GetActiveStopLimitOrder",
    method="GET",
    path="/order/{OrderId}/activestoplimitorder",
    idempotent=True,
    auth_policy=AuthPolicy.SESSION,
    rate_limit_bucket="order",
    response_model=GetActiveStopLimitOrderResponseDTOv2,
    params=(Param(name="OrderId", location="path", python_name="order_id"),),
)


def get_active_stop_limit_order(
    ctx: CallContext, order_id: int
) -> GetActiveStopLimitOrderResponseDTOv2:
    return ctx.invoke(GET_ACTIVE_STOP_LIMIT_ORDER_SPEC, path_params={"OrderId": order_id})


async def aget_active_stop_limit_order(
    ctx: CallContext, order_id: int
) -> GetActiveStopLimitOrderResponseDTOv2:
    return await ctx.ainvoke(GET_ACTIVE_STOP_LIMIT_ORDER_SPEC, path_params={"OrderId": order_id})


GET_OPEN_POSITION_SPEC: EndpointSpec[GetOpenPositionResponseDTOv2] = EndpointSpec(
    name="GetOpenPosition",
    method="GET",
    path="/order/{OrderId}/openposition",
    idempotent=True,
    auth_policy=AuthPolicy.SESSION,
    rate_limit_bucket="order",
    response_model=GetOpenPositionResponseDTOv2,
    params=(Param(name="OrderId", location="path", python_name="order_id"),),
)


def get_open_position(ctx: CallContext, order_id: str) -> GetOpenPositionResponseDTOv2:
    return ctx.invoke(GET_OPEN_POSITION_SPEC, path_params={"OrderId": order_id})


async def aget_open_position(ctx: CallContext, order_id: str) -> GetOpenPositionResponseDTOv2:
    return await ctx.ainvoke(GET_OPEN_POSITION_SPEC, path_params={"OrderId": order_id})


GET_ORDER_SPEC: EndpointSpec[GetOrderResponseDTOv2] = EndpointSpec(
    name="GetOrder",
    method="GET",
    path="/order/{OrderId}",
    idempotent=True,
    auth_policy=AuthPolicy.SESSION,
    rate_limit_bucket="order",
    response_model=GetOrderResponseDTOv2,
    params=(Param(name="OrderId", location="path", python_name="order_id"),),
)


def get_order(ctx: CallContext, order_id: int) -> GetOrderResponseDTOv2:
    return ctx.invoke(GET_ORDER_SPEC, path_params={"OrderId": order_id})


async def aget_order(ctx: CallContext, order_id: int) -> GetOrderResponseDTOv2:
    return await ctx.ainvoke(GET_ORDER_SPEC, path_params={"OrderId": order_id})


LIST_ACTIVE_ORDERS_SPEC: EndpointSpec[ListActiveOrdersResponseDTO] = EndpointSpec(
    name="ListActiveOrders",
    method="POST",
    path="/order/activeorders",
    idempotent=True,
    auth_policy=AuthPolicy.SESSION,
    rate_limit_bucket="order",
    response_model=ListActiveOrdersResponseDTO,
    request_model=ListActiveOrdersRequestDTO,
    params=(Param(name="requestDTO", location="query", python_name="request_dto"),),
)


def list_active_orders(
    ctx: CallContext, request_dto: ListActiveOrdersRequestDTO
) -> ListActiveOrdersResponseDTO:
    return ctx.invoke(
        LIST_ACTIVE_ORDERS_SPEC,
        query=request_dto.model_dump(by_alias=True, exclude_unset=True, mode="python"),
    )


async def alist_active_orders(
    ctx: CallContext, request_dto: ListActiveOrdersRequestDTO
) -> ListActiveOrdersResponseDTO:
    return await ctx.ainvoke(
        LIST_ACTIVE_ORDERS_SPEC,
        query=request_dto.model_dump(by_alias=True, exclude_unset=True, mode="python"),
    )


LIST_ACTIVE_STOP_LIMIT_ORDERS_SPEC: EndpointSpec[ListActiveStopLimitOrderResponseDTO] = (
    EndpointSpec(
        name="ListActiveStopLimitOrders",
        method="GET",
        path="/order/activestoplimitorders?TradingAccountId={TradingAccountId}",
        idempotent=True,
        auth_policy=AuthPolicy.SESSION,
        rate_limit_bucket="order",
        response_model=ListActiveStopLimitOrderResponseDTO,
        params=(
            Param(name="TradingAccountId", location="query", python_name="trading_account_id"),
        ),
    )
)


def list_active_stop_limit_orders(
    ctx: CallContext, *, trading_account_id: int | None = None
) -> ListActiveStopLimitOrderResponseDTO:
    return ctx.invoke(
        LIST_ACTIVE_STOP_LIMIT_ORDERS_SPEC, query={"TradingAccountId": trading_account_id}
    )


async def alist_active_stop_limit_orders(
    ctx: CallContext, *, trading_account_id: int | None = None
) -> ListActiveStopLimitOrderResponseDTO:
    return await ctx.ainvoke(
        LIST_ACTIVE_STOP_LIMIT_ORDERS_SPEC, query={"TradingAccountId": trading_account_id}
    )


LIST_OPEN_POSITIONS_SPEC: EndpointSpec[ListOpenPositionsResponseDTO] = EndpointSpec(
    name="ListOpenPositions",
    method="GET",
    path="/order/openpositions?TradingAccountId={TradingAccountId}",
    idempotent=True,
    auth_policy=AuthPolicy.SESSION,
    rate_limit_bucket="order",
    response_model=ListOpenPositionsResponseDTO,
    params=(Param(name="TradingAccountId", location="query", python_name="trading_account_id"),),
)


def list_open_positions(
    ctx: CallContext, *, trading_account_id: int | None = None
) -> ListOpenPositionsResponseDTO:
    return ctx.invoke(LIST_OPEN_POSITIONS_SPEC, query={"TradingAccountId": trading_account_id})


async def alist_open_positions(
    ctx: CallContext, *, trading_account_id: int | None = None
) -> ListOpenPositionsResponseDTO:
    return await ctx.ainvoke(
        LIST_OPEN_POSITIONS_SPEC, query={"TradingAccountId": trading_account_id}
    )


LIST_STOP_LIMIT_ORDER_HISTORY_SPEC: EndpointSpec[ListStopLimitOrderHistoryResponseDTO] = (
    EndpointSpec(
        name="ListStopLimitOrderHistory",
        method="GET",
        path="/order/stoplimitorderhistory",
        idempotent=True,
        auth_policy=AuthPolicy.SESSION,
        rate_limit_bucket="order",
        response_model=ListStopLimitOrderHistoryResponseDTO,
        params=(
            Param(name="TradingAccountId", location="query", python_name="trading_account_id"),
            Param(name="maxResults", location="query", python_name="max_results"),
            Param(name="from", location="query", python_name="from_"),
        ),
    )
)


def list_stop_limit_order_history(
    ctx: CallContext,
    *,
    trading_account_id: int | None = None,
    max_results: int | None = None,
    from_: int | None = None,
) -> ListStopLimitOrderHistoryResponseDTO:
    return ctx.invoke(
        LIST_STOP_LIMIT_ORDER_HISTORY_SPEC,
        query={"TradingAccountId": trading_account_id, "maxResults": max_results, "from": from_},
    )


async def alist_stop_limit_order_history(
    ctx: CallContext,
    *,
    trading_account_id: int | None = None,
    max_results: int | None = None,
    from_: int | None = None,
) -> ListStopLimitOrderHistoryResponseDTO:
    return await ctx.ainvoke(
        LIST_STOP_LIMIT_ORDER_HISTORY_SPEC,
        query={"TradingAccountId": trading_account_id, "maxResults": max_results, "from": from_},
    )


LIST_TRADE_HISTORY_SPEC: EndpointSpec[ListTradeHistoryResponseDTO] = EndpointSpec(
    name="ListTradeHistory",
    method="GET",
    path="/order/tradehistory",
    idempotent=True,
    auth_policy=AuthPolicy.SESSION,
    rate_limit_bucket="order",
    response_model=ListTradeHistoryResponseDTO,
    params=(
        Param(name="TradingAccountId", location="query", python_name="trading_account_id"),
        Param(name="maxResults", location="query", python_name="max_results"),
        Param(name="from", location="query", python_name="from_"),
    ),
)


def list_trade_history(
    ctx: CallContext,
    *,
    trading_account_id: int | None = None,
    max_results: int | None = None,
    from_: int | None = None,
) -> ListTradeHistoryResponseDTO:
    return ctx.invoke(
        LIST_TRADE_HISTORY_SPEC,
        query={"TradingAccountId": trading_account_id, "maxResults": max_results, "from": from_},
    )


async def alist_trade_history(
    ctx: CallContext,
    *,
    trading_account_id: int | None = None,
    max_results: int | None = None,
    from_: int | None = None,
) -> ListTradeHistoryResponseDTO:
    return await ctx.ainvoke(
        LIST_TRADE_HISTORY_SPEC,
        query={"TradingAccountId": trading_account_id, "maxResults": max_results, "from": from_},
    )


ORDER_SPEC: EndpointSpec[ApiTradeOrderResponseDTO] = EndpointSpec(
    name="Order",
    method="POST",
    path="/order/newstoplimitorder",
    idempotent=False,
    auth_policy=AuthPolicy.SESSION,
    rate_limit_bucket="order",
    response_model=ApiTradeOrderResponseDTO,
    request_model=NewStopLimitOrderRequestDTO,
    params=(Param(name="order", location="body", python_name="order"),),
)


def order(ctx: CallContext, request: NewStopLimitOrderRequestDTO) -> ApiTradeOrderResponseDTO:
    return ctx.invoke(ORDER_SPEC, body=request)


async def aorder(
    ctx: CallContext, request: NewStopLimitOrderRequestDTO
) -> ApiTradeOrderResponseDTO:
    return await ctx.ainvoke(ORDER_SPEC, body=request)


SIMULATE_TRADE_SPEC: EndpointSpec[ApiSimulateTradeOrderResponseDTO] = EndpointSpec(
    name="SimulateTrade",
    method="POST",
    path="/order/simulate/newtradeorder",
    idempotent=False,
    auth_policy=AuthPolicy.SESSION,
    rate_limit_bucket="order",
    response_model=ApiSimulateTradeOrderResponseDTO,
    request_model=NewTradeOrderRequestDTO,
    params=(Param(name="Trade", location="body", python_name="trade"),),
)


def simulate_trade(
    ctx: CallContext, request: NewTradeOrderRequestDTO
) -> ApiSimulateTradeOrderResponseDTO:
    return ctx.invoke(SIMULATE_TRADE_SPEC, body=request)


async def asimulate_trade(
    ctx: CallContext, request: NewTradeOrderRequestDTO
) -> ApiSimulateTradeOrderResponseDTO:
    return await ctx.ainvoke(SIMULATE_TRADE_SPEC, body=request)


__all__ = [
    "CANCEL_ORDER_SPEC",
    "cancel_order",
    "acancel_order",
    "GET_ACTIVE_STOP_LIMIT_ORDER_SPEC",
    "get_active_stop_limit_order",
    "aget_active_stop_limit_order",
    "GET_OPEN_POSITION_SPEC",
    "get_open_position",
    "aget_open_position",
    "GET_ORDER_SPEC",
    "get_order",
    "aget_order",
    "LIST_ACTIVE_ORDERS_SPEC",
    "list_active_orders",
    "alist_active_orders",
    "LIST_ACTIVE_STOP_LIMIT_ORDERS_SPEC",
    "list_active_stop_limit_orders",
    "alist_active_stop_limit_orders",
    "LIST_OPEN_POSITIONS_SPEC",
    "list_open_positions",
    "alist_open_positions",
    "LIST_STOP_LIMIT_ORDER_HISTORY_SPEC",
    "list_stop_limit_order_history",
    "alist_stop_limit_order_history",
    "LIST_TRADE_HISTORY_SPEC",
    "list_trade_history",
    "alist_trade_history",
    "ORDER_SPEC",
    "order",
    "aorder",
    "SIMULATE_TRADE_SPEC",
    "simulate_trade",
    "asimulate_trade",
]
