# GENERATED by stonepy._generator. Do not edit by hand.
"""Generated endpoint bindings for the StoneX CIAPI v2 pm target."""

from __future__ import annotations

from stonepy._core.endpoint import AuthPolicy, EndpointSpec
from stonepy._core.pipeline import CallContext
from stonepy._core.status import StatusDomain
from stonepy.models import (
    ActiveSignalsResponseDTO,
    ApiSaveSignalPreferencesResponseDTO,
    HistoricalOrdersResponseDTO,
    OpenOrdersResponseDTO,
    PendingOrdersResponseDTO,
    PreferenceDTO,
    SignalPerformanceResponseDTO,
)

GET_HISTORICAL_ORDERS_SPEC: EndpointSpec[HistoricalOrdersResponseDTO] = EndpointSpec(
    name="GetHistoricalOrders",
    method="GET",
    path="/pm/orders/historical",
    status_domain=StatusDomain.NONE,
    idempotent=True,
    auth_policy=AuthPolicy.SESSION,
    rate_limit_bucket="pm",
    response_model=HistoricalOrdersResponseDTO,
)


def get_historical_orders(ctx: CallContext) -> HistoricalOrdersResponseDTO:
    """
    All service calls and DTOs related to Predicted Markets are for internal StoneX use only.
    Retrieves a list of historical limit and market orders over the specified time period,
    which are cancelled, rejected, suspended, closed, or red carded together with their
    associated signal information.
    """
    return ctx.invoke(GET_HISTORICAL_ORDERS_SPEC)


async def aget_historical_orders(ctx: CallContext) -> HistoricalOrdersResponseDTO:
    """
    All service calls and DTOs related to Predicted Markets are for internal StoneX use only.
    Retrieves a list of historical limit and market orders over the specified time period,
    which are cancelled, rejected, suspended, closed, or red carded together with their
    associated signal information.
    """
    return await ctx.ainvoke(GET_HISTORICAL_ORDERS_SPEC)


GET_OPEN_ORDERS_SPEC: EndpointSpec[OpenOrdersResponseDTO] = EndpointSpec(
    name="GetOpenOrders",
    method="GET",
    path="/pm/orders/open",
    idempotent=True,
    auth_policy=AuthPolicy.SESSION,
    rate_limit_bucket="pm",
    response_model=OpenOrdersResponseDTO,
)


def get_open_orders(ctx: CallContext) -> OpenOrdersResponseDTO:
    """
    All service calls and DTOs related to Predicted Markets are for internal StoneX use only.
    Retrieves a list of market orders that have open status along with their associated signal
    information.
    """
    return ctx.invoke(GET_OPEN_ORDERS_SPEC)


async def aget_open_orders(ctx: CallContext) -> OpenOrdersResponseDTO:
    """
    All service calls and DTOs related to Predicted Markets are for internal StoneX use only.
    Retrieves a list of market orders that have open status along with their associated signal
    information.
    """
    return await ctx.ainvoke(GET_OPEN_ORDERS_SPEC)


GET_PENDING_ORDERS_SPEC: EndpointSpec[PendingOrdersResponseDTO] = EndpointSpec(
    name="GetPendingOrders",
    method="GET",
    path="/pm/orders/pending",
    idempotent=True,
    auth_policy=AuthPolicy.SESSION,
    rate_limit_bucket="pm",
    response_model=PendingOrdersResponseDTO,
)


def get_pending_orders(ctx: CallContext) -> PendingOrdersResponseDTO:
    """
    All service calls and DTOs related to Predicted Markets are for internal StoneX use only.
    Retrieves the list of pending orders.
    """
    return ctx.invoke(GET_PENDING_ORDERS_SPEC)


async def aget_pending_orders(ctx: CallContext) -> PendingOrdersResponseDTO:
    """
    All service calls and DTOs related to Predicted Markets are for internal StoneX use only.
    Retrieves the list of pending orders.
    """
    return await ctx.ainvoke(GET_PENDING_ORDERS_SPEC)


GET_SIGNAL_PERFORMANCE_SPEC: EndpointSpec[SignalPerformanceResponseDTO] = EndpointSpec(
    name="GetSignalPerformance",
    method="GET",
    path="/pm/signals/performance",
    idempotent=True,
    auth_policy=AuthPolicy.SESSION,
    rate_limit_bucket="pm",
    response_model=SignalPerformanceResponseDTO,
)


def get_signal_performance(ctx: CallContext) -> SignalPerformanceResponseDTO:
    """
    All service calls and DTOs related to Predicted Markets are for internal StoneX use only.
    Returns a list of the X top and bottom performing signals as well as a win/loss ratio for
    signals that have expired in the given time period (hours) . A percentage format is used
    to calculate the top and bottom performers.
    """
    return ctx.invoke(GET_SIGNAL_PERFORMANCE_SPEC)


async def aget_signal_performance(ctx: CallContext) -> SignalPerformanceResponseDTO:
    """
    All service calls and DTOs related to Predicted Markets are for internal StoneX use only.
    Returns a list of the X top and bottom performing signals as well as a win/loss ratio for
    signals that have expired in the given time period (hours) . A percentage format is used
    to calculate the top and bottom performers.
    """
    return await ctx.ainvoke(GET_SIGNAL_PERFORMANCE_SPEC)


GET_SIGNAL_PREFERENCES_SPEC: EndpointSpec[PreferenceDTO] = EndpointSpec(
    name="GetSignalPreferences",
    method="GET",
    path="/pm/preferences",
    idempotent=True,
    auth_policy=AuthPolicy.SESSION,
    rate_limit_bucket="pm",
    response_model=PreferenceDTO,
)


def get_signal_preferences(ctx: CallContext) -> PreferenceDTO:
    """
    All service calls and DTOs related to Predicted Markets are for internal StoneX use only.
    Retrieves the signal preferences for the authenticated user.
    """
    return ctx.invoke(GET_SIGNAL_PREFERENCES_SPEC)


async def aget_signal_preferences(ctx: CallContext) -> PreferenceDTO:
    """
    All service calls and DTOs related to Predicted Markets are for internal StoneX use only.
    Retrieves the signal preferences for the authenticated user.
    """
    return await ctx.ainvoke(GET_SIGNAL_PREFERENCES_SPEC)


LIST_ACTIVE_SIGNALS_SPEC: EndpointSpec[ActiveSignalsResponseDTO] = EndpointSpec(
    name="ListActiveSignals",
    method="GET",
    path="/pm/signals/active",
    idempotent=True,
    auth_policy=AuthPolicy.SESSION,
    rate_limit_bucket="pm",
    response_model=ActiveSignalsResponseDTO,
)


def list_active_signals(ctx: CallContext) -> ActiveSignalsResponseDTO:
    """
    All service calls and DTOs related to Predicted Markets are for internal StoneX use only.
    Returns a list of all active signals. These are signals with a status of
    WithinTriggerLevel (2) or Triggered (3).
    """
    return ctx.invoke(LIST_ACTIVE_SIGNALS_SPEC)


async def alist_active_signals(ctx: CallContext) -> ActiveSignalsResponseDTO:
    """
    All service calls and DTOs related to Predicted Markets are for internal StoneX use only.
    Returns a list of all active signals. These are signals with a status of
    WithinTriggerLevel (2) or Triggered (3).
    """
    return await ctx.ainvoke(LIST_ACTIVE_SIGNALS_SPEC)


SAVE_SIGNAL_PREFERENCES_SPEC: EndpointSpec[ApiSaveSignalPreferencesResponseDTO] = EndpointSpec(
    name="SaveSignalPreferences",
    method="POST",
    path="/pm/preferences",
    idempotent=False,
    auth_policy=AuthPolicy.SESSION,
    rate_limit_bucket="pm",
    response_model=ApiSaveSignalPreferencesResponseDTO,
)


def save_signal_preferences(ctx: CallContext) -> ApiSaveSignalPreferencesResponseDTO:
    """
    All service calls and DTOs related to Predicted Markets are for internal StoneX use only.
    Saves the signal preferences for the authenticated user.
    """
    return ctx.invoke(SAVE_SIGNAL_PREFERENCES_SPEC)


async def asave_signal_preferences(ctx: CallContext) -> ApiSaveSignalPreferencesResponseDTO:
    """
    All service calls and DTOs related to Predicted Markets are for internal StoneX use only.
    Saves the signal preferences for the authenticated user.
    """
    return await ctx.ainvoke(SAVE_SIGNAL_PREFERENCES_SPEC)


__all__ = [
    "GET_HISTORICAL_ORDERS_SPEC",
    "get_historical_orders",
    "aget_historical_orders",
    "GET_OPEN_ORDERS_SPEC",
    "get_open_orders",
    "aget_open_orders",
    "GET_PENDING_ORDERS_SPEC",
    "get_pending_orders",
    "aget_pending_orders",
    "GET_SIGNAL_PERFORMANCE_SPEC",
    "get_signal_performance",
    "aget_signal_performance",
    "GET_SIGNAL_PREFERENCES_SPEC",
    "get_signal_preferences",
    "aget_signal_preferences",
    "LIST_ACTIVE_SIGNALS_SPEC",
    "list_active_signals",
    "alist_active_signals",
    "SAVE_SIGNAL_PREFERENCES_SPEC",
    "save_signal_preferences",
    "asave_signal_preferences",
]
