# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from stonepy._core.endpoint import AuthPolicy, EndpointSpec, Param
from stonepy._core.models import ResponseModel
from stonepy._core.pipeline import CallContext
from stonepy.models import ApiGetPreferencesResponseDTO, ApiSavePreferencesRequestDTO

DELETE_USER_PREFERENCE_SPEC: EndpointSpec[ResponseModel] = EndpointSpec(
    name="DeleteUserPreference v2",
    method="DELETE",
    path="/preference/v2/Preference",
    idempotent=True,
    auth_policy=AuthPolicy.SESSION,
    rate_limit_bucket="preference",
    response_model=ResponseModel,
    params=(Param(name="Preferences", location="body", python_name="preferences"),),
)


def delete_user_preference(
    ctx: CallContext, *, preferences: list[str] | None = None
) -> ResponseModel:
    return ctx.invoke(DELETE_USER_PREFERENCE_SPEC, body={"Preferences": preferences})


async def adelete_user_preference(
    ctx: CallContext, *, preferences: list[str] | None = None
) -> ResponseModel:
    return await ctx.ainvoke(DELETE_USER_PREFERENCE_SPEC, body={"Preferences": preferences})


GET_USER_PREFERENCE_SPEC: EndpointSpec[ApiGetPreferencesResponseDTO] = EndpointSpec(
    name="GetUserPreference v2",
    method="GET",
    path="/preference/v2/Preferences",
    idempotent=True,
    auth_policy=AuthPolicy.SESSION,
    rate_limit_bucket="preference",
    response_model=ApiGetPreferencesResponseDTO,
    params=(Param(name="Preferences", location="query", python_name="preferences"),),
)


def get_user_preference(
    ctx: CallContext, *, preferences: list[str] | None = None
) -> ApiGetPreferencesResponseDTO:
    return ctx.invoke(GET_USER_PREFERENCE_SPEC, query={"Preferences": preferences})


async def aget_user_preference(
    ctx: CallContext, *, preferences: list[str] | None = None
) -> ApiGetPreferencesResponseDTO:
    return await ctx.ainvoke(GET_USER_PREFERENCE_SPEC, query={"Preferences": preferences})


SAVE_USER_PREFERENCE_SPEC: EndpointSpec[ResponseModel] = EndpointSpec(
    name="SaveUserPreference v2",
    method="POST",
    path="/preference/v2/Preference/save",
    idempotent=False,
    auth_policy=AuthPolicy.SESSION,
    rate_limit_bucket="preference",
    response_model=ResponseModel,
    request_model=ApiSavePreferencesRequestDTO,
    params=(
        Param(
            name="ApiSavePreferencesRequestDTO",
            location="body",
            python_name="api_save_preferences_request_dto",
        ),
    ),
)


def save_user_preference(ctx: CallContext, request: ApiSavePreferencesRequestDTO) -> ResponseModel:
    return ctx.invoke(SAVE_USER_PREFERENCE_SPEC, body=request)


async def asave_user_preference(
    ctx: CallContext, request: ApiSavePreferencesRequestDTO
) -> ResponseModel:
    return await ctx.ainvoke(SAVE_USER_PREFERENCE_SPEC, body=request)


__all__ = [
    "DELETE_USER_PREFERENCE_SPEC",
    "delete_user_preference",
    "adelete_user_preference",
    "GET_USER_PREFERENCE_SPEC",
    "get_user_preference",
    "aget_user_preference",
    "SAVE_USER_PREFERENCE_SPEC",
    "save_user_preference",
    "asave_user_preference",
]
