# GENERATED by stonepy._generator. Do not edit by hand.
"""Generated endpoint bindings for the StoneX CIAPI v2 price_alert target."""

from __future__ import annotations

from stonepy._core.endpoint import AuthPolicy, EndpointSpec, Param
from stonepy._core.models import ResponseModel
from stonepy._core.pipeline import CallContext
from stonepy.models import PriceAlertResponseDTO, SaveAlertRequestDTOv2, SaveAlertResponseDTOv2

DELETE_PA_SPEC: EndpointSpec[ResponseModel] = EndpointSpec(
    name="DeletePA",
    method="POST",
    path="/pricealert/delete/{alertId}",
    idempotent=False,
    auth_policy=AuthPolicy.SESSION,
    rate_limit_bucket="price_alert",
    response_model=ResponseModel,
    params=(
        Param(name="alertId", location="path", python_name="alert_id"),
        Param(name="ClientAccountId", location="body", python_name="client_account_id"),
    ),
)


def delete_pa(ctx: CallContext, alert_id: int, client_account_id: int) -> ResponseModel:
    """Remove the specified price alert from the client account."""
    return ctx.invoke(
        DELETE_PA_SPEC,
        path_params={"alertId": alert_id},
        body={"ClientAccountId": client_account_id},
    )


async def adelete_pa(ctx: CallContext, alert_id: int, client_account_id: int) -> ResponseModel:
    """Remove the specified price alert from the client account."""
    return await ctx.ainvoke(
        DELETE_PA_SPEC,
        path_params={"alertId": alert_id},
        body={"ClientAccountId": client_account_id},
    )


GET_PA_SPEC: EndpointSpec[PriceAlertResponseDTO] = EndpointSpec(
    name="GetPA",
    method="GET",
    path="/pricealert/",
    idempotent=True,
    auth_policy=AuthPolicy.SESSION,
    rate_limit_bucket="price_alert",
    response_model=PriceAlertResponseDTO,
    params=(
        Param(name="alertId", location="body", python_name="alert_id"),
        Param(name="ClientAccountId", location="body", python_name="client_account_id"),
    ),
)


def get_pa(
    ctx: CallContext, client_account_id: int, *, alert_id: int | None = None
) -> PriceAlertResponseDTO:
    """
    Perform a retrieve operation for the specified client price alert, or where no parameter
    is supplied for all price alerts on this client account.
    """
    return ctx.invoke(GET_PA_SPEC, body={"alertId": alert_id, "ClientAccountId": client_account_id})


async def aget_pa(
    ctx: CallContext, client_account_id: int, *, alert_id: int | None = None
) -> PriceAlertResponseDTO:
    """
    Perform a retrieve operation for the specified client price alert, or where no parameter
    is supplied for all price alerts on this client account.
    """
    return await ctx.ainvoke(
        GET_PA_SPEC, body={"alertId": alert_id, "ClientAccountId": client_account_id}
    )


SAVE_PA_SPEC: EndpointSpec[ResponseModel] = EndpointSpec(
    name="SavePA",
    method="POST",
    path="/pricealert/",
    idempotent=False,
    auth_policy=AuthPolicy.SESSION,
    rate_limit_bucket="price_alert",
    response_model=ResponseModel,
    request_model=SaveAlertRequestDTOv2,
    params=(Param(name="request", location="body", python_name="request"),),
)


def save_pa(ctx: CallContext, request: SaveAlertRequestDTOv2) -> ResponseModel:
    """
    Perform a save operation for a client defined price alert. This service call is also used
    to update an alert by saving the new parameters and overwriting the previous settings on
    the same alert.
    """
    return ctx.invoke(SAVE_PA_SPEC, body=request)


async def asave_pa(ctx: CallContext, request: SaveAlertRequestDTOv2) -> ResponseModel:
    """
    Perform a save operation for a client defined price alert. This service call is also used
    to update an alert by saving the new parameters and overwriting the previous settings on
    the same alert.
    """
    return await ctx.ainvoke(SAVE_PA_SPEC, body=request)


SAVE_PRICE_ALERT_SPEC: EndpointSpec[SaveAlertResponseDTOv2] = EndpointSpec(
    name="SavePriceAlert v2",
    method="POST",
    path="/v2/priceAlert/save",
    idempotent=False,
    auth_policy=AuthPolicy.SESSION,
    rate_limit_bucket="price_alert",
    response_model=SaveAlertResponseDTOv2,
    request_model=SaveAlertRequestDTOv2,
    params=(Param(name="request", location="body", python_name="request"),),
)


def save_price_alert(ctx: CallContext, request: SaveAlertRequestDTOv2) -> SaveAlertResponseDTOv2:
    """
    Perform a save operation for a client defined price alert. This service call is also used
    to update an alert by saving the new parameters and overwriting the previous settings on
    the same alert.
    """
    return ctx.invoke(SAVE_PRICE_ALERT_SPEC, body=request)


async def asave_price_alert(
    ctx: CallContext, request: SaveAlertRequestDTOv2
) -> SaveAlertResponseDTOv2:
    """
    Perform a save operation for a client defined price alert. This service call is also used
    to update an alert by saving the new parameters and overwriting the previous settings on
    the same alert.
    """
    return await ctx.ainvoke(SAVE_PRICE_ALERT_SPEC, body=request)


__all__ = [
    "DELETE_PA_SPEC",
    "delete_pa",
    "adelete_pa",
    "GET_PA_SPEC",
    "get_pa",
    "aget_pa",
    "SAVE_PA_SPEC",
    "save_pa",
    "asave_pa",
    "SAVE_PRICE_ALERT_SPEC",
    "save_price_alert",
    "asave_price_alert",
]
