# GENERATED by stonepy._generator. Do not edit by hand.
"""Generated endpoint bindings for the StoneX CIAPI v2 session target."""

from __future__ import annotations

from stonepy._core.endpoint import AuthPolicy, EndpointSpec, Param
from stonepy._core.pipeline import CallContext
from stonepy.models import (
    ApiChangePasswordRequestDTO,
    ApiChangePasswordResponseDTO,
    ApiLogOffResponseDTO,
    ApiLogOnRequestDTO,
    ApiLogOnResponseDTOv2,
    ApiValidateSessionRequestDTOv2,
    ApiValidateSessionResponseDTO,
)

CHANGE_PASSWORD_SPEC: EndpointSpec[ApiChangePasswordResponseDTO] = EndpointSpec(
    name="ChangePassword",
    method="POST",
    path="/session/changePassword",
    idempotent=False,
    auth_policy=AuthPolicy.SESSION,
    rate_limit_bucket="session",
    response_model=ApiChangePasswordResponseDTO,
    request_model=ApiChangePasswordRequestDTO,
    params=(
        Param(
            name="apiChangePasswordRequest",
            location="body",
            python_name="api_change_password_request",
        ),
    ),
)


def change_password(
    ctx: CallContext, request: ApiChangePasswordRequestDTO
) -> ApiChangePasswordResponseDTO:
    """Change a user's password."""
    return ctx.invoke(CHANGE_PASSWORD_SPEC, body=request)


async def achange_password(
    ctx: CallContext, request: ApiChangePasswordRequestDTO
) -> ApiChangePasswordResponseDTO:
    """Change a user's password."""
    return await ctx.ainvoke(CHANGE_PASSWORD_SPEC, body=request)


DELETE_SESSION_SPEC: EndpointSpec[ApiLogOffResponseDTO] = EndpointSpec(
    name="DeleteSession",
    method="POST",
    path="/session/deleteSession",
    idempotent=False,
    auth_policy=AuthPolicy.SESSION,
    rate_limit_bucket="session",
    response_model=ApiLogOffResponseDTO,
    params=(
        Param(name="UserName", location="body", python_name="user_name"),
        Param(name="Session", location="body", python_name="session"),
    ),
)


def delete_session(ctx: CallContext, user_name: str, session: str) -> ApiLogOffResponseDTO:
    """Delete a session. This is how you "log off" from the StoneX API."""
    return ctx.invoke(DELETE_SESSION_SPEC, body={"UserName": user_name, "Session": session})


async def adelete_session(ctx: CallContext, user_name: str, session: str) -> ApiLogOffResponseDTO:
    """Delete a session. This is how you "log off" from the StoneX API."""
    return await ctx.ainvoke(DELETE_SESSION_SPEC, body={"UserName": user_name, "Session": session})


LOG_ON_SPEC: EndpointSpec[ApiLogOnResponseDTOv2] = EndpointSpec(
    name="LogOn v2",
    method="POST",
    path="/session/v2/Session",
    idempotent=False,
    auth_policy=AuthPolicy.NONE,
    rate_limit_bucket="session",
    response_model=ApiLogOnResponseDTOv2,
    request_model=ApiLogOnRequestDTO,
    params=(Param(name="apiLogOnRequest", location="body", python_name="api_log_on_request"),),
)


def log_on(ctx: CallContext, request: ApiLogOnRequestDTO) -> ApiLogOnResponseDTOv2:
    """Create a new session. This is how you "log on" to the StoneX API."""
    return ctx.invoke(LOG_ON_SPEC, body=request)


async def alog_on(ctx: CallContext, request: ApiLogOnRequestDTO) -> ApiLogOnResponseDTOv2:
    """Create a new session. This is how you "log on" to the StoneX API."""
    return await ctx.ainvoke(LOG_ON_SPEC, body=request)


VALIDATE_SESSION_SPEC: EndpointSpec[ApiValidateSessionResponseDTO] = EndpointSpec(
    name="ValidateSession v2",
    method="POST",
    path="/session/v2/Session/validate",
    idempotent=False,
    auth_policy=AuthPolicy.SESSION,
    rate_limit_bucket="session",
    response_model=ApiValidateSessionResponseDTO,
    request_model=ApiValidateSessionRequestDTOv2,
    params=(
        Param(
            name="ValidateSessionRequest", location="body", python_name="validate_session_request"
        ),
    ),
)


def validate_session(
    ctx: CallContext, request: ApiValidateSessionRequestDTOv2
) -> ApiValidateSessionResponseDTO:
    """Validates a session - checks that your session ID and username combination is valid."""
    return ctx.invoke(VALIDATE_SESSION_SPEC, body=request)


async def avalidate_session(
    ctx: CallContext, request: ApiValidateSessionRequestDTOv2
) -> ApiValidateSessionResponseDTO:
    """Validates a session - checks that your session ID and username combination is valid."""
    return await ctx.ainvoke(VALIDATE_SESSION_SPEC, body=request)


__all__ = [
    "CHANGE_PASSWORD_SPEC",
    "change_password",
    "achange_password",
    "DELETE_SESSION_SPEC",
    "delete_session",
    "adelete_session",
    "LOG_ON_SPEC",
    "log_on",
    "alog_on",
    "VALIDATE_SESSION_SPEC",
    "validate_session",
    "avalidate_session",
]
