# GENERATED by stonepy._generator. Do not edit by hand.
"""Generated endpoint bindings for the StoneX CIAPI v2 watchlist target."""

from __future__ import annotations

from stonepy._core.endpoint import AuthPolicy, EndpointSpec, Param
from stonepy._core.pipeline import CallContext
from stonepy.models import (
    DeleteWatchlistResponseDTO,
    ListWatchlistResponseDTO,
    SaveWatchlistRequestDTO,
    SaveWatchlistResponseDTO,
)

DELETE_WATCHLIST_SPEC: EndpointSpec[DeleteWatchlistResponseDTO] = EndpointSpec(
    name="DeleteWatchlist v2",
    method="DELETE",
    path="/watchlist/v2/watchlists",
    idempotent=True,
    auth_policy=AuthPolicy.SESSION,
    rate_limit_bucket="watchlist",
    response_model=DeleteWatchlistResponseDTO,
    params=(
        Param(name="ClientAccountId", location="body", python_name="client_account_id"),
        Param(name="WatchlistId", location="body", python_name="watchlist_id"),
    ),
)


def delete_watchlist(
    ctx: CallContext, client_account_id: int, watchlist_id: int
) -> DeleteWatchlistResponseDTO:
    """Delete watchlist v2."""
    return ctx.invoke(
        DELETE_WATCHLIST_SPEC,
        body={"ClientAccountId": client_account_id, "WatchlistId": watchlist_id},
    )


async def adelete_watchlist(
    ctx: CallContext, client_account_id: int, watchlist_id: int
) -> DeleteWatchlistResponseDTO:
    """Delete watchlist v2."""
    return await ctx.ainvoke(
        DELETE_WATCHLIST_SPEC,
        body={"ClientAccountId": client_account_id, "WatchlistId": watchlist_id},
    )


GET_WATCHLISTS_LIST_SPEC: EndpointSpec[ListWatchlistResponseDTO] = EndpointSpec(
    name="GetWatchlistsList v2",
    method="GET",
    path="/watchlist/v2/watchlists/list?clientAccountId={clientAccountId}&ids={ids}",
    idempotent=True,
    auth_policy=AuthPolicy.SESSION,
    rate_limit_bucket="watchlist",
    response_model=ListWatchlistResponseDTO,
    params=(
        Param(name="ClientAccountId", location="query", python_name="client_account_id"),
        Param(name="Ids", location="query", python_name="ids"),
        Param(name="IncludeItems", location="query", python_name="include_items"),
        Param(
            name="IncludeMarketInformation",
            location="query",
            python_name="include_market_information",
        ),
    ),
)


def get_watchlists_list(
    ctx: CallContext,
    client_account_id: int,
    ids: list[int],
    *,
    include_items: bool | None = None,
    include_market_information: bool | None = None,
) -> ListWatchlistResponseDTO:
    """Returns the client's list of watchlists."""
    return ctx.invoke(
        GET_WATCHLISTS_LIST_SPEC,
        query={
            "ClientAccountId": client_account_id,
            "Ids": ids,
            "IncludeItems": include_items,
            "IncludeMarketInformation": include_market_information,
        },
    )


async def aget_watchlists_list(
    ctx: CallContext,
    client_account_id: int,
    ids: list[int],
    *,
    include_items: bool | None = None,
    include_market_information: bool | None = None,
) -> ListWatchlistResponseDTO:
    """Returns the client's list of watchlists."""
    return await ctx.ainvoke(
        GET_WATCHLISTS_LIST_SPEC,
        query={
            "ClientAccountId": client_account_id,
            "Ids": ids,
            "IncludeItems": include_items,
            "IncludeMarketInformation": include_market_information,
        },
    )


GET_WATCHLISTS_SPEC: EndpointSpec[ListWatchlistResponseDTO] = EndpointSpec(
    name="GetWatchlists v2",
    method="GET",
    path="/watchlists/v2/watchlists?clientAccountId={clientAccountId}",
    idempotent=True,
    auth_policy=AuthPolicy.SESSION,
    rate_limit_bucket="watchlist",
    response_model=ListWatchlistResponseDTO,
    params=(Param(name="ClientAccountId", location="query", python_name="client_account_id"),),
)


def get_watchlists(ctx: CallContext, client_account_id: int) -> ListWatchlistResponseDTO:
    """Returns the client's watchlists."""
    return ctx.invoke(GET_WATCHLISTS_SPEC, query={"ClientAccountId": client_account_id})


async def aget_watchlists(ctx: CallContext, client_account_id: int) -> ListWatchlistResponseDTO:
    """Returns the client's watchlists."""
    return await ctx.ainvoke(GET_WATCHLISTS_SPEC, query={"ClientAccountId": client_account_id})


SAVE_WATCHLIST_SPEC: EndpointSpec[SaveWatchlistResponseDTO] = EndpointSpec(
    name="SaveWatchlist v2",
    method="POST",
    path="/watchlist/v2/watchlists/save",
    idempotent=False,
    auth_policy=AuthPolicy.SESSION,
    rate_limit_bucket="watchlist",
    response_model=SaveWatchlistResponseDTO,
    request_model=SaveWatchlistRequestDTO,
    params=(
        Param(
            name="SaveWatchlistRequestDTO",
            location="body",
            python_name="save_watchlist_request_dto",
        ),
    ),
)


def save_watchlist(ctx: CallContext, request: SaveWatchlistRequestDTO) -> SaveWatchlistResponseDTO:
    """Save watchlist v2."""
    return ctx.invoke(SAVE_WATCHLIST_SPEC, body=request)


async def asave_watchlist(
    ctx: CallContext, request: SaveWatchlistRequestDTO
) -> SaveWatchlistResponseDTO:
    """Save watchlist v2."""
    return await ctx.ainvoke(SAVE_WATCHLIST_SPEC, body=request)


__all__ = [
    "DELETE_WATCHLIST_SPEC",
    "delete_watchlist",
    "adelete_watchlist",
    "GET_WATCHLISTS_LIST_SPEC",
    "get_watchlists_list",
    "aget_watchlists_list",
    "GET_WATCHLISTS_SPEC",
    "get_watchlists",
    "aget_watchlists",
    "SAVE_WATCHLIST_SPEC",
    "save_watchlist",
    "asave_watchlist",
]
