# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from stonepy._core.resource import BaseResource

from ._sync.cancel_order import _CancelOrderMixin as _SyncCancelOrderMixin
from ._sync.get_active_stop_limit_order import (
    _GetActiveStopLimitOrderMixin as _SyncGetActiveStopLimitOrderMixin,
)
from ._sync.get_open_position import _GetOpenPositionMixin as _SyncGetOpenPositionMixin
from ._sync.get_order import _GetOrderMixin as _SyncGetOrderMixin
from ._sync.list_active_orders import _ListActiveOrdersMixin as _SyncListActiveOrdersMixin
from ._sync.list_active_stop_limit_orders import (
    _ListActiveStopLimitOrdersMixin as _SyncListActiveStopLimitOrdersMixin,
)
from ._sync.list_open_positions import _ListOpenPositionsMixin as _SyncListOpenPositionsMixin
from ._sync.list_stop_limit_order_history import (
    _ListStopLimitOrderHistoryMixin as _SyncListStopLimitOrderHistoryMixin,
)
from ._sync.list_trade_history import _ListTradeHistoryMixin as _SyncListTradeHistoryMixin
from ._sync.order import _OrderMixin as _SyncOrderMixin
from ._sync.place_order import _PlaceOrderMixin as _SyncPlaceOrderMixin
from ._sync.simulate_trade import _SimulateTradeMixin as _SyncSimulateTradeMixin
from .cancel_order import _CancelOrderMixin as _AsyncCancelOrderMixin
from .get_active_stop_limit_order import (
    _GetActiveStopLimitOrderMixin as _AsyncGetActiveStopLimitOrderMixin,
)
from .get_open_position import _GetOpenPositionMixin as _AsyncGetOpenPositionMixin
from .get_order import _GetOrderMixin as _AsyncGetOrderMixin
from .list_active_orders import _ListActiveOrdersMixin as _AsyncListActiveOrdersMixin
from .list_active_stop_limit_orders import (
    _ListActiveStopLimitOrdersMixin as _AsyncListActiveStopLimitOrdersMixin,
)
from .list_open_positions import _ListOpenPositionsMixin as _AsyncListOpenPositionsMixin
from .list_stop_limit_order_history import (
    _ListStopLimitOrderHistoryMixin as _AsyncListStopLimitOrderHistoryMixin,
)
from .list_trade_history import _ListTradeHistoryMixin as _AsyncListTradeHistoryMixin
from .order import _OrderMixin as _AsyncOrderMixin
from .place_order import _PlaceOrderMixin as _AsyncPlaceOrderMixin
from .simulate_trade import _SimulateTradeMixin as _AsyncSimulateTradeMixin


class OrderResource(
    _SyncCancelOrderMixin,
    _SyncGetActiveStopLimitOrderMixin,
    _SyncGetOpenPositionMixin,
    _SyncGetOrderMixin,
    _SyncListActiveOrdersMixin,
    _SyncListActiveStopLimitOrdersMixin,
    _SyncListOpenPositionsMixin,
    _SyncListStopLimitOrderHistoryMixin,
    _SyncListTradeHistoryMixin,
    _SyncOrderMixin,
    _SyncPlaceOrderMixin,
    _SyncSimulateTradeMixin,
    BaseResource,
):
    pass


class AsyncOrderResource(
    _AsyncCancelOrderMixin,
    _AsyncGetActiveStopLimitOrderMixin,
    _AsyncGetOpenPositionMixin,
    _AsyncGetOrderMixin,
    _AsyncListActiveOrdersMixin,
    _AsyncListActiveStopLimitOrdersMixin,
    _AsyncListOpenPositionsMixin,
    _AsyncListStopLimitOrderHistoryMixin,
    _AsyncListTradeHistoryMixin,
    _AsyncOrderMixin,
    _AsyncPlaceOrderMixin,
    _AsyncSimulateTradeMixin,
    BaseResource,
):
    pass


__all__ = [
    "AsyncOrderResource",
    "OrderResource",
]
