# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from stonepy._core.resource import BaseResource

from ._sync.list_spread_markets import _ListSpreadMarketsMixin as _SyncListSpreadMarketsMixin
from .list_spread_markets import _ListSpreadMarketsMixin as _AsyncListSpreadMarketsMixin


class SpreadResource(_SyncListSpreadMarketsMixin, BaseResource):
    pass


class AsyncSpreadResource(_AsyncListSpreadMarketsMixin, BaseResource):
    pass


__all__ = [
    "AsyncSpreadResource",
    "SpreadResource",
]
