# GENERATED by stonepy._generator. Do not edit by hand.
"""Resource method: GetSignalPreferences."""

from __future__ import annotations

from stonepy._core.resource import BaseResource
from stonepy._endpoints import pm as _ep
from stonepy.models import PreferenceDTO


class _GetSignalPreferencesMixin(BaseResource):
    def get_signal_preferences(
        self,
    ) -> PreferenceDTO:
        """
        All service calls and DTOs related to Predicted Markets are for internal StoneX
        use only. Retrieves the signal preferences for the authenticated user.
        """
        return _ep.get_signal_preferences(self._ctx)
