# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from stonepy._core.resource import BaseResource

from ._sync.delete_watchlist import _DeleteWatchlistMixin as _SyncDeleteWatchlistMixin
from ._sync.get_watchlists import _GetWatchlistsMixin as _SyncGetWatchlistsMixin
from ._sync.get_watchlists_list import _GetWatchlistsListMixin as _SyncGetWatchlistsListMixin
from ._sync.save_watchlist import _SaveWatchlistMixin as _SyncSaveWatchlistMixin
from .delete_watchlist import _DeleteWatchlistMixin as _AsyncDeleteWatchlistMixin
from .get_watchlists import _GetWatchlistsMixin as _AsyncGetWatchlistsMixin
from .get_watchlists_list import _GetWatchlistsListMixin as _AsyncGetWatchlistsListMixin
from .save_watchlist import _SaveWatchlistMixin as _AsyncSaveWatchlistMixin


class WatchlistResource(
    _SyncDeleteWatchlistMixin,
    _SyncGetWatchlistsMixin,
    _SyncGetWatchlistsListMixin,
    _SyncSaveWatchlistMixin,
    BaseResource,
):
    pass


class AsyncWatchlistResource(
    _AsyncDeleteWatchlistMixin,
    _AsyncGetWatchlistsMixin,
    _AsyncGetWatchlistsListMixin,
    _AsyncSaveWatchlistMixin,
    BaseResource,
):
    pass


__all__ = [
    "AsyncWatchlistResource",
    "WatchlistResource",
]
