# GENERATED by stonepy._generator. Do not edit by hand.
"""Resource method: GetWallSubItems."""

from __future__ import annotations

from stonepy._core.resource import BaseResource
from stonepy._endpoints import user_account as _ep
from stonepy.models import ApiGetWallSubItemsResponseDTO


class _GetWallSubItemsMixin(BaseResource):
    def get_wall_sub_items(
        self,
    ) -> ApiGetWallSubItemsResponseDTO:
        """
        Fetches the sub-wall items for the specified wall items. (Service call used by the
        CI Connect social trading platform.) Note: this requires that the respective CI
        Connect user record in the CI Connect database exists.
        """
        return _ep.get_wall_sub_items(self._ctx)
