# GENERATED by stonepy._generator. Do not edit by hand.
"""Resource method: GetActiveStopLimitOrder."""

from __future__ import annotations

from stonepy._core.resource import BaseResource
from stonepy._endpoints import order as _ep
from stonepy.models import GetActiveStopLimitOrderResponseDTOv2


class _GetActiveStopLimitOrderMixin(BaseResource):
    def get_active_stop_limit_order(self, order_id: int) -> GetActiveStopLimitOrderResponseDTOv2:
        """
        Queries for an active stop limit order with a specified order ID. It returns a
        null value if the order doesn't exist, or is not an active stop limit order. This
        URI is intended to support a grid in a UI. One usage pattern is to subscribe to
        streaming orders, call the HTTP service ListActiveStopLimitOrders for the initial
        data to display in the grid, and call this URI when you receive updates on the
        order stream to get the updated data in this format.
        """
        return _ep.get_active_stop_limit_order(self._ctx, order_id)
