# GENERATED by stonepy._generator. Do not edit by hand.
"""Resource method: UpdateOrder."""

from __future__ import annotations

from stonepy._core.resource import BaseResource
from stonepy._endpoints import order as _ep
from stonepy.models import ApiTradeOrderResponseDTO, UpdateStopLimitOrderRequestDTO


class _UpdateOrderMixin(BaseResource):
    def update_order(self, request: UpdateStopLimitOrderRequestDTO) -> ApiTradeOrderResponseDTO:
        """
        Update the details of a resting entry order. For example: change the trigger price
        level or quantity, attach conditional if/done stop/limit orders, or attach an OCO
        relationship.
        """
        return _ep.update_order(self._ctx, request)
