# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from enum import IntEnum

import pytest

from stonepy.models import (
    AlertCriterion,
    AlertDirection,
    AlertExpiry,
    AlertNotification,
    ErrorCode,
    MarketState,
)

DATATYPE_ENUM_CASES = [
    pytest.param(AlertCriterion, {"AtOrAbove": 1, "AtOrBelow": 2}, id="AlertCriterion"),
    pytest.param(AlertDirection, {"Buy": 1, "Sell": 2}, id="AlertDirection"),
    pytest.param(AlertExpiry, {"GTC": 1, "GTD": 2}, id="AlertExpiry"),
    pytest.param(
        AlertNotification,
        {
            "EMailAndSms": 3,
            "Email": 1,
            "EmailAndPushNotification": 5,
            "EmailAndSmsAndPushNotification": 7,
            "PushNotification": 4,
            "Sms": 2,
            "SmsAndPushNotification": 6,
        },
        id="AlertNotification",
    ),
    pytest.param(
        ErrorCode,
        {
            "Forbidden": 403,
            "InternalServerError": 500,
            "InvalidCredentials": 4010,
            "InvalidJsonRequest": 4003,
            "InvalidJsonRequestCaseFormat": 4004,
            "InvalidParameterType": 4000,
            "InvalidParameterValue": 4002,
            "InvalidSession": 4011,
            "NoDataAvailable": 5001,
            "NoError": 0,
            "ParameterMissing": 4001,
            "Throttling": 5002,
        },
        id="ErrorCode",
    ),
    pytest.param(
        MarketState,
        {
            "Close": 4,
            "CloseOnly": 6,
            "Indicative": 2,
            "LongOnly": 7,
            "PhoneOnly": 3,
            "ShortOnly": 8,
            "Suspended": 5,
            "Tradable": 0,
            "TradableAndFast": 1,
        },
        id="MarketState",
    ),
]


@pytest.mark.parametrize("enum_cls, members", DATATYPE_ENUM_CASES)
def test_generated_datatype_enum_matches_catalog(
    enum_cls: type[IntEnum], members: dict[str, int]
) -> None:
    assert {name: member.value for name, member in enum_cls.__members__.items()} == members
