# GENERATED by stonepy._generator. Do not edit by hand.
"""Synchronous and asynchronous margin resource group classes."""

from __future__ import annotations

from stonepy._core.resource import BaseResource

from ._sync.get_client_account_margin import (
    _GetClientAccountMarginMixin as _SyncGetClientAccountMarginMixin,
)
from .get_client_account_margin import (
    _GetClientAccountMarginMixin as _AsyncGetClientAccountMarginMixin,
)


class MarginResource(_SyncGetClientAccountMarginMixin, BaseResource):
    """
    Synchronous `margin` resource group; access it via `StoneXClient.margin`. Each method maps
    to one StoneX CIAPI v2 endpoint.
    """


class AsyncMarginResource(_AsyncGetClientAccountMarginMixin, BaseResource):
    """
    Asynchronous `margin` resource group; access it via `AsyncStoneXClient.margin`. Each
    method is the awaitable twin of the synchronous resource's method.
    """


__all__ = [
    "AsyncMarginResource",
    "MarginResource",
]
