# GENERATED by stonepy._generator. Do not edit by hand.
"""Synchronous and asynchronous message resource group classes."""

from __future__ import annotations

from stonepy._core.resource import BaseResource

from ._sync.client_communication_message_update import (
    _ClientCommunicationMessageUpdateMixin as _SyncClientCommunicationMessageUpdateMixin,
)
from ._sync.get_client_application_message_translation import (
    _GetClientApplicationMessageTranslationMixin as _SyncGetClientApplicationMessageTranslationMixin,  # noqa: E501
)
from ._sync.get_client_application_message_translation_with_interesting_items import (
    _GetClientApplicationMessageTranslationWithInterestingItemsMixin as _SyncGetClientApplicationMessageTranslationWithInterestingItemsMixin,  # noqa: E501
)
from ._sync.get_client_communication_messages import (
    _GetClientCommunicationMessagesMixin as _SyncGetClientCommunicationMessagesMixin,
)
from ._sync.get_message_popup import _GetMessagePopupMixin as _SyncGetMessagePopupMixin
from ._sync.get_secure_messages import _GetSecureMessagesMixin as _SyncGetSecureMessagesMixin
from ._sync.get_system_lookup import _GetSystemLookupMixin as _SyncGetSystemLookupMixin
from ._sync.save_client_communication_message_response import (
    _SaveClientCommunicationMessageResponseMixin as _SyncSaveClientCommunicationMessageResponseMixin,  # noqa: E501
)
from .client_communication_message_update import (
    _ClientCommunicationMessageUpdateMixin as _AsyncClientCommunicationMessageUpdateMixin,
)
from .get_client_application_message_translation import (
    _GetClientApplicationMessageTranslationMixin as _AsyncGetClientApplicationMessageTranslationMixin,  # noqa: E501
)
from .get_client_application_message_translation_with_interesting_items import (
    _GetClientApplicationMessageTranslationWithInterestingItemsMixin as _AsyncGetClientApplicationMessageTranslationWithInterestingItemsMixin,  # noqa: E501
)
from .get_client_communication_messages import (
    _GetClientCommunicationMessagesMixin as _AsyncGetClientCommunicationMessagesMixin,
)
from .get_message_popup import _GetMessagePopupMixin as _AsyncGetMessagePopupMixin
from .get_secure_messages import _GetSecureMessagesMixin as _AsyncGetSecureMessagesMixin
from .get_system_lookup import _GetSystemLookupMixin as _AsyncGetSystemLookupMixin
from .save_client_communication_message_response import (
    _SaveClientCommunicationMessageResponseMixin as _AsyncSaveClientCommunicationMessageResponseMixin,  # noqa: E501
)


class MessageResource(
    _SyncClientCommunicationMessageUpdateMixin,
    _SyncGetClientApplicationMessageTranslationMixin,
    _SyncGetClientApplicationMessageTranslationWithInterestingItemsMixin,
    _SyncGetClientCommunicationMessagesMixin,
    _SyncGetMessagePopupMixin,
    _SyncGetSecureMessagesMixin,
    _SyncGetSystemLookupMixin,
    _SyncSaveClientCommunicationMessageResponseMixin,
    BaseResource,
):
    """
    Synchronous `message` resource group; access it via `StoneXClient.message`. Each method
    maps to one StoneX CIAPI v2 endpoint.
    """


class AsyncMessageResource(
    _AsyncClientCommunicationMessageUpdateMixin,
    _AsyncGetClientApplicationMessageTranslationMixin,
    _AsyncGetClientApplicationMessageTranslationWithInterestingItemsMixin,
    _AsyncGetClientCommunicationMessagesMixin,
    _AsyncGetMessagePopupMixin,
    _AsyncGetSecureMessagesMixin,
    _AsyncGetSystemLookupMixin,
    _AsyncSaveClientCommunicationMessageResponseMixin,
    BaseResource,
):
    """
    Asynchronous `message` resource group; access it via `AsyncStoneXClient.message`. Each
    method is the awaitable twin of the synchronous resource's method.
    """


__all__ = [
    "AsyncMessageResource",
    "MessageResource",
]
