# GENERATED by stonepy._generator. Do not edit by hand.
"""Resource method: DeleteSession."""

from __future__ import annotations

from stonepy._core.resource import BaseResource
from stonepy._endpoints import session as _ep
from stonepy.models import ApiLogOffResponseDTO


class _DeleteSessionMixin(BaseResource):
    def delete_session(self, user_name: str, session: str) -> ApiLogOffResponseDTO:
        """Delete a session. This is how you "log off" from the StoneX API."""
        return _ep.delete_session(self._ctx, user_name, session)
