from __future__ import annotations

import importlib
import sys
from pathlib import Path

from stonepy._generator.catalog import Catalog, EndpointRecord, TypeRecord, load_catalog
from stonepy._generator.emit_models import emit_all
from stonepy._generator.emit_models import render_enum as emit_render_enum
from stonepy._generator.emit_models import render_model as emit_render_model
from stonepy._generator.render import format_python, render_enum, render_model

FIX = Path(__file__).parent / "fixtures"


def _datatype(
    name: str,
    properties: list[dict[str, object]],
) -> TypeRecord:
    return TypeRecord(
        name=name,
        catalog_name=name,
        version="v1",
        description=None,
        properties=properties,
        source_url=None,
        source_file=None,
        last_updated=None,
        raw={"name": name, "properties": properties},
    )


def _endpoint(request_type: str | None = None, response_type: str | None = None) -> EndpointRecord:
    return EndpointRecord(
        name="FixtureEndpoint",
        logical_name="FixtureEndpoint",
        version="v1",
        description=None,
        method="POST",
        target=None,
        uri_template="/fixture",
        path="/fixture",
        content_type="application/json",
        envelope="JSON",
        parameters=[],
        request_type=request_type,
        response_type=response_type,
        source_url=None,
        source_file=None,
        last_updated=None,
        raw={"name": "FixtureEndpoint"},
    )


def test_render_model_has_banner_decimal_import_and_field_alias() -> None:
    cat = load_catalog(FIX)
    alert = next(rec for rec in cat.datatypes if rec.name == "AlertDTO")

    rendered = render_model(alert, {rec.name for rec in cat.datatypes})

    assert "GENERATED by stonepy._generator" in rendered
    assert "from __future__ import annotations" in rendered
    assert "from decimal import Decimal" in rendered
    assert "class AlertDTO(ResponseModel):" in rendered
    assert 'fill_rate: Decimal | None = Field(default=None, alias="FillRate")' in rendered


def test_format_python_applies_ruff_import_sorting() -> None:
    rendered = format_python(
        "\n".join(
            [
                "from __future__ import annotations",
                "",
                "import pytest",
                "from stonepy._core.models import StoneXModel",
                "",
            ]
        )
    )

    assert "import pytest\n\nfrom stonepy._core.models import StoneXModel" in rendered


def test_emit_models_reexports_plan_render_functions() -> None:
    assert emit_render_enum is render_enum
    assert emit_render_model is render_model


def test_render_enum_creates_alert_direction_members() -> None:
    cat = load_catalog(FIX)
    alert_direction = next(rec for rec in cat.datatypes if rec.name == "AlertDirection")

    rendered = render_enum(alert_direction)

    assert "class AlertDirection(IntEnum):" in rendered
    assert "Buy = 1" in rendered
    assert "Sell = 2" in rendered


def test_render_model_is_deterministic() -> None:
    cat = load_catalog(FIX)
    alert = next(rec for rec in cat.datatypes if rec.name == "AlertDTO")
    known_names = {rec.name for rec in cat.datatypes}

    assert render_model(alert, known_names) == render_model(alert, known_names)


def test_render_model_uses_exact_alias_and_snake_case_field_names() -> None:
    cat = load_catalog(FIX)
    alert = next(rec for rec in cat.datatypes if rec.name == "AlertDTO")

    rendered = render_model(alert, {rec.name for rec in cat.datatypes})

    assert 'alert_id: int | None = Field(default=None, alias="AlertId")' in rendered
    assert (
        'expiry_date: StoneXDateTime | None = Field(default=None, alias="ExpiryDate")' in rendered
    )


def test_render_model_imports_and_annotates_stonex_datetime_and_decimal() -> None:
    cat = load_catalog(FIX)
    alert = next(rec for rec in cat.datatypes if rec.name == "AlertDTO")

    rendered = render_model(alert, {rec.name for rec in cat.datatypes})

    assert "from decimal import Decimal" in rendered
    assert "StoneXDateTime" in rendered
    assert 'fill_rate: Decimal | None = Field(default=None, alias="FillRate")' in rendered
    assert (
        'expiry_date: StoneXDateTime | None = Field(default=None, alias="ExpiryDate")' in rendered
    )


def test_render_model_named_empty_type_is_optional_unresolved() -> None:
    cat = load_catalog(FIX)
    alert = next(rec for rec in cat.datatypes if rec.name == "AlertDTO")

    rendered = render_model(alert, {rec.name for rec in cat.datatypes})

    assert "Unresolved = Any" in rendered
    assert 'comment: Unresolved | None = Field(default=None, alias="Comment")' in rendered
    assert 'Field(alias="")' not in rendered


def test_emit_all_writes_models_enums_init_and_uses_endpoint_request_context(
    tmp_path: Path,
) -> None:
    request = _datatype(
        "SubmitAlertDTO",
        [{"name": "AlertId", "type": "Integer", "format": None, "ref": None}],
    )
    response = _datatype(
        "AlertDTO",
        [{"name": "AlertId", "type": "Integer", "format": None, "ref": None}],
    )
    direction = _datatype(
        "AlertDirection",
        [
            {"name": "Buy", "type": "1", "format": None, "ref": None},
            {"name": "Sell", "type": "2", "format": None, "ref": None},
        ],
    )
    catalog = Catalog(
        endpoints=[_endpoint(request_type="SubmitAlertDTO", response_type="AlertDTO")],
        datatypes=[request, response, direction],
        lookups={},
        unresolved=set(),
    )

    emit_all(catalog, tmp_path)
    first_init = (tmp_path / "models" / "__init__.py").read_text(encoding="utf-8")
    emit_all(catalog, tmp_path)

    assert (tmp_path / "models" / "AlertDTO.py").exists()
    assert (tmp_path / "models" / "SubmitAlertDTO.py").exists()
    assert (tmp_path / "models" / "enums.py").exists()
    assert (tmp_path / "models" / "__init__.py").read_text(encoding="utf-8") == first_init
    assert "class SubmitAlertDTO(RequestModel):" in (
        tmp_path / "models" / "SubmitAlertDTO.py"
    ).read_text(encoding="utf-8")
    assert "class AlertDTO(ResponseModel):" in (tmp_path / "models" / "AlertDTO.py").read_text(
        encoding="utf-8"
    )
    assert "class AlertDirection(IntEnum):" in (tmp_path / "models" / "enums.py").read_text(
        encoding="utf-8"
    )
    assert "from .AlertDTO import AlertDTO" in first_init
    assert "from .SubmitAlertDTO import SubmitAlertDTO" in first_init
    assert "from .enums import AlertDirection" in first_init


def test_emit_all_renders_lookup_code_tables_as_enums(tmp_path: Path) -> None:
    catalog = Catalog(
        endpoints=[],
        datatypes=[],
        lookups={
            "InstructionStatus": {
                "columns": ["InstructionStatus Code", "Description"],
                "rows": [
                    {"InstructionStatus Code": "1", "Description": "Accepted"},
                    {"InstructionStatus Code": "2", "Description": "Red Card"},
                ],
            }
        },
        unresolved=set(),
    )

    emit_all(catalog, tmp_path)

    enums = (tmp_path / "models" / "enums.py").read_text(encoding="utf-8")
    init_text = (tmp_path / "models" / "__init__.py").read_text(encoding="utf-8")
    assert "class InstructionStatus(IntEnum):" in enums
    assert "Accepted = 1" in enums
    assert "RedCard = 2" in enums
    assert "from .enums import InstructionStatus" in init_text


def test_emit_all_renders_id_column_lookup_tables_as_enums(tmp_path: Path) -> None:
    # Lookup tables whose code column is named "<Thing>Id"/"<Thing> ID" (rather than
    # "<Thing> Code") must still become enums; the column-name heuristic looks for an id
    # column when no "code" column is present.
    catalog = Catalog(
        endpoints=[],
        datatypes=[],
        lookups={
            "OrderActionTypeId": {
                "columns": ["OrderActionTypeId", "Description"],
                "rows": [
                    {"OrderActionTypeId": "1", "Description": "Opening Order"},
                    {"OrderActionTypeId": "2", "Description": "Full Close"},
                ],
            },
            "CurrencyID": {
                "columns": ["Currency ID", "ISO Currency", "Description"],
                "rows": [
                    {"Currency ID": "1", "ISO Currency": "AUD", "Description": "Australian Dollar"},
                    {"Currency ID": "2", "ISO Currency": "CAD", "Description": "Canadian Dollar"},
                ],
            },
        },
        unresolved=set(),
    )

    emit_all(catalog, tmp_path)

    enums = (tmp_path / "models" / "enums.py").read_text(encoding="utf-8")
    init_text = (tmp_path / "models" / "__init__.py").read_text(encoding="utf-8")
    assert "class OrderActionTypeId(IntEnum):" in enums
    assert "OpeningOrder = 1" in enums
    assert "FullClose = 2" in enums
    assert "class CurrencyID(IntEnum):" in enums
    assert "AustralianDollar = 1" in enums
    assert "from .enums import" in init_text
    assert "CurrencyID" in init_text
    assert "OrderActionTypeId" in init_text


def test_param_model_references_are_request_models(tmp_path: Path) -> None:
    request = _datatype(
        "ListActiveOrdersRequestDTO",
        [{"name": "TradingAccountId", "type": "Integer", "format": None, "ref": None}],
    )
    response = _datatype(
        "ListActiveOrdersResponseDTO",
        [{"name": "OrderId", "type": "Integer", "format": None, "ref": None}],
    )
    catalog = Catalog(
        endpoints=[
            EndpointRecord(
                name="ListActiveOrders",
                logical_name="ListActiveOrders",
                version="v1",
                description=None,
                method="POST",
                target="order",
                uri_template="/order/activeorders",
                path="/order/activeorders",
                content_type="application/json",
                envelope="URL",
                parameters=[
                    {
                        "name": "requestDTO",
                        "type": "ListActiveOrdersRequestDTO",
                        "format": None,
                        "ref": "ListActiveOrdersRequestDTO",
                        "in": "query",
                    }
                ],
                request_type=None,
                response_type="ListActiveOrdersResponseDTO",
                source_url=None,
                source_file=None,
                last_updated=None,
                raw={"name": "ListActiveOrders"},
            )
        ],
        datatypes=[request, response],
        lookups={},
        unresolved=set(),
    )

    emit_all(catalog, tmp_path)

    assert "class ListActiveOrdersRequestDTO(RequestModel):" in (
        tmp_path / "models" / "ListActiveOrdersRequestDTO.py"
    ).read_text(encoding="utf-8")


def test_emit_all_removes_stale_model_files(tmp_path: Path) -> None:
    old = _datatype(
        "OldDTO",
        [{"name": "Value", "type": "String", "format": None, "ref": None}],
    )
    new = _datatype(
        "NewDTO",
        [{"name": "Value", "type": "String", "format": None, "ref": None}],
    )

    emit_all(Catalog(endpoints=[], datatypes=[old], lookups={}, unresolved=set()), tmp_path)
    assert (tmp_path / "models" / "OldDTO.py").exists()

    emit_all(Catalog(endpoints=[], datatypes=[new], lookups={}, unresolved=set()), tmp_path)

    assert not (tmp_path / "models" / "OldDTO.py").exists()
    assert (tmp_path / "models" / "NewDTO.py").exists()


def test_direct_render_model_uses_enums_module_for_known_enum_refs(tmp_path: Path) -> None:
    cat = load_catalog(FIX)
    alert = next(rec for rec in cat.datatypes if rec.name == "AlertDTO")
    alert_direction = next(rec for rec in cat.datatypes if rec.name == "AlertDirection")

    package = tmp_path / "models"
    package.mkdir()
    (package / "__init__.py").write_text("", encoding="utf-8")
    (package / "AlertDTO.py").write_text(
        render_model(alert, {rec.name for rec in cat.datatypes}),
        encoding="utf-8",
    )
    (package / "enums.py").write_text(render_enum(alert_direction), encoding="utf-8")

    for module_name in [
        name for name in sys.modules if name == "models" or name.startswith("models.")
    ]:
        del sys.modules[module_name]
    sys.path.insert(0, str(tmp_path))
    try:
        module = importlib.import_module("models.AlertDTO")
        enums = importlib.import_module("models.enums")
    finally:
        sys.path.remove(str(tmp_path))

    import typing as _t

    assert enums.AlertDirection in _t.get_args(module.AlertDTO.model_fields["direction"].annotation)


def test_emit_all_generated_package_imports_with_circular_model_refs(
    tmp_path: Path,
) -> None:
    first = _datatype(
        "FirstDTO",
        [{"name": "Second", "type": "SecondDTO", "format": None, "ref": "SecondDTO"}],
    )
    second = _datatype(
        "SecondDTO",
        [{"name": "First", "type": "FirstDTO", "format": None, "ref": "FirstDTO"}],
    )
    catalog = Catalog(
        endpoints=[_endpoint(response_type="FirstDTO")],
        datatypes=[first, second],
        lookups={},
        unresolved=set(),
    )

    emit_all(catalog, tmp_path)

    first_text = (tmp_path / "models" / "FirstDTO.py").read_text(encoding="utf-8")
    assert "from typing import TYPE_CHECKING" in first_text
    assert "if TYPE_CHECKING:" in first_text
    assert "    from .SecondDTO import SecondDTO" in first_text
    assert first_text.count("from .SecondDTO import SecondDTO") == 1

    for module_name in [
        name for name in sys.modules if name == "models" or name.startswith("models.")
    ]:
        del sys.modules[module_name]
    sys.path.insert(0, str(tmp_path))
    try:
        imported = importlib.import_module("models")
    finally:
        sys.path.remove(str(tmp_path))

    assert imported.FirstDTO.__name__ == "FirstDTO"
    assert imported.SecondDTO.__name__ == "SecondDTO"
