from __future__ import annotations

import importlib.util
import sys
from pathlib import Path
from types import ModuleType

from stonepy._generator.__main__ import main
from stonepy._generator.catalog import Catalog, EndpointRecord, TypeRecord, load_catalog
from stonepy._generator.emit_contract import emit_contract_tests
from stonepy._generator.emit_endpoints import emit_all as emit_endpoints
from stonepy._generator.emit_models import emit_all as emit_models

FIX = Path(__file__).parent / "fixtures"


def test_emit_contract_tests_writes_importable_contract_modules(tmp_path: Path) -> None:
    catalog = load_catalog(FIX)
    project_root = tmp_path
    package_root = project_root / "stonepy"
    package_root.mkdir()
    (package_root / "__init__.py").write_text(
        "from pkgutil import extend_path\n__path__ = extend_path(__path__, __name__)\n",
        encoding="utf-8",
    )

    emit_models(catalog, package_root)
    emit_endpoints(catalog, package_root)

    stale = project_root / "tests" / "contract" / "stale.py"
    stale.parent.mkdir(parents=True)
    stale.write_text("SHOULD_BE_REMOVED = True\n", encoding="utf-8")

    emit_contract_tests(catalog, project_root)

    roundtrip = project_root / "tests" / "contract" / "test_models_roundtrip.py"
    endpoint_specs = project_root / "tests" / "contract" / "test_endpoint_specs.py"
    lookup_enums = project_root / "tests" / "contract" / "test_lookup_enums.py"
    assert roundtrip.exists()
    assert endpoint_specs.exists()
    assert lookup_enums.exists()
    assert not stale.exists()
    roundtrip_text = roundtrip.read_text(encoding="utf-8")
    endpoint_specs_text = endpoint_specs.read_text(encoding="utf-8")
    lookup_enums_text = lookup_enums.read_text(encoding="utf-8")
    assert "GENERATED by stonepy._generator" in roundtrip_text
    assert "GENERATED by stonepy._generator" in endpoint_specs_text
    assert "GENERATED by stonepy._generator" in lookup_enums_text
    assert "from stonepy._core.models import StoneXModel" in roundtrip_text
    assert "model_cls: type[StoneXModel]" in roundtrip_text
    assert "from stonepy._core.endpoint import EndpointSpec" in endpoint_specs_text
    assert "spec: EndpointSpec[ResponseModel]" in endpoint_specs_text
    assert "enum_cls: type[IntEnum]" in lookup_enums_text

    stonepy_modules = _snapshot_stonepy_modules()
    _clear_stonepy_modules()
    sys.path.insert(0, str(project_root))
    try:
        _import_generated_module(roundtrip, "generated_test_models_roundtrip")
        _import_generated_module(endpoint_specs, "generated_test_endpoint_specs")
        _import_generated_module(lookup_enums, "generated_test_lookup_enums")
    finally:
        sys.path.remove(str(project_root))
        _restore_stonepy_modules(stonepy_modules)


def test_cli_all_writes_package_outputs_and_contract_tests_from_parent_catalog_root(
    tmp_path: Path,
) -> None:
    docs_root = tmp_path / "Docs"
    catalog_root = docs_root / "catalog"
    catalog_root.mkdir(parents=True)
    for filename in ("endpoints.json", "data-types.json", "lookup-codes.json"):
        (catalog_root / filename).write_text((FIX / filename).read_text(encoding="utf-8"))

    project_root = tmp_path / "project"
    package_root = project_root / "src" / "stonepy"
    package_root.mkdir(parents=True)
    (package_root / "__init__.py").write_text("", encoding="utf-8")

    assert (
        main(
            [
                "all",
                "--catalog-root",
                str(docs_root),
                "--package-dir",
                str(package_root),
                "--project-root",
                str(project_root),
                "--allow-unresolved",
                "--allow-unfrozen-catalog",
            ]
        )
        == 0
    )

    assert (package_root / "models" / "AlertDTO.py").exists()
    assert (package_root / "_endpoints" / "order.py").exists()
    assert (project_root / "tests" / "contract" / "test_models_roundtrip.py").exists()
    assert (project_root / "tests" / "contract" / "test_endpoint_specs.py").exists()
    assert (project_root / "tests" / "contract" / "test_lookup_enums.py").exists()


def test_endpoint_contract_uses_module_qualified_specs_to_avoid_shadowing(
    tmp_path: Path,
) -> None:
    catalog = Catalog(
        endpoints=[
            _endpoint("Get", target="market", path="/market/get"),
            _endpoint("Get", target="preference", path="/preference/get"),
        ],
        datatypes=[],
        lookups={},
        unresolved=set(),
    )

    emit_contract_tests(catalog, tmp_path)

    rendered = (tmp_path / "tests" / "contract" / "test_endpoint_specs.py").read_text(
        encoding="utf-8"
    )
    assert '_ep_market = import_module("stonepy._endpoints.market")' in rendered
    assert '_ep_preference = import_module("stonepy._endpoints.preference")' in rendered
    assert "_ep_market.GET_SPEC" in rendered
    assert '"/market/get"' in rendered
    assert '"market"' in rendered
    assert "_ep_preference.GET_SPEC" in rendered
    assert '"/preference/get"' in rendered
    assert '"preference"' in rendered
    assert '"rate_limit_bucket, status_domain, request_model, params"' in rendered


def test_endpoint_contract_rejects_empty_fallback_for_declared_response(
    tmp_path: Path,
) -> None:
    catalog = Catalog(
        endpoints=[
            _endpoint("Known", target="news", path="/news/known", response_type="KnownDTO"),
            _endpoint("NoBody", target="news", path="/news/no-body", response_type=None),
        ],
        datatypes=[],
        lookups={},
        unresolved={"KnownDTO"},
    )

    emit_contract_tests(catalog, tmp_path)

    rendered = (tmp_path / "tests" / "contract" / "test_endpoint_specs.py").read_text(
        encoding="utf-8"
    )
    assert "from stonepy._core.models import ResponseModel" in rendered
    assert "has_declared_response" in rendered
    assert "assert spec.response_model is not ResponseModel" in rendered
    assert "_ep_news.KNOWN_SPEC" in rendered
    assert '"/news/known"' in rendered
    assert 'id="Known"' in rendered
    assert "_ep_news.NO_BODY_SPEC" in rendered
    assert '"/news/no-body"' in rendered
    assert 'id="NoBody"' in rendered


def test_endpoint_contract_records_full_spec_metadata(tmp_path: Path) -> None:
    catalog = Catalog(
        endpoints=[
            EndpointRecord(
                name="Trade",
                logical_name="Trade",
                version="v1",
                description=None,
                method="POST",
                target="order",
                uri_template="/order/new",
                path="/order/new",
                content_type="application/json",
                envelope="JSON",
                parameters=[
                    {
                        "name": "order",
                        "type": "NewTradeOrderRequestDTO",
                        "ref": "NewTradeOrderRequestDTO",
                        "in": "body",
                    }
                ],
                request_type="NewTradeOrderRequestDTO",
                response_type="ApiTradeOrderResponseDTO",
                source_url=None,
                source_file=None,
                last_updated=None,
                raw={"name": "Trade"},
            )
        ],
        datatypes=[],
        lookups={},
        unresolved={"NewTradeOrderRequestDTO", "ApiTradeOrderResponseDTO"},
    )

    emit_contract_tests(catalog, tmp_path)

    rendered = (tmp_path / "tests" / "contract" / "test_endpoint_specs.py").read_text(
        encoding="utf-8"
    )
    assert '"POST"' in rendered
    assert '"order"' in rendered
    assert "False" in rendered
    assert '"SESSION"' in rendered
    assert '"INSTRUCTION"' in rendered
    assert '"NewTradeOrderRequestDTO"' in rendered
    assert '(("order", "body", "order"),)' in rendered
    assert "assert spec.idempotent is idempotent" in rendered
    assert "assert spec.auth_policy.name == auth_policy" in rendered
    assert "assert spec.rate_limit_bucket == rate_limit_bucket" in rendered
    assert "assert spec.status_domain.name == status_domain" in rendered
    assert "assert spec.request_model.__name__ == request_model" in rendered
    assert "assert param_fields == params" in rendered


def test_endpoint_contract_uses_endpoint_retry_safety_rules(tmp_path: Path) -> None:
    catalog = Catalog(
        endpoints=[
            _endpoint(
                "DeleteUserPreference",
                target="preference",
                path="/preference/v2/Preference",
                method="DELETE",
            ),
            _endpoint(
                "ListActiveOrders",
                target="order",
                path="/order/activeorders",
                method="POST",
            ),
            _endpoint(
                "SubmitOrder",
                target="order",
                path="/order/new",
                method="POST",
            ),
        ],
        datatypes=[],
        lookups={},
        unresolved=set(),
    )

    emit_contract_tests(catalog, tmp_path)

    rendered = (tmp_path / "tests" / "contract" / "test_endpoint_specs.py").read_text(
        encoding="utf-8"
    )
    assert (
        "_ep_preference.DELETE_USER_PREFERENCE_SPEC,\n"
        '        "DELETE",\n'
        '        "/preference/v2/Preference",\n'
        "        False,\n"
        "        True,"
    ) in rendered
    assert (
        "_ep_order.LIST_ACTIVE_ORDERS_SPEC,\n"
        '        "POST",\n'
        '        "/order/activeorders",\n'
        "        False,\n"
        "        True,"
    ) in rendered
    assert (
        "_ep_order.SUBMIT_ORDER_SPEC,\n"
        '        "POST",\n'
        '        "/order/new",\n'
        "        False,\n"
        "        False,"
    ) in rendered


def test_model_contract_builds_nested_payload_for_required_model_field(
    tmp_path: Path,
) -> None:
    catalog = Catalog(
        endpoints=[],
        datatypes=[
            _datatype(
                "ChildDTO",
                [
                    {
                        "name": "Value",
                        "type": "String",
                        "format": None,
                        "ref": None,
                    }
                ],
            ),
            _datatype(
                "ParentDTO",
                [
                    {
                        "name": "Child",
                        "type": "ChildDTO",
                        "format": None,
                        "ref": "ChildDTO",
                    }
                ],
            ),
        ],
        lookups={},
        unresolved=set(),
    )

    emit_contract_tests(catalog, tmp_path)

    rendered = (tmp_path / "tests" / "contract" / "test_models_roundtrip.py").read_text(
        encoding="utf-8"
    )
    assert "pytest.skip" not in rendered
    assert 'pytest.param(ParentDTO, {"Child": {"Value": "x"}}, id="ParentDTO")' in rendered


def test_recursive_required_model_graph_roundtrips_via_validate_after_cycle_break(
    tmp_path: Path,
) -> None:
    first_name = "FirstRecursiveModelWithRequiredPeerDTO"
    second_name = "SecondRecursiveModelWithRequiredPeerDTO"
    catalog = Catalog(
        endpoints=[],
        datatypes=[
            _datatype(
                first_name,
                [
                    {
                        "name": "Second",
                        "type": second_name,
                        "format": None,
                        "ref": second_name,
                    }
                ],
            ),
            _datatype(
                second_name,
                [
                    {
                        "name": "First",
                        "type": first_name,
                        "format": None,
                        "ref": first_name,
                    }
                ],
            ),
        ],
        lookups={},
        unresolved=set(),
    )

    emit_contract_tests(catalog, tmp_path)

    rendered = (tmp_path / "tests" / "contract" / "test_models_roundtrip.py").read_text(
        encoding="utf-8"
    )
    # Mutually-recursive required model refs are emitted optional (cycle-broken in
    # emit_models._cyclic_ref_fields), so the roundtrip test validates them normally rather than
    # falling back to model_construct.
    assert "requires recursive model payload" not in rendered
    assert "pytest.skip(skip_reason)" not in rendered
    assert "required recursive model graph has no finite validating JSON payload" not in rendered
    assert "model_construct" not in rendered
    assert '@pytest.mark.parametrize("model_cls, payload", MODEL_CASES)' in rendered
    assert "model_validate" in rendered
    assert first_name in rendered and second_name in rendered
    assert max(len(line) for line in rendered.splitlines()) <= 100


def test_lookup_enum_contract_records_lookup_values(tmp_path: Path) -> None:
    catalog = Catalog(
        endpoints=[],
        datatypes=[],
        lookups={
            "Custom Lookup": {
                "columns": ["Custom Lookup Code", "Description"],
                "rows": [
                    {"Custom Lookup Code": "1", "Description": "First Value"},
                    {"Custom Lookup Code": "2", "Description": "Second Value"},
                ],
            }
        },
        unresolved=set(),
    )

    emit_contract_tests(catalog, tmp_path)

    rendered = (tmp_path / "tests" / "contract" / "test_lookup_enums.py").read_text(
        encoding="utf-8"
    )
    assert "from enum import IntEnum" in rendered
    assert "from stonepy.models import CustomLookup" in rendered
    assert 'pytest.param(CustomLookup, {"FirstValue": 1, "SecondValue": 2}' in rendered
    assert "name: member.value for name, member in enum_cls.__members__.items()" in rendered


def _import_generated_module(path: Path, module_name: str) -> None:
    spec = importlib.util.spec_from_file_location(module_name, path)
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module
    try:
        spec.loader.exec_module(module)
    finally:
        del sys.modules[module_name]


def _snapshot_stonepy_modules() -> dict[str, ModuleType]:
    return {
        name: module
        for name, module in sys.modules.items()
        if name == "stonepy" or name.startswith("stonepy.")
    }


def _clear_stonepy_modules() -> None:
    for module_name in list(_snapshot_stonepy_modules()):
        del sys.modules[module_name]


def _restore_stonepy_modules(snapshot: dict[str, ModuleType]) -> None:
    _clear_stonepy_modules()
    sys.modules.update(snapshot)


def _endpoint(
    name: str,
    *,
    target: str,
    path: str,
    method: str = "GET",
    response_type: str | None = None,
) -> EndpointRecord:
    return EndpointRecord(
        name=name,
        logical_name=name,
        version="v1",
        description=None,
        method=method,
        target=target,
        uri_template=path,
        path=path,
        content_type="application/json",
        envelope="URL",
        parameters=[],
        request_type=None,
        response_type=response_type,
        source_url=None,
        source_file=None,
        last_updated=None,
        raw={"name": name},
    )


def _datatype(name: str, properties: list[dict[str, object]]) -> TypeRecord:
    return TypeRecord(
        name=name,
        catalog_name=name,
        version="v1",
        description=None,
        properties=properties,
        source_url=None,
        source_file=None,
        last_updated=None,
        raw={"name": name, "properties": properties},
    )
