# GENERATED by stonepy._generator. Do not edit by hand.
"""Resource method: SavePA."""

from __future__ import annotations

from stonepy._core.models import ResponseModel
from stonepy._core.resource import BaseResource
from stonepy._endpoints import price_alert as _ep
from stonepy.models import SaveAlertRequestDTOv2


class _SavePaMixin(BaseResource):
    def save_pa(self, request: SaveAlertRequestDTOv2) -> ResponseModel:
        """
        Perform a save operation for a client defined price alert. This service call is
        also used to update an alert by saving the new parameters and overwriting the
        previous settings on the same alert.
        """
        return _ep.save_pa(self._ctx, request)
