# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from stonepy._core.resource import BaseResource

from ._sync.get_market_report_headlines import (
    _GetMarketReportHeadlinesMixin as _SyncGetMarketReportHeadlinesMixin,
)
from ._sync.get_market_reports import _GetMarketReportsMixin as _SyncGetMarketReportsMixin
from ._sync.get_news import _GetNewsMixin as _SyncGetNewsMixin
from ._sync.get_news_headlines import _GetNewsHeadlinesMixin as _SyncGetNewsHeadlinesMixin
from ._sync.get_story import _GetStoryMixin as _SyncGetStoryMixin
from ._sync.search_market_reports import _SearchMarketReportsMixin as _SyncSearchMarketReportsMixin
from ._sync.search_news import _SearchNewsMixin as _SyncSearchNewsMixin
from .get_market_report_headlines import (
    _GetMarketReportHeadlinesMixin as _AsyncGetMarketReportHeadlinesMixin,
)
from .get_market_reports import _GetMarketReportsMixin as _AsyncGetMarketReportsMixin
from .get_news import _GetNewsMixin as _AsyncGetNewsMixin
from .get_news_headlines import _GetNewsHeadlinesMixin as _AsyncGetNewsHeadlinesMixin
from .get_story import _GetStoryMixin as _AsyncGetStoryMixin
from .search_market_reports import _SearchMarketReportsMixin as _AsyncSearchMarketReportsMixin
from .search_news import _SearchNewsMixin as _AsyncSearchNewsMixin


class NewsResource(
    _SyncGetMarketReportHeadlinesMixin,
    _SyncGetMarketReportsMixin,
    _SyncGetNewsMixin,
    _SyncGetNewsHeadlinesMixin,
    _SyncGetStoryMixin,
    _SyncSearchMarketReportsMixin,
    _SyncSearchNewsMixin,
    BaseResource,
):
    pass


class AsyncNewsResource(
    _AsyncGetMarketReportHeadlinesMixin,
    _AsyncGetMarketReportsMixin,
    _AsyncGetNewsMixin,
    _AsyncGetNewsHeadlinesMixin,
    _AsyncGetStoryMixin,
    _AsyncSearchMarketReportsMixin,
    _AsyncSearchNewsMixin,
    BaseResource,
):
    pass


__all__ = [
    "AsyncNewsResource",
    "NewsResource",
]
