# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .AccountResult import AccountResult


class AccountInformationResponseDTOv2(ResponseModel):
    account_result: AccountResult | None = Field(default=None, alias="AccountResult")


AccountInformationResponseDTOv2.model_rebuild(raise_errors=False)
