# GENERATED by stonepy._generator. Do not edit by hand.
"""
All service calls and DTOs related to Predicted Markets are for internal StoneX use only.
Response to a ListActiveSignals call containing the list of active trading signals.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .SignalDTO import SignalDTO


class ActiveSignalsResponseDTO(ResponseModel):
    """
    All service calls and DTOs related to Predicted Markets are for internal StoneX use only.
    Response to a ListActiveSignals call containing the list of active trading signals.
    """

    signals: list[SignalDTO] | None = Field(default=None, alias="Signals")
    """The list of active trading signals."""


ActiveSignalsResponseDTO.model_rebuild(raise_errors=False)
