# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from decimal import Decimal

from pydantic import Field

from stonepy._core.models import ResponseModel, StoneXDateTime

from .enums import AlertCriterion, AlertDirection, AlertExpiry, AlertNotification


class AlertDTO(ResponseModel):
    alert_id: int | None = Field(default=None, alias="AlertId")
    market_id: int | None = Field(default=None, alias="MarketId")
    criterion: AlertCriterion | None = Field(default=None, alias="Criterion")
    direction: AlertDirection | None = Field(default=None, alias="Direction")
    fill_rate: Decimal | None = Field(default=None, alias="FillRate")
    email_address: str | None = Field(default=None, alias="EmailAddress")
    expiry: AlertExpiry | None = Field(default=None, alias="Expiry")
    expiry_date: StoneXDateTime | None = Field(default=None, alias="ExpiryDate")
    create_date: StoneXDateTime | None = Field(default=None, alias="CreateDate")
    comment: str | None = Field(default=None, alias="Comment")
    notification_method: AlertNotification | None = Field(default=None, alias="NotificationMethod")


AlertDTO.model_rebuild(raise_errors=False)
