# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class Api2FALogonOnResponseDTO(ResponseModel):
    contact_id: int | None = Field(default=None, alias="ContactId")
    contact_category_id: int | None = Field(default=None, alias="ContactCategoryId")
    value: str | None = Field(default=None, alias="Value")


Api2FALogonOnResponseDTO.model_rebuild(raise_errors=False)
