# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ApiOrderResponseDTO import ApiOrderResponseDTO


class ApiAssociatedResponseDTO(ResponseModel):
    stop: ApiOrderResponseDTO | None = Field(default=None, alias="Stop")
    limit: ApiOrderResponseDTO | None = Field(default=None, alias="Limit")


ApiAssociatedResponseDTO.model_rebuild(raise_errors=False)
