# GENERATED by stonepy._generator. Do not edit by hand.
"""
Contains the associated stop and limit orders. An associated order is linked to a net position
rather than to specific individual trades.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ApiStopLimitOrderDTOv2 import ApiStopLimitOrderDTOv2


class ApiAssociatedDTOv2(ResponseModel):
    """
    Contains the associated stop and limit orders. An associated order is linked to a net
    position rather than to specific individual trades.
    """

    stop: ApiStopLimitOrderDTOv2 | None = Field(default=None, alias="Stop")
    """The associated stop order"""
    limit: ApiStopLimitOrderDTOv2 | None = Field(default=None, alias="Limit")
    """The associated limit order"""


ApiAssociatedDTOv2.model_rebuild(raise_errors=False)
