# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ApiManagedInstructionResponseDTO import ApiManagedInstructionResponseDTO


class ApiAdvisoryTradeOrderResponseDTO(ResponseModel):
    managed_instructions: list[ApiManagedInstructionResponseDTO] | None = Field(
        default=None, alias="ManagedInstructions"
    )


ApiAdvisoryTradeOrderResponseDTO.model_rebuild(raise_errors=False)
