# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class ApiAccountHolderDTO(ResponseModel):
    party_id: int | None = Field(default=None, alias="PartyId")
    name: str | None = Field(default=None, alias="Name")


ApiAccountHolderDTO.model_rebuild(raise_errors=False)
