# GENERATED by stonepy._generator. Do not edit by hand.
"""A stop or limit order with a limited number of data fields."""

from __future__ import annotations

from decimal import Decimal

from pydantic import Field

from stonepy._core.models import ResponseModel


class ApiBasicStopLimitOrderDTO(ResponseModel):
    """A stop or limit order with a limited number of data fields."""

    order_id: int | None = Field(default=None, alias="OrderId")
    """The order's unique identifier."""
    trigger_price: Decimal | None = Field(default=None, alias="TriggerPrice")
    """The order's trigger price."""
    trailing_distance: Decimal | None = Field(default=None, alias="TrailingDistance")
    """The stop order's trailing distance."""
    quantity: Decimal | None = Field(default=None, alias="Quantity")
    """The quantity of the product."""
    guaranteed: bool | None = Field(default=None, alias="Guaranteed")
    """Flag indicating if the stop order is a guaranteed order."""


ApiBasicStopLimitOrderDTO.model_rebuild(raise_errors=False)
