# GENERATED by stonepy._generator. Do not edit by hand.
"""
Response to a ClientCommunicationMessageUpdate (obsolete) service call. Returns a boolean flag
indicating whether the message update was retrieved.
"""

from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class ApiClientCommunicationUpdateResponseDTO(ResponseModel):
    """
    Response to a ClientCommunicationMessageUpdate (obsolete) service call. Returns a boolean
    flag indicating whether the message update was retrieved.
    """

    success: bool | None = Field(default=None, alias="Success")
    """Flag indicating whether the request was completed successfully."""


ApiClientCommunicationUpdateResponseDTO.model_rebuild(raise_errors=False)
