# GENERATED by stonepy._generator. Do not edit by hand.
"""Response to the save request for overridden client preferences."""

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ApiClientPreferencesOverridenSettingsSaveDTO import (
        ApiClientPreferencesOverridenSettingsSaveDTO,
    )


class ApiClientPreferencesOverriddenSettingsSaveResponseDTO(ResponseModel):
    """Response to the save request for overridden client preferences."""

    successful: bool | None = Field(default=None, alias="Successful")
    """Indicates whether the save request of overridden settings was successful."""
    settings: ApiClientPreferencesOverridenSettingsSaveDTO | None = Field(
        default=None, alias="Settings"
    )
    """The client level overridden settings that were saved."""


ApiClientPreferencesOverriddenSettingsSaveResponseDTO.model_rebuild(raise_errors=False)
