# GENERATED by stonepy._generator. Do not edit by hand.
"""All overridden client preference settings to save."""

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ApiClientPreferencesOverriddenSettingSaveDTO import (
        ApiClientPreferencesOverriddenSettingSaveDTO,
    )


class ApiClientPreferencesOverriddenSettingsSaveDTO(ResponseModel):
    """All overridden client preference settings to save."""

    price_tolerance: ApiClientPreferencesOverriddenSettingSaveDTO | None = Field(
        default=None, alias="Price Tolerance"
    )
    """The overridden price tolerance value to save - cannot be null"""
    margin_factor_percentage: ApiClientPreferencesOverriddenSettingSaveDTO | None = Field(
        default=None, alias="MarginFactorPercentage"
    )
    """The overridden margin factor value to save - cannot be null"""


ApiClientPreferencesOverriddenSettingsSaveDTO.model_rebuild(raise_errors=False)
