# GENERATED by stonepy._generator. Do not edit by hand.
"""Response to the save request for overridden client preferences."""

from __future__ import annotations

from typing import TYPE_CHECKING, overload

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ApiClientPreferencesOverridenSettingsSaveDTO import (
        ApiClientPreferencesOverridenSettingsSaveDTO,
    )

class ApiClientPreferencesOverridenSettingsSaveResponseDTO(ResponseModel):
    """Response to the save request for overridden client preferences."""

    successful: bool | None = Field(default=None, alias="Successful")
    """Indicates whether the save request of overridden settings was successful."""
    settings: ApiClientPreferencesOverridenSettingsSaveDTO | None = Field(
        default=None, alias="Settings"
    )
    """The client level overridden settings that were saved."""

    @overload
    def __init__(
        self,
        *,
        Successful: bool | None = ...,
        Settings: ApiClientPreferencesOverridenSettingsSaveDTO | None = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        *,
        successful: bool | None = ...,
        settings: ApiClientPreferencesOverridenSettingsSaveDTO | None = ...,
    ) -> None: ...
