# GENERATED by stonepy._generator. Do not edit by hand.
"""
The current margin and other account balance data for a specific client account used in the
ClientAccountMargin stream.
"""

from __future__ import annotations

from decimal import Decimal

from pydantic import Field

from stonepy._core.models import ResponseModel


class ApiClientAccountMarginResponseDTO(ResponseModel):
    """
    The current margin and other account balance data for a specific client account used in
    the ClientAccountMargin stream.
    """

    cash: Decimal | None = Field(default=None, alias="Cash")
    """The cash balance expressed in the client account base currency."""
    margin: Decimal | None = Field(default=None, alias="Margin")
    """The client account total margin requirement expressed in base currency."""
    margin_indicator: Decimal | None = Field(default=None, alias="MarginIndicator")
    """The margin indicator expressed as a percentage."""
    net_equity: Decimal | None = Field(default=None, alias="NetEquity")
    """The net equity expressed in the client account base currency."""
    open_trade_equity: Decimal | None = Field(default=None, alias="OpenTradeEquity")
    """
    The open trade equity (open or unrealised P&L) expressed in the client account base
    currency.
    """
    tradable_funds: Decimal | None = Field(default=None, alias="TradableFunds")
    """The tradable funds in the client account base currency."""
    pending_funds: Decimal | None = Field(default=None, alias="PendingFunds")
    """
    The amount in base currency that is still being processed for addition to the funds in the
    account.
    """
    trading_resource: Decimal | None = Field(default=None, alias="TradingResource")
    """The trading resource expressed in the client account base currency."""
    total_margin_requirement: Decimal | None = Field(default=None, alias="TotalMarginRequirement")
    """The total margin requirement expressed in the client account base currency."""
    currency_id: int | None = Field(default=None, alias="CurrencyId")
    """
    The ID code for the client account base currency. The table of lookup codes can be found
    at Lookup Values .
    """
    currency_iso_code: str | None = Field(default=None, alias="CurrencyIsoCode")
    """The base currency ISO code."""


ApiClientAccountMarginResponseDTO.model_rebuild(raise_errors=False)
