# GENERATED by stonepy._generator. Do not edit by hand.
"""A single overridden client preference value to save."""

from __future__ import annotations

from decimal import Decimal

from pydantic import Field

from stonepy._core.models import ResponseModel


class ApiClientPreferencesOverridenSettingSaveDTO(ResponseModel):
    """A single overridden client preference value to save."""

    is_dirty: bool | None = Field(default=None, alias="IsDirty")
    """The read/write status of the response."""
    value: Decimal | None = Field(default=None, alias="Value")
    """The value to save if IsDirty is TRUE. Can be null to unset the current value."""


ApiClientPreferencesOverridenSettingSaveDTO.model_rebuild(raise_errors=False)
