# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from decimal import Decimal

from pydantic import Field

from stonepy._core.models import ResponseModel


class ApiClientAccountMarginResponseDTO(ResponseModel):
    cash: Decimal | None = Field(default=None, alias="Cash")
    margin: Decimal | None = Field(default=None, alias="Margin")
    margin_indicator: Decimal | None = Field(default=None, alias="MarginIndicator")
    net_equity: Decimal | None = Field(default=None, alias="NetEquity")
    open_trade_equity: Decimal | None = Field(default=None, alias="OpenTradeEquity")
    tradable_funds: Decimal | None = Field(default=None, alias="TradableFunds")
    pending_funds: Decimal | None = Field(default=None, alias="PendingFunds")
    trading_resource: Decimal | None = Field(default=None, alias="TradingResource")
    total_margin_requirement: Decimal | None = Field(default=None, alias="TotalMarginRequirement")
    currency_id: int | None = Field(default=None, alias="CurrencyId")
    currency_iso_code: str | None = Field(default=None, alias="CurrencyIsoCode")


ApiClientAccountMarginResponseDTO.model_rebuild(raise_errors=False)
