# GENERATED by stonepy._generator. Do not edit by hand.
"""
List entry for ApiGetMultipleUsersDetailsResponseDTO . Contains the CI Connect user details
for all users given in the parameter of the GetMultipleUsersDetailsByScreenNames call. Note:
for use of the CI Connect social trading platform.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ApiConnectUserDetailsDTO import ApiConnectUserDetailsDTO


class ApiCiConnectMultipleUsersDetailsDTO(ResponseModel):
    """
    List entry for ApiGetMultipleUsersDetailsResponseDTO . Contains the CI Connect user
    details for all users given in the parameter of the GetMultipleUsersDetailsByScreenNames
    call. Note: for use of the CI Connect social trading platform.
    """

    client_account_id: int | None = Field(default=None, alias="ClientAccountId")
    """The user's client account ID."""
    screen_name: str | None = Field(default=None, alias="ScreenName")
    """The user's screen name."""
    facebook_id: str | None = Field(default=None, alias="FacebookId")
    """The user's Facebook ID."""
    ci_connect_user_details: ApiConnectUserDetailsDTO | None = Field(
        default=None, alias="CiConnectUserDetails"
    )
    """The user details for each individual user."""


ApiCiConnectMultipleUsersDetailsDTO.model_rebuild(raise_errors=False)
