# GENERATED by stonepy._generator. Do not edit by hand.
"""
Details of a user that was involved in a community action. Note: for use of the CI Connect
social trading platform.
"""

from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class ApiCommunityActionUserDetailsDTO(ResponseModel):
    """
    Details of a user that was involved in a community action. Note: for use of the CI Connect
    social trading platform.
    """

    screen_name: str | None = Field(default=None, alias="ScreenName")
    """The user's screen name."""
    first_name: str | None = Field(default=None, alias="FirstName")
    """The user's first name."""
    last_name: str | None = Field(default=None, alias="LastName")
    """The user's surname."""
    avatar: str | None = Field(default=None, alias="Avatar")
    """The user's avatar."""


ApiCommunityActionUserDetailsDTO.model_rebuild(raise_errors=False)
