# GENERATED by stonepy._generator. Do not edit by hand.
"""All overridden client preference settings to get."""

from __future__ import annotations

from typing import TYPE_CHECKING, overload

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ApiClientPreferencesOverriddenMarginFactorDTO import (
        ApiClientPreferencesOverriddenMarginFactorDTO,
    )
    from .ApiClientPreferencesOverriddenPriceToleranceDTO import (
        ApiClientPreferencesOverriddenPriceToleranceDTO,
    )

class ApiClientPreferencesOverriddenSettingsDTO(ResponseModel):
    """All overridden client preference settings to get."""

    price_tolerance: ApiClientPreferencesOverriddenPriceToleranceDTO | None = Field(
        default=None, alias="Price Tolerance"
    )
    """The overridden price tolerance value"""
    margin_factor_percentage: ApiClientPreferencesOverriddenMarginFactorDTO | None = Field(
        default=None, alias="MarginFactorPercentage"
    )
    """The overridden margin factor value"""

    @overload
    def __init__(
        self,
        *,
        price_tolerance: ApiClientPreferencesOverriddenPriceToleranceDTO | None = ...,
        MarginFactorPercentage: ApiClientPreferencesOverriddenMarginFactorDTO | None = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        *,
        price_tolerance: ApiClientPreferencesOverriddenPriceToleranceDTO | None = ...,
        margin_factor_percentage: ApiClientPreferencesOverriddenMarginFactorDTO | None = ...,
    ) -> None: ...
