# GENERATED by stonepy._generator. Do not edit by hand.
"""Information about contracts."""

from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class ApiContractDTOv2(ResponseModel):
    """Information about contracts."""

    contract_id: int | None = Field(default=None, alias="ContractId")
    """Contract identifier"""
    is_nigo: bool | None = Field(default=None, alias="IsNIGO")
    """Is NIGO flag"""
    contract_type: int | None = Field(default=None, alias="ContractType")
    """Contract type"""


ApiContractDTOv2.model_rebuild(raise_errors=False)
