# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ApiClientPreferencesOverridenSettingsSaveDTO import (
        ApiClientPreferencesOverridenSettingsSaveDTO,
    )


class ApiClientPreferencesOverriddenSettingsSaveResponseDTO(ResponseModel):
    successful: bool | None = Field(default=None, alias="Successful")
    settings: ApiClientPreferencesOverridenSettingsSaveDTO | None = Field(
        default=None, alias="Settings"
    )


ApiClientPreferencesOverriddenSettingsSaveResponseDTO.model_rebuild(raise_errors=False)
