# GENERATED by stonepy._generator. Do not edit by hand.
"""Watchlist item."""

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ApiMarketInformationDTOv2 import ApiMarketInformationDTOv2


class ApiClientAccountWatchlistItemDTO(ResponseModel):
    """Watchlist item."""

    watchlist_id: int | None = Field(default=None, alias="WatchlistId")
    """Identifier of the parent watchlist"""
    market_id: int | None = Field(default=None, alias="MarketId")
    """Watchlist item market identifier"""
    market_information: ApiMarketInformationDTOv2 | None = Field(
        default=None, alias="MarketInformation"
    )
    """
    Watchlist item market information Note: should be left null when making a save watchlist
    call
    """
    display_order: int | None = Field(default=None, alias="DisplayOrder")
    """Watchlist item display order"""


ApiClientAccountWatchlistItemDTO.model_rebuild(raise_errors=False)
