# GENERATED by stonepy._generator. Do not edit by hand.
"""The Price Tolerance single overridden client preference value to retrieve."""

from __future__ import annotations

from decimal import Decimal
from typing import overload

from pydantic import Field

from stonepy._core.models import ResponseModel

class ApiClientPreferencesOverridenPriceToleranceDTO(ResponseModel):
    """The Price Tolerance single overridden client preference value to retrieve."""

    value: Decimal | None = Field(default=None, alias="Value")
    """Setting to indicate the user's price tolerance for the client account."""

    @overload
    def __init__(
        self,
        *,
        Value: Decimal | None = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        *,
        value: Decimal | None = ...,
    ) -> None: ...
