# GENERATED by stonepy._generator. Do not edit by hand.
"""A request to retrieve application message translation keys."""

from __future__ import annotations

from typing import overload

from pydantic import Field

from stonepy._core.models import RequestModel

class ApiClientApplicationMessageTranslationRequestDTO(RequestModel):
    """A request to retrieve application message translation keys."""

    client_application_id: int = Field(alias="ClientApplicationId")
    """Client Id of requesting user."""
    culture_id: int = Field(alias="CultureId")
    """Culture Id of requesting user."""
    account_operator_id: int = Field(alias="AccountOperatorId")
    """Account Operator ID of requesting user"""
    interested_translation_keys: list[str] = Field(alias="InterestedTranslationKeys")
    """A list of interesting keys to get translations for."""

    @overload
    def __init__(
        self,
        *,
        ClientApplicationId: int,
        CultureId: int,
        AccountOperatorId: int,
        InterestedTranslationKeys: list[str],
    ) -> None: ...
    @overload
    def __init__(
        self,
        *,
        client_application_id: int,
        culture_id: int,
        account_operator_id: int,
        interested_translation_keys: list[str],
    ) -> None: ...
