# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ClientCommunicationMessageDTO import ClientCommunicationMessageDTO


class ApiClientCommunicationResponseDTO(ResponseModel):
    client_communication_messages: list[ClientCommunicationMessageDTO] | None = Field(
        default=None, alias="ClientCommunicationMessages"
    )


ApiClientCommunicationResponseDTO.model_rebuild(raise_errors=False)
