# GENERATED by stonepy._generator. Do not edit by hand.
"""Information about a client account."""

from __future__ import annotations

from typing import TYPE_CHECKING, overload

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .Timestamp import Timestamp

class ApiClientAccountDTO(ResponseModel):
    """Information about a client account."""

    contract_id: int | None = Field(default=None, alias="ContractId")
    """Contract identifier"""
    client_account_id: int | None = Field(default=None, alias="ClientAccountId")
    """Client Account identifier"""
    culture_id: int | None = Field(default=None, alias="CultureId")
    """Culture identifier"""
    client_account_currency: str | None = Field(default=None, alias="ClientAccountCurrency")
    """Client account currency"""
    account_operator_id: int | None = Field(default=None, alias="AccountOperatorId")
    """Account operator identifier"""
    client_type_id: int | None = Field(default=None, alias="ClientTypeId")
    """Client type identifier"""
    is_mi_fid_regulator: bool | None = Field(default=None, alias="IsMiFIDRegulator")
    """MiFID regulator apply flag"""
    client_account_creation_date: Timestamp | None = Field(
        default=None, alias="ClientAccountCreationDate"
    )
    """Time when account was created"""
    is_meta_trader: bool | None = Field(default=None, alias="isMetaTrader")
    """Is MetaTrader account flag"""
    brand_parent_id: int | None = Field(default=None, alias="BrandParentId")
    """Brand parent identifier"""
    account_group_name: str | None = Field(default=None, alias="AccountGroupName")
    """Account Group Name"""

    @overload
    def __init__(
        self,
        *,
        ContractId: int | None = ...,
        ClientAccountId: int | None = ...,
        CultureId: int | None = ...,
        ClientAccountCurrency: str | None = ...,
        AccountOperatorId: int | None = ...,
        ClientTypeId: int | None = ...,
        IsMiFIDRegulator: bool | None = ...,
        ClientAccountCreationDate: Timestamp | None = ...,
        isMetaTrader: bool | None = ...,
        BrandParentId: int | None = ...,
        AccountGroupName: str | None = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        *,
        contract_id: int | None = ...,
        client_account_id: int | None = ...,
        culture_id: int | None = ...,
        client_account_currency: str | None = ...,
        account_operator_id: int | None = ...,
        client_type_id: int | None = ...,
        is_mi_fid_regulator: bool | None = ...,
        client_account_creation_date: Timestamp | None = ...,
        is_meta_trader: bool | None = ...,
        brand_parent_id: int | None = ...,
        account_group_name: str | None = ...,
    ) -> None: ...
