# GENERATED by stonepy._generator. Do not edit by hand.
"""
List entry for ApiCiConnectMultipleUsersDetailsDTO . It contains the data representing a user
of the CI Connect system. Note: for use of the CI Connect social trading platform.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel, StoneXDateTime

if TYPE_CHECKING:
    from .ApiUserDynamicProfileDTO import ApiUserDynamicProfileDTO
    from .ApiUserProfileDTO import ApiUserProfileDTO
    from .ApiUserTradingAccountDTO import ApiUserTradingAccountDTO


class ApiConnectUserDetailsDTO(ResponseModel):
    """
    List entry for ApiCiConnectMultipleUsersDetailsDTO . It contains the data representing a
    user of the CI Connect system. Note: for use of the CI Connect social trading platform.
    """

    user_profile: ApiUserProfileDTO | None = Field(default=None, alias="UserProfile")
    """The profile information for the user."""
    user_dynamic_profile_dto: ApiUserDynamicProfileDTO | None = Field(
        default=None, alias="UserDynamicProfileDTO"
    )
    """The user's dynamic (calculated details) profile."""
    user_trading_accounts: list[ApiUserTradingAccountDTO] | None = Field(
        default=None, alias="UserTradingAccounts"
    )
    """List of the user's trading accounts."""
    create_date: StoneXDateTime | None = Field(default=None, alias="CreateDate")
    """The date and time when the user was created in the CI Connect database."""
    last_changed_date: StoneXDateTime | None = Field(default=None, alias="LastChangedDate")
    """The date and time when the user's details were last updated in the CI Connect database."""


ApiConnectUserDetailsDTO.model_rebuild(raise_errors=False)
