# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from decimal import Decimal

from pydantic import Field

from stonepy._core.models import ResponseModel


class ApiClientPreferencesOverridenPriceToleranceDTO(ResponseModel):
    value: Decimal | None = Field(default=None, alias="Value")


ApiClientPreferencesOverridenPriceToleranceDTO.model_rebuild(raise_errors=False)
