# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from decimal import Decimal

from pydantic import Field

from stonepy._core.models import ResponseModel


class ApiClientPreferencesOverridenSettingSaveDTO(ResponseModel):
    is_dirty: bool | None = Field(default=None, alias="IsDirty")
    value: Decimal | None = Field(default=None, alias="Value")


ApiClientPreferencesOverridenSettingSaveDTO.model_rebuild(raise_errors=False)
