# GENERATED by stonepy._generator. Do not edit by hand.
"""Lookup data specific to a Culture."""

from __future__ import annotations

from typing import overload

from pydantic import Field

from stonepy._core.models import ResponseModel

class ApiCultureLookupDTO(ResponseModel):
    """Lookup data specific to a Culture."""

    code: str | None = Field(default=None, alias="Code")
    """Two letter ISO 639 culture code followed by a two letter uppercase ISO 3166 culture code."""

    @overload
    def __init__(
        self,
        *,
        Code: str | None = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        *,
        code: str | None = ...,
    ) -> None: ...
