# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from pydantic import Field

from stonepy._core.models import RequestModel


class ApiClientApplicationMessageTranslationRequestDTO(RequestModel):
    client_application_id: int = Field(alias="ClientApplicationId")
    culture_id: int = Field(alias="CultureId")
    account_operator_id: int = Field(alias="AccountOperatorId")
    interested_translation_keys: list[str] = Field(alias="InterestedTranslationKeys")


ApiClientApplicationMessageTranslationRequestDTO.model_rebuild(raise_errors=False)
