# GENERATED by stonepy._generator. Do not edit by hand.
"""Response from a request to delete a watchlist."""

from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class ApiDeleteWatchlistResponseDTO(ResponseModel):
    """Response from a request to delete a watchlist."""

    deleted: bool | None = Field(default=None, alias="Deleted")
    """Flag confirming whether the watchlist was deleted."""


ApiDeleteWatchlistResponseDTO.model_rebuild(raise_errors=False)
