# GENERATED by stonepy._generator. Do not edit by hand.
"""
Contains DateTime represented as UTC time and time zone offset in minutes to convert back to
local time.
"""

from __future__ import annotations

from typing import overload

from pydantic import Field

from stonepy._core.models import ResponseModel, StoneXDateTime

class ApiDateTimeOffsetDTO(ResponseModel):
    """
    Contains DateTime represented as UTC time and time zone offset in minutes to convert back
    to local time.
    """

    utc_date_time: StoneXDateTime | None = Field(default=None, alias="UtcDateTime")
    """Gets the date and time in UTC"""
    offset_minutes: int | None = Field(default=None, alias="OffsetMinutes")
    """Gets the time's offset from Coordinated Universal Time (UTC)"""

    @overload
    def __init__(
        self,
        *,
        UtcDateTime: StoneXDateTime | None = ...,
        OffsetMinutes: int | None = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        *,
        utc_date_time: StoneXDateTime | None = ...,
        offset_minutes: int | None = ...,
    ) -> None: ...
