# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class ApiDeleteWatchlistRequestDTO(ResponseModel):
    watchlist_id: int | None = Field(default=None, alias="WatchlistId")


ApiDeleteWatchlistRequestDTO.model_rebuild(raise_errors=False)
