# GENERATED by stonepy._generator. Do not edit by hand.
"""The response to an error condition."""

from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class ApiErrorResponseDTO(ResponseModel):
    """The response to an error condition."""

    http_status: int | None = Field(default=None, alias="HttpStatus")
    """
    The intended HTTP status code. This will be the same value as the actual HTTP status code
    unless the QueryString contains only200=true . This is useful for JavaScript clients who
    can only read responses with status code 200.
    """
    error_message: str | None = Field(default=None, alias="ErrorMessage")
    """This is a description of the ErrorMessage property."""
    error_code: int | None = Field(default=None, alias="ErrorCode")
    """The error code."""


ApiErrorResponseDTO.model_rebuild(raise_errors=False)
