# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class ApiFollowerDTO(ResponseModel):
    client_account_id: int | None = Field(default=None, alias="ClientAccountId")
    screen_name: str | None = Field(default=None, alias="ScreenName")


ApiFollowerDTO.model_rebuild(raise_errors=False)
