# GENERATED by stonepy._generator. Do not edit by hand.
"""Contains an FX market's financing information."""

from __future__ import annotations

from decimal import Decimal
from typing import overload

from pydantic import Field

from stonepy._core.models import ResponseModel, StoneXDateTime

class ApiFxFinancingDTO(ResponseModel):
    """Contains an FX market's financing information."""

    capture_date_time: StoneXDateTime | None = Field(default=None, alias="CaptureDateTime")
    """The starting date when the financing charge will be applied"""
    long_points: Decimal | None = Field(default=None, alias="LongPoints")
    """The points rate for long positions used in the FX financing charge calculation"""
    short_points: Decimal | None = Field(default=None, alias="ShortPoints")
    """The points rate for short positions used in the FX financing charge calculation"""
    long_charge: Decimal | None = Field(default=None, alias="LongCharge")
    """Example long financing charge"""
    short_charge: Decimal | None = Field(default=None, alias="ShortCharge")
    """Example short financing charge"""
    quantity: Decimal | None = Field(default=None, alias="Quantity")
    """The quantity used in calculating the example charges"""
    charge_currency_id: int | None = Field(default=None, alias="ChargeCurrencyId")
    """The ID of the currency for the long and short financing charges"""
    days_to_roll: int | None = Field(default=None, alias="DaysToRoll")
    """The number of days to apply the financing charge"""

    @overload
    def __init__(
        self,
        *,
        CaptureDateTime: StoneXDateTime | None = ...,
        LongPoints: Decimal | None = ...,
        ShortPoints: Decimal | None = ...,
        LongCharge: Decimal | None = ...,
        ShortCharge: Decimal | None = ...,
        Quantity: Decimal | None = ...,
        ChargeCurrencyId: int | None = ...,
        DaysToRoll: int | None = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        *,
        capture_date_time: StoneXDateTime | None = ...,
        long_points: Decimal | None = ...,
        short_points: Decimal | None = ...,
        long_charge: Decimal | None = ...,
        short_charge: Decimal | None = ...,
        quantity: Decimal | None = ...,
        charge_currency_id: int | None = ...,
        days_to_roll: int | None = ...,
    ) -> None: ...
