# GENERATED by stonepy._generator. Do not edit by hand.
"""
List entry for ApiUserFollowedUsersDTO . Contains the screen name and account ID of a CI
Connect secondary follower who is following another CI Connect user (primary follower) that is
following yet another CI Connect trader. Note: for use of the CI Connect social trading
platform.
"""

from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class ApiFollowedDTO(ResponseModel):
    """
    List entry for ApiUserFollowedUsersDTO . Contains the screen name and account ID of a CI
    Connect secondary follower who is following another CI Connect user (primary follower)
    that is following yet another CI Connect trader. Note: for use of the CI Connect social
    trading platform.
    """

    client_account_id: int | None = Field(default=None, alias="ClientAccountId")
    """The account ID for the secondary CI Connect follower."""
    screen_name: str | None = Field(default=None, alias="ScreenName")
    """The CI Connect screen name for the user."""


ApiFollowedDTO.model_rebuild(raise_errors=False)
