# GENERATED by stonepy._generator. Do not edit by hand.
"""
Response to a CI Connect GetSocialActions call. Contains the list of community actions. Note:
this API call response is for the use of the CI Connect social trading platform.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ApiCommunityActionDTO import ApiCommunityActionDTO


class ApiGetCommunityActionsResponseDTO(ResponseModel):
    """
    Response to a CI Connect GetSocialActions call. Contains the list of community actions.
    Note: this API call response is for the use of the CI Connect social trading platform.
    """

    community_actions: ApiCommunityActionDTO | None = Field(default=None, alias="CommunityActions")
    """The list of community actions."""


ApiGetCommunityActionsResponseDTO.model_rebuild(raise_errors=False)
