# GENERATED by stonepy._generator. Do not edit by hand.
"""Result of a get client preference request."""

from __future__ import annotations

from typing import TYPE_CHECKING, overload

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ClientPreferenceKeyDTO import ClientPreferenceKeyDTO

class ApiGetClientPreferenceResponseDTO(ResponseModel):
    """Result of a get client preference request."""

    client_preference: ClientPreferenceKeyDTO | None = Field(default=None, alias="ClientPreference")
    """The requested client preference key value pair"""

    @overload
    def __init__(
        self,
        *,
        ClientPreference: ClientPreferenceKeyDTO | None = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        *,
        client_preference: ClientPreferenceKeyDTO | None = ...,
    ) -> None: ...
