# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ClientPreferenceKeyDTO import ClientPreferenceKeyDTO


class ApiGetClientPreferenceResponseDTO(ResponseModel):
    client_preference: ClientPreferenceKeyDTO | None = Field(default=None, alias="ClientPreference")


ApiGetClientPreferenceResponseDTO.model_rebuild(raise_errors=False)
