# GENERATED by stonepy._generator. Do not edit by hand.
"""Results of client preference get request."""

from __future__ import annotations

from typing import overload

from pydantic import Field

from stonepy._core.models import ResponseModel

class ApiGetKeyListClientPreferenceResponseDTO(ResponseModel):
    """Results of client preference get request."""

    client_preference_keys: list[str] | None = Field(default=None, alias="ClientPreferenceKeys")
    """The list of client preference keys"""

    @overload
    def __init__(
        self,
        *,
        ClientPreferenceKeys: list[str] | None = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        *,
        client_preference_keys: list[str] | None = ...,
    ) -> None: ...
