# GENERATED by stonepy._generator. Do not edit by hand.
"""Result of a get client preference request."""

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ClientPreferenceKeyDTO import ClientPreferenceKeyDTO


class ApiGetClientPreferenceResponseDTO(ResponseModel):
    """Result of a get client preference request."""

    client_preference: ClientPreferenceKeyDTO | None = Field(default=None, alias="ClientPreference")
    """The requested client preference key value pair"""


ApiGetClientPreferenceResponseDTO.model_rebuild(raise_errors=False)
