# GENERATED by stonepy._generator. Do not edit by hand.
"""
Response to a CI Connect GetWallItemsForUsers call. Contains the list of wall items for the
specified users. Note: this API call response is for the use of the CI Connect social trading
platform.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ApiWallItemsForUsersDTO import ApiWallItemsForUsersDTO


class ApiGetWallItemsForUsersResponseDTO(ResponseModel):
    """
    Response to a CI Connect GetWallItemsForUsers call. Contains the list of wall items for
    the specified users. Note: this API call response is for the use of the CI Connect social
    trading platform.
    """

    wall_items_for_users: ApiWallItemsForUsersDTO | None = Field(
        default=None, alias="WallItemsForUsers"
    )
    """The list of specified users and their respective wall items."""


ApiGetWallItemsForUsersResponseDTO.model_rebuild(raise_errors=False)
