# GENERATED by stonepy._generator. Do not edit by hand.
"""Knockout information."""

from __future__ import annotations

from decimal import Decimal

from pydantic import Field

from stonepy._core.models import ResponseModel


class ApiKnockoutDTO(ResponseModel):
    """Knockout information."""

    paired_markets: int | None = Field(default=None, alias="PairedMarkets")
    """Provides the paired bull or bear market Id"""
    knockout_levels: int | None = Field(default=None, alias="KnockoutLevels")
    """The number of levels the UI should generate and present to the client as closeout levels"""
    knockout_increment: Decimal | None = Field(default=None, alias="KnockoutIncrement")
    """Specifies the gap between UI generated knockout levels"""
    knockout_increment_units: int | None = Field(default=None, alias="KnockoutIncrementUnits")
    """Units of the knockout increment value"""
    knockout_min_distance: Decimal | None = Field(default=None, alias="KnockoutMinDistance")
    """The min distance for the first knockout level"""
    knockout_min_distance_units: int | None = Field(default=None, alias="KnockoutMinDistanceUnits")
    """Units of the min distance for the knockout level"""


ApiKnockoutDTO.model_rebuild(raise_errors=False)
