# GENERATED by stonepy._generator. Do not edit by hand.
"""Response from a session delete (Log Out) request."""

from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class ApiLogOffResponseDTO(ResponseModel):
    """Response from a session delete (Log Out) request."""

    logged_out: bool | None = Field(default=None, alias="LoggedOut")
    """Flag indicating the Log Out status, where true == successful log out."""


ApiLogOffResponseDTO.model_rebuild(raise_errors=False)
