# GENERATED by stonepy._generator. Do not edit by hand.
"""
Response to the CI Connect social trading platform ListTopholdersForMarkets method call. Gives
a list of the CI Connect registered topholders for the specified market(s).
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ApiListTopholdersDTO import ApiListTopholdersDTO


class ApiListTopholdersForMarketsResponseDTO(ResponseModel):
    """
    Response to the CI Connect social trading platform ListTopholdersForMarkets method call.
    Gives a list of the CI Connect registered topholders for the specified market(s).
    """

    top_holders: ApiListTopholdersDTO | None = Field(default=None, alias="TopHolders")
    """
    List of the topholders for the specified market(s). Only topholders who have registered
    with the CI Connect social trading platform are returned.
    """


ApiListTopholdersForMarketsResponseDTO.model_rebuild(raise_errors=False)
