# GENERATED by stonepy._generator. Do not edit by hand.
"""Request to create a session (log on) ."""

from __future__ import annotations

from typing import overload

from pydantic import Field

from stonepy._core.models import RequestModel

class ApiLogOnRequestDTO(RequestModel):
    """Request to create a session (log on) ."""

    user_name: str = Field(alias="UserName")
    """Username is case sensitive"""
    password: str = Field(alias="Password", repr=False)
    """Password is case sensitive"""
    app_key: str = Field(alias="AppKey", repr=False)
    """A unique key to identify the client application"""
    app_version: str = Field(alias="AppVersion")
    """The version of the client application"""
    app_comments: str = Field(alias="AppComments")
    """Any client application comments on what to associate with this session"""

    @overload
    def __init__(
        self,
        *,
        UserName: str,
        Password: str,
        AppKey: str,
        AppVersion: str,
        AppComments: str,
    ) -> None: ...
    @overload
    def __init__(
        self,
        *,
        user_name: str,
        password: str,
        app_key: str,
        app_version: str,
        app_comments: str,
    ) -> None: ...
