# GENERATED by stonepy._generator. Do not edit by hand.
"""Request to delete a session (log off) . Deprecated!"""

from __future__ import annotations

from typing import overload

from pydantic import Field

from stonepy._core.models import ResponseModel

class ApiLogOffRequestDTO(ResponseModel):
    """Request to delete a session (log off) . Deprecated!"""

    user_name: str | None = Field(default=None, alias="UserName")
    """User name of the session to delete (log off) . This is case sensitive."""
    session: str | None = Field(default=None, alias="Session", repr=False)
    """Session identifier (session token) to delete (log off) ."""

    @overload
    def __init__(
        self,
        *,
        UserName: str | None = ...,
        Session: str | None = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        *,
        user_name: str | None = ...,
        session: str | None = ...,
    ) -> None: ...
