# GENERATED by stonepy._generator. Do not edit by hand.
"""Gets the lookup entities from trading database given the lookup name and culture ID."""

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ApiCultureLookupDTO import ApiCultureLookupDTO
    from .ApiLookupDTO import ApiLookupDTO


class ApiLookupResponseDTO(ResponseModel):
    """Gets the lookup entities from trading database given the lookup name and culture ID."""

    culture_id: int | None = Field(default=None, alias="CultureId")
    """The requested culture ID."""
    lookup_entity_name: str | None = Field(default=None, alias="LookupEntityName")
    """The requested lookup name."""
    api_lookup_dto_list: list[ApiLookupDTO] | None = Field(default=None, alias="ApiLookupDTOList")
    """List of lookup entities from the database."""
    api_culture_lookup_dto_list: list[ApiCultureLookupDTO] | None = Field(
        default=None, alias="ApiCultureLookupDTOList"
    )
    """List of entities each containing data specific to a culture."""


ApiLookupResponseDTO.model_rebuild(raise_errors=False)
