# GENERATED by stonepy._generator. Do not edit by hand.
"""Generic look up data entities - such as localised text names."""

from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class ApiLookupDTO(ResponseModel):
    """Generic look up data entities - such as localised text names."""

    id: int | None = Field(default=None, alias="Id")
    """The lookup ID."""
    description: str | None = Field(default=None, alias="Description")
    """Lookup items description."""
    display_order: int | None = Field(default=None, alias="DisplayOrder")
    """The order to display the items on a user interface."""
    translation_text_id: int | None = Field(default=None, alias="TranslationTextId")
    """Translation text ID."""
    translation_text: str | None = Field(default=None, alias="TranslationText")
    """Translated text."""
    is_active: bool | None = Field(default=None, alias="IsActive")
    """Is active flag."""
    is_allowed: bool | None = Field(default=None, alias="IsAllowed")
    """Is allowed flag."""


ApiLookupDTO.model_rebuild(raise_errors=False)
