# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class ApiLookupDTO(ResponseModel):
    id: int | None = Field(default=None, alias="Id")
    description: str | None = Field(default=None, alias="Description")
    display_order: int | None = Field(default=None, alias="DisplayOrder")
    translation_text_id: int | None = Field(default=None, alias="TranslationTextId")
    translation_text: str | None = Field(default=None, alias="TranslationText")
    is_active: bool | None = Field(default=None, alias="IsActive")
    is_allowed: bool | None = Field(default=None, alias="IsAllowed")


ApiLookupDTO.model_rebuild(raise_errors=False)
