# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class ApiLogOffRequestDTO(ResponseModel):
    user_name: str | None = Field(default=None, alias="UserName")
    session: str | None = Field(default=None, alias="Session")


ApiLogOffRequestDTO.model_rebuild(raise_errors=False)
