# GENERATED by stonepy._generator. Do not edit by hand.
"""A constituent order of a Trading Advisor managed position."""

from __future__ import annotations

from decimal import Decimal
from typing import overload

from pydantic import Field

from stonepy._core.models import ResponseModel, StoneXDateTime

class ApiManagedTradeDTO(ResponseModel):
    """A constituent order of a Trading Advisor managed position."""

    order_id: int | None = Field(default=None, alias="OrderId")
    """The unique identifier for the order"""
    quantity: Decimal | None = Field(default=None, alias="Quantity")
    """The order size or amount"""
    trading_account_id: int | None = Field(default=None, alias="TradingAccountId")
    """The unique identifier for the managed trading account that the order is being placed on"""
    trading_account_code: str | None = Field(default=None, alias="TradingAccountCode")
    """The code of the managed trading account that the order is being placed on"""
    trading_account_name: str | None = Field(default=None, alias="TradingAccountName")
    """The name of the managed trading account that the order is being placed on"""
    last_changed_date_time_utc: StoneXDateTime | None = Field(
        default=None, alias="LastChangedDateTimeUTC"
    )
    """
    Represents the date and time when the order was last changed. Note: does not include
    things such as the current market price
    """

    @overload
    def __init__(
        self,
        *,
        OrderId: int | None = ...,
        Quantity: Decimal | None = ...,
        TradingAccountId: int | None = ...,
        TradingAccountCode: str | None = ...,
        TradingAccountName: str | None = ...,
        LastChangedDateTimeUTC: StoneXDateTime | None = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        *,
        order_id: int | None = ...,
        quantity: Decimal | None = ...,
        trading_account_id: int | None = ...,
        trading_account_code: str | None = ...,
        trading_account_name: str | None = ...,
        last_changed_date_time_utc: StoneXDateTime | None = ...,
    ) -> None: ...
