# GENERATED by stonepy._generator. Do not edit by hand.
"""Basic information about a market tag."""

from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class ApiMarketTagDTO(ResponseModel):
    """Basic information about a market tag."""

    market_tag_id: int | None = Field(default=None, alias="MarketTagId")
    """A unique identifier for this market tag"""
    name: str | None = Field(default=None, alias="Name")
    """The market tag description. Can be localised if required"""
    type: int | None = Field(default=None, alias="Type")
    """Used to determine if the market tag is a primary (1) or secondary (2) tag"""
    weighting: int | None = Field(default=None, alias="Weighting")
    """
    Weighting of the market between 0 and 1000 inclusive. Relays the priority of the market in
    the market search results. The higher the value the more prominent the market should
    appear
    """


ApiMarketTagDTO.model_rebuild(raise_errors=False)
