# GENERATED by stonepy._generator. Do not edit by hand.
"""
Details of a previous trade within a Trading Advisor managed client account for use in the
Trade History.
"""

from __future__ import annotations

from decimal import Decimal

from pydantic import Field

from stonepy._core.models import ResponseModel, StoneXDateTime


class ApiManagedTradeHistoryDTO(ResponseModel):
    """
    Details of a previous trade within a Trading Advisor managed client account for use in the
    Trade History.
    """

    order_id: int | None = Field(default=None, alias="OrderId")
    """The unique identifier for the order."""
    opening_order_ids: list[int] | None = Field(default=None, alias="OpeningOrderIds")
    """
    The list of order identifiers for the opening orders that are being closed or part closed
    by this closing order.
    """
    trading_account_id: int | None = Field(default=None, alias="TradingAccountId")
    """The unique identifier for the managed trading account that the order is being placed on."""
    trading_account_code: str | None = Field(default=None, alias="TradingAccountCode")
    """The code of the managed trading account that the order is being placed on."""
    trading_account_name: str | None = Field(default=None, alias="TradingAccountName")
    """The name of the managed trading account that the order is being placed on."""
    original_quantity: Decimal | None = Field(default=None, alias="OriginalQuantity")
    """The original order size or amount before partial closures."""
    quantity: Decimal | None = Field(default=None, alias="Quantity")
    """The current order size or amount."""
    realised_pnl: Decimal | None = Field(default=None, alias="RealisedPnl")
    """The realised profit and loss."""
    realised_pnl_currency: str | None = Field(default=None, alias="RealisedPnlCurrency")
    """The currency of the realised profit and loss."""
    last_changed_date_time_utc: StoneXDateTime | None = Field(
        default=None, alias="LastChangedDateTimeUTC"
    )
    """
    Represents the date and time when the order was last changed. Note: does not include
    things such as the current market price.
    """
    executed_date_time_utc: StoneXDateTime | None = Field(default=None, alias="ExecutedDateTimeUTC")
    """Represents the date and time when the order was executed."""


ApiManagedTradeHistoryDTO.model_rebuild(raise_errors=False)
