# GENERATED by stonepy._generator. Do not edit by hand.
"""Contains market information to be modified and saved."""

from __future__ import annotations

from decimal import Decimal

from pydantic import Field

from stonepy._core.models import ResponseModel


class ApiMarketInformationSaveDTO(ResponseModel):
    """Contains market information to be modified and saved."""

    market_id: int | None = Field(default=None, alias="MarketId")
    """The ID of the market to be modified."""
    price_tolerance: Decimal | None = Field(default=None, alias="PriceTolerance")
    """Setting to indicate the user's price tolerance for the given market."""
    price_tolerance_is_dirty: bool | None = Field(default=None, alias="PriceToleranceIsDirty")
    """Flag to indicate if the price tolerance value has changed."""
    margin_factor: Decimal | None = Field(default=None, alias="MarginFactor")
    """The user's margin factor for the given market."""
    margin_factor_is_dirty: bool | None = Field(default=None, alias="MarginFactorIsDirty")
    """Flag to indicate if the margin factor value has changed."""


ApiMarketInformationSaveDTO.model_rebuild(raise_errors=False)
