# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ApiManagedClientAccountMarginResponseDTO import ApiManagedClientAccountMarginResponseDTO


class ApiManagedClientAccountsMarginResponseDTO(ResponseModel):
    client_accounts_margin: list[ApiManagedClientAccountMarginResponseDTO] | None = Field(
        default=None, alias="ClientAccountsMargin"
    )


ApiManagedClientAccountsMarginResponseDTO.model_rebuild(raise_errors=False)
