# GENERATED by stonepy._generator. Do not edit by hand.
"""
The response details of each managed instruction that was automatically created and processed
as part of a Trading Advisor's instruction.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ApiOrderResponseDTO import ApiOrderResponseDTO


class ApiManagedInstructionResponseDTO(ResponseModel):
    """
    The response details of each managed instruction that was automatically created and
    processed as part of a Trading Advisor's instruction.
    """

    managed_trading_account_id: int | None = Field(default=None, alias="ManagedTradingAccountId")
    """The ID for the managed trading account for which the instruction was placed."""
    status: int | None = Field(default=None, alias="Status")
    """The instruction status. The table of lookup codes can be found at Lookup Values ."""
    status_reason: int | None = Field(default=None, alias="StatusReason")
    """The instruction status reason. The table of lookup codes can be found at Lookup Values ."""
    orders: list[ApiOrderResponseDTO] | None = Field(default=None, alias="Orders")
    """The list of order requests placed by the Trading Advisor for the managed account."""


ApiManagedInstructionResponseDTO.model_rebuild(raise_errors=False)
