# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ApiOrderResponseDTO import ApiOrderResponseDTO


class ApiManagedInstructionResponseDTO(ResponseModel):
    managed_trading_account_id: int | None = Field(default=None, alias="ManagedTradingAccountId")
    status: int | None = Field(default=None, alias="Status")
    status_reason: int | None = Field(default=None, alias="StatusReason")
    orders: list[ApiOrderResponseDTO] | None = Field(default=None, alias="Orders")


ApiManagedInstructionResponseDTO.model_rebuild(raise_errors=False)
