# GENERATED by stonepy._generator. Do not edit by hand.
"""Basic information about a Market."""

from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class ApiMarketDTO(ResponseModel):
    """Basic information about a Market."""

    market_id: int | None = Field(default=None, alias="MarketId")
    """A market's unique identifier."""
    name: str | None = Field(default=None, alias="Name")
    """The market name."""
    weighting: int | None = Field(default=None, alias="Weighting")
    """
    Weighting of the market between 0 and 1000 inclusive. Relays the priority of the market in
    the market search results. The higher the value the more prominent the market should
    appear.
    """


ApiMarketDTO.model_rebuild(raise_errors=False)
