# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class ApiManagedClientAccountMarginResponseDTO(ResponseModel):
    client_account_id: int | None = Field(default=None, alias="ClientAccountId")


ApiManagedClientAccountMarginResponseDTO.model_rebuild(raise_errors=False)
