# GENERATED by stonepy._generator. Do not edit by hand.
"""Response to an order request."""

from __future__ import annotations

from decimal import Decimal
from typing import overload

from pydantic import Field

from stonepy._core.models import ResponseModel

class ApiOrderActionResponseDTO(ResponseModel):
    """Response to an order request."""

    actioned_order_id: int | None = Field(default=None, alias="ActionedOrderId")
    """Actioned Order ID."""
    actioning_order_id: int | None = Field(default=None, alias="ActioningOrderId")
    """Actioning Order ID."""
    quantity: Decimal | None = Field(default=None, alias="Quantity")
    """Quantity."""
    profit_and_loss: Decimal | None = Field(default=None, alias="ProfitAndLoss")
    """Profit or Loss."""
    profit_and_loss_currency: str | None = Field(default=None, alias="ProfitAndLossCurrency")
    """Profit or Loss Currency."""
    order_action_type_id: int | None = Field(default=None, alias="OrderActionTypeId")
    """
    Indicates the action performed by the order, for example: partial close, fully close and
    so on. The table of lookup codes can be found at API Code Lookup Values .
    """

    @overload
    def __init__(
        self,
        *,
        ActionedOrderId: int | None = ...,
        ActioningOrderId: int | None = ...,
        Quantity: Decimal | None = ...,
        ProfitAndLoss: Decimal | None = ...,
        ProfitAndLossCurrency: str | None = ...,
        OrderActionTypeId: int | None = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        *,
        actioned_order_id: int | None = ...,
        actioning_order_id: int | None = ...,
        quantity: Decimal | None = ...,
        profit_and_loss: Decimal | None = ...,
        profit_and_loss_currency: str | None = ...,
        order_action_type_id: int | None = ...,
    ) -> None: ...
