# GENERATED by stonepy._generator. Do not edit by hand.
"""Represents an order."""

from __future__ import annotations

from decimal import Decimal
from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel, StoneXDateTime

if TYPE_CHECKING:
    from .ApiAssociatedDTOv2 import ApiAssociatedDTOv2
    from .ApiIfDoneDTOv2 import ApiIfDoneDTOv2
    from .ApiStopLimitOrderDTOv2 import ApiStopLimitOrderDTOv2


class ApiOrderDTOv2(ResponseModel):
    """Represents an order."""

    order_id: int | None = Field(default=None, alias="OrderId")
    """The order identifier"""
    reference: str | None = Field(default=None, alias="Reference")
    """Reference identifier for the instruction"""
    order_reference: str | None = Field(default=None, alias="OrderReference")
    """Reference identifier for the order"""
    market_id: int | None = Field(default=None, alias="MarketId")
    """A market's unique identifier"""
    direction: str | None = Field(default=None, alias="Direction")
    """Direction identifier for trade, values supported are Buy or Sell"""
    quantity: Decimal | None = Field(default=None, alias="Quantity")
    """The current size of the order"""
    original_quantity: Decimal | None = Field(default=None, alias="OriginalQuantity")
    """The original size of the order before user modification"""
    price: Decimal | None = Field(default=None, alias="Price")
    """The currently set price at which the order is triggered"""
    original_price: Decimal | None = Field(default=None, alias="OriginalPrice")
    """The original price to trigger the order before user modification"""
    trading_account_id: int | None = Field(default=None, alias="TradingAccountId")
    """The ID of the Trading Account associated with the order"""
    currency_id: int | None = Field(default=None, alias="CurrencyId")
    """Currency ID for order (as represented in the trading system)"""
    status_id: int | None = Field(default=None, alias="StatusId")
    """
    Status ID of order (as represented in the trading system) . The table of lookup codes can
    be found at Lookup Values
    """
    type_id: int | None = Field(default=None, alias="TypeId")
    """
    The type of the order: trade, stop or limit. The table of lookup codes can be found at
    Lookup Values
    """
    if_done: list[ApiIfDoneDTOv2] | None = Field(default=None, alias="IfDone")
    """List of If/Done Orders which will be filled when the initial order is triggered"""
    oco_order: ApiStopLimitOrderDTOv2 | None = Field(default=None, alias="OcoOrder")
    """Corresponding OCO Order (One Cancels the Other)"""
    auto_rollover: bool | None = Field(default=None, alias="AutoRollover")
    """
    Flag to indicate whether the trade will automatically roll into the next contract when the
    current contract expires. Only applies to markets where the underlying is a futures
    contract
    """
    last_changed_date_time_utc: StoneXDateTime | None = Field(
        default=None, alias="LastChangedDateTimeUTC"
    )
    """The date and time when the order was last changed, or executed"""
    allocation_profile_id: int | None = Field(default=None, alias="AllocationProfileId")
    """Allocation profile identifier"""
    allocation_profile_name: str | None = Field(default=None, alias="AllocationProfileName")
    """Allocation profile name"""
    source: str | None = Field(default=None, alias="Source")
    """Source"""
    executed_date_time_utc: StoneXDateTime | None = Field(default=None, alias="ExecutedDateTimeUTC")
    """The date and time when the order was executed"""
    associated_orders: ApiAssociatedDTOv2 | None = Field(default=None, alias="AssociatedOrders")
    """
    Any associated orders linked to this one. An associated order is linked to a net position
    rather than to specific individual trades
    """
    position_method_id: int | None = Field(default=None, alias="PositionMethodId")
    """Position method identifier"""
    realized_pnl: Decimal | None = Field(default=None, alias="RealizedPNL")
    """Realized PnL"""
    knock_out_level: Decimal | None = Field(default=None, alias="KnockOutLevel")
    """Knockout level"""


ApiOrderDTOv2.model_rebuild(raise_errors=False)
