# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from decimal import Decimal
from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel, StoneXDateTime

if TYPE_CHECKING:
    from .ApiAssociatedDTOv2 import ApiAssociatedDTOv2
    from .ApiBasicStopLimitOrderDTO import ApiBasicStopLimitOrderDTO
    from .ApiManagedTradeDTO import ApiManagedTradeDTO


class ApiOpenPositionDTOv2(ResponseModel):
    order_id: int | None = Field(default=None, alias="OrderId")
    market_id: int | None = Field(default=None, alias="MarketId")
    market_name: str | None = Field(default=None, alias="MarketName")
    direction: str | None = Field(default=None, alias="Direction")
    qauantity: Decimal | None = Field(default=None, alias="Qauantity")
    trigger_price: Decimal | None = Field(default=None, alias="TriggerPrice")
    trading_account_id: int | None = Field(default=None, alias="TradingAccountId")
    currency: str | None = Field(default=None, alias="Currency")
    status: int | None = Field(default=None, alias="Status")
    stop_order: ApiBasicStopLimitOrderDTO | None = Field(default=None, alias="StopOrder")
    limit_order: ApiBasicStopLimitOrderDTO | None = Field(default=None, alias="LimitOrder")
    last_changed_date_time_utc: StoneXDateTime | None = Field(
        default=None, alias="LastChangedDateTimeUTC"
    )
    created_date_time_utc: StoneXDateTime | None = Field(default=None, alias="CreatedDateTimeUTC")
    executed_date_time_utc: StoneXDateTime | None = Field(default=None, alias="ExecutedDateTimeUTC")
    auto_rollover: bool | None = Field(default=None, alias="AutoRollover")
    trade_reference: str | None = Field(default=None, alias="TradeReference")
    managed_trades: list[ApiManagedTradeDTO] | None = Field(default=None, alias="ManagedTrades")
    allocation_profile_id: int | None = Field(default=None, alias="AllocationProfileId")
    allocation_profile_name: str | None = Field(default=None, alias="AllocationProfileName")
    associated_orders: ApiAssociatedDTOv2 | None = Field(default=None, alias="AssociatedOrders")
    fixed_initial_margin: Decimal | None = Field(default=None, alias="FixedInitialMargin")
    position_method_id: int | None = Field(default=None, alias="PositionMethodId")


ApiOpenPositionDTOv2.model_rebuild(raise_errors=False)
