# GENERATED by stonepy._generator. Do not edit by hand.
"""-"""

from __future__ import annotations

from decimal import Decimal
from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel, StoneXDateTime

if TYPE_CHECKING:
    from .ApiMarketSpreadDTO import ApiMarketSpreadDTO
    from .ApiStepMarginBandDTO import ApiStepMarginBandDTO


class ApiProductInformationDTO(ResponseModel):
    """-"""

    market_id: int | None = Field(default=None, alias="MarketId")
    """Market identifier"""
    market_name: str | None = Field(default=None, alias="MarketName")
    """Market name"""
    mobile_short_name: str | None = Field(default=None, alias="MobileShortName")
    """Mobile short market name"""
    minimum_spread: Decimal | None = Field(default=None, alias="MinimumSpread")
    """Minimum spread"""
    minimum_spread_time_utc: StoneXDateTime | None = Field(
        default=None, alias="MinimumSpreadTimeUtc"
    )
    """Minimum spread time"""
    additional_market_spreads: list[ApiMarketSpreadDTO] | None = Field(
        default=None, alias="AdditionalMarketSpreads"
    )
    """List of market spreads"""
    minimum_margin: Decimal | None = Field(default=None, alias="MinimumMargin")
    """Minimum margin"""
    bands: list[ApiStepMarginBandDTO] | None = Field(default=None, alias="Bands")
    """List of step margin bands"""
    market24_h: bool | None = Field(default=None, alias="Market24H")
    """Flag to determine if the market is tradeable 24 hours"""
    trading_start_time_utc: StoneXDateTime | None = Field(default=None, alias="TradingStartTimeUtc")
    """Market Trading start time on each trading day represented in UTC and local time"""
    trading_end_time_utc: StoneXDateTime | None = Field(default=None, alias="TradingEndTimeUtc")
    """Market Trading end time on each trading day represented in UTC and local time"""
    bet_per: Decimal | None = Field(default=None, alias="BetPer")
    """Bet Per value for CFD and Spread Bet markets"""
    expiry_utc: StoneXDateTime | None = Field(default=None, alias="ExpiryUtc")
    """Expiry of the market in UTC"""
    min_stop_distance: Decimal | None = Field(default=None, alias="MinStopDistance")
    """Minimum stop distance"""
    guaranteed_order_min_distance: Decimal | None = Field(
        default=None, alias="GuaranteedOrderMinDistance"
    )
    """The minimum distance from current market price at which a guaranteed order can be placed"""
    currency_id: int | None = Field(default=None, alias="CurrencyId")
    """The currency being traded"""
    currency_iso_code: str | None = Field(default=None, alias="CurrencyIsoCode")
    """The currency ISO code"""
    market_underlying_type: str | None = Field(default=None, alias="MarketUnderlyingType")
    """Reflects the market underlying type description of the associated market"""
    price_decimal_places: int | None = Field(default=None, alias="PriceDecimalPlaces")
    """The number of decimal places in the market's price"""
    max_size: Decimal | None = Field(default=None, alias="MaxSize")
    """The max size of an order"""
    web_min_size: Decimal | None = Field(default=None, alias="WebMinSize")
    """The minimum quantity that can be traded over the web"""
    phone_min_size: Decimal | None = Field(default=None, alias="PhoneMinSize")
    """The minimum quantity that can be traded over the Phone"""
    market_time_zone_offset_minutes: int | None = Field(
        default=None, alias="MarketTimeZoneOffsetMinutes"
    )
    """Offset minutes to convert UTC times to local times"""


ApiProductInformationDTO.model_rebuild(raise_errors=False)
