# GENERATED by stonepy._generator. Do not edit by hand.
"""Market tag information extended to include a list of child tags."""

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ApiMarketTagDTO import ApiMarketTagDTO


class ApiPrimaryMarketTagDTO(ResponseModel):
    """Market tag information extended to include a list of child tags."""

    children: list[ApiMarketTagDTO] | None = Field(default=None, alias="Children")
    """The list of child tags associated with this market tag"""


ApiPrimaryMarketTagDTO.model_rebuild(raise_errors=False)
