# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ApiMarketTagDTO import ApiMarketTagDTO


class ApiPrimaryMarketTagDTO(ResponseModel):
    children: list[ApiMarketTagDTO] | None = Field(default=None, alias="Children")


ApiPrimaryMarketTagDTO.model_rebuild(raise_errors=False)
