# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from decimal import Decimal
from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel, StoneXDateTime

if TYPE_CHECKING:
    from .ApiMarketSpreadDTO import ApiMarketSpreadDTO
    from .ApiStepMarginBandDTO import ApiStepMarginBandDTO


class ApiProductInformationDTO(ResponseModel):
    market_id: int | None = Field(default=None, alias="MarketId")
    market_name: str | None = Field(default=None, alias="MarketName")
    mobile_short_name: str | None = Field(default=None, alias="MobileShortName")
    minimum_spread: Decimal | None = Field(default=None, alias="MinimumSpread")
    minimum_spread_time_utc: StoneXDateTime | None = Field(
        default=None, alias="MinimumSpreadTimeUtc"
    )
    additional_market_spreads: list[ApiMarketSpreadDTO] | None = Field(
        default=None, alias="AdditionalMarketSpreads"
    )
    minimum_margin: Decimal | None = Field(default=None, alias="MinimumMargin")
    bands: list[ApiStepMarginBandDTO] | None = Field(default=None, alias="Bands")
    market24_h: bool | None = Field(default=None, alias="Market24H")
    trading_start_time_utc: StoneXDateTime | None = Field(default=None, alias="TradingStartTimeUtc")
    trading_end_time_utc: StoneXDateTime | None = Field(default=None, alias="TradingEndTimeUtc")
    bet_per: Decimal | None = Field(default=None, alias="BetPer")
    expiry_utc: StoneXDateTime | None = Field(default=None, alias="ExpiryUtc")
    min_stop_distance: Decimal | None = Field(default=None, alias="MinStopDistance")
    guaranteed_order_min_distance: Decimal | None = Field(
        default=None, alias="GuaranteedOrderMinDistance"
    )
    currency_id: int | None = Field(default=None, alias="CurrencyId")
    currency_iso_code: str | None = Field(default=None, alias="CurrencyIsoCode")
    market_underlying_type: str | None = Field(default=None, alias="MarketUnderlyingType")
    price_decimal_places: int | None = Field(default=None, alias="PriceDecimalPlaces")
    max_size: Decimal | None = Field(default=None, alias="MaxSize")
    web_min_size: Decimal | None = Field(default=None, alias="WebMinSize")
    phone_min_size: Decimal | None = Field(default=None, alias="PhoneMinSize")
    market_time_zone_offset_minutes: int | None = Field(
        default=None, alias="MarketTimeZoneOffsetMinutes"
    )


ApiProductInformationDTO.model_rebuild(raise_errors=False)
