# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class ApiQuoteResponseDTO(ResponseModel):
    quote_id: int | None = Field(default=None, alias="QuoteId")
    status: int | None = Field(default=None, alias="Status")
    status_reason: int | None = Field(default=None, alias="StatusReason")


ApiQuoteResponseDTO.model_rebuild(raise_errors=False)
