# GENERATED by stonepy._generator. Do not edit by hand.
"""Quote response."""

from __future__ import annotations

from typing import overload

from pydantic import Field

from stonepy._core.models import ResponseModel

class ApiQuoteResponseDTO(ResponseModel):
    """Quote response."""

    quote_id: int | None = Field(default=None, alias="QuoteId")
    """Quote ID."""
    status: int | None = Field(default=None, alias="Status")
    """Quote status. The table of lookup codes can be found at Lookup Values ."""
    status_reason: int | None = Field(default=None, alias="StatusReason")
    """Quote status reason. The table of lookup codes can be found at Lookup Values ."""

    @overload
    def __init__(
        self,
        *,
        QuoteId: int | None = ...,
        Status: int | None = ...,
        StatusReason: int | None = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        *,
        quote_id: int | None = ...,
        status: int | None = ...,
        status_reason: int | None = ...,
    ) -> None: ...
