# GENERATED by stonepy._generator. Do not edit by hand.
"""Simulated order response."""

from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class ApiSimulateOrderResponseDTO(ResponseModel):
    """Simulated order response."""

    status_reason: int | None = Field(default=None, alias="StatusReason")
    """
    Simulated order status reason ID. The table of lookup codes can be found at Lookup Values
    .
    """
    status: int | None = Field(default=None, alias="Status")
    """Simulated order status ID. The table of lookup codes can be found at Lookup Values ."""


ApiSimulateOrderResponseDTO.model_rebuild(raise_errors=False)
