# GENERATED by stonepy._generator. Do not edit by hand.
"""Represents a single step margin band as expressed by the trading API."""

from __future__ import annotations

from decimal import Decimal
from typing import overload

from pydantic import Field

from stonepy._core.models import ResponseModel

class ApiStepMarginBandDTO(ResponseModel):
    """Represents a single step margin band as expressed by the trading API."""

    lower_bound: Decimal | None = Field(default=None, alias="LowerBound")
    """Minimum threshold for this band, expressed in terms of the client's trade quantity"""
    margin_factor: Decimal | None = Field(default=None, alias="MarginFactor")
    """
    The margin factor that is used for this band. It can be expressed as a percentage or in
    points based on the market's margin factor type
    """

    @overload
    def __init__(
        self,
        *,
        LowerBound: Decimal | None = ...,
        MarginFactor: Decimal | None = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        *,
        lower_bound: Decimal | None = ...,
        margin_factor: Decimal | None = ...,
    ) -> None: ...
