# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from stonepy._core.models import ResponseModel


class ApiSaveAccountInformationResponseDTO(ResponseModel):
    pass


ApiSaveAccountInformationResponseDTO.model_rebuild(raise_errors=False)
