# GENERATED by stonepy._generator. Do not edit by hand.
"""
All service calls and DTOs related to Predicted Markets are for internal StoneX use only. An
empty response to indicate that the SaveSignalPreferences operation has completed.
"""

from __future__ import annotations

from stonepy._core.models import ResponseModel


class ApiSaveSignalPreferencesResponseDTO(ResponseModel):
    """
    All service calls and DTOs related to Predicted Markets are for internal StoneX use only.
    An empty response to indicate that the SaveSignalPreferences operation has completed.
    """


ApiSaveSignalPreferencesResponseDTO.model_rebuild(raise_errors=False)
