# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from decimal import Decimal
from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ApiSimulateOrderResponseDTO import ApiSimulateOrderResponseDTO


class ApiSimulateTradeOrderResponseDTO(ResponseModel):
    status: int | None = Field(default=None, alias="Status")
    status_reason: int | None = Field(default=None, alias="StatusReason")
    simulated_cash: Decimal | None = Field(default=None, alias="SimulatedCash")
    actual_cash: Decimal | None = Field(default=None, alias="ActualCash")
    simulated_total_margin_requirement: Decimal | None = Field(
        default=None, alias="SimulatedTotalMarginRequirement"
    )
    actual_total_margin_requirement: Decimal | None = Field(
        default=None, alias="ActualTotalMarginRequirement"
    )
    currency_id: int | None = Field(default=None, alias="CurrencyId")
    orders: list[ApiSimulateOrderResponseDTO] | None = Field(default=None, alias="Orders")
    adjust: Decimal | None = Field(default=None, alias="Adjust")


ApiSimulateTradeOrderResponseDTO.model_rebuild(raise_errors=False)
