# GENERATED by stonepy._generator. Do not edit by hand.
"""List of preferences to save."""

from __future__ import annotations

from typing import TYPE_CHECKING, overload

from pydantic import Field

from stonepy._core.models import RequestModel

if TYPE_CHECKING:
    from .RequestPreferenceDTO import RequestPreferenceDTO

class ApiSavePreferencesRequestDTO(RequestModel):
    """List of preferences to save."""

    preferences: list[RequestPreferenceDTO] | None = Field(default=None, alias="Preferences")
    """List of user preferences"""

    @overload
    def __init__(
        self,
        *,
        Preferences: list[RequestPreferenceDTO] | None = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        *,
        preferences: list[RequestPreferenceDTO] | None = ...,
    ) -> None: ...
