# GENERATED by stonepy._generator. Do not edit by hand.
"""Simulated order response."""

from __future__ import annotations

from typing import overload

from pydantic import Field

from stonepy._core.models import ResponseModel

class ApiSimulateOrderResponseDTO(ResponseModel):
    """Simulated order response."""

    status_reason: int | None = Field(default=None, alias="StatusReason")
    """
    Simulated order status reason ID. The table of lookup codes can be found at Lookup Values
    .
    """
    status: int | None = Field(default=None, alias="Status")
    """Simulated order status ID. The table of lookup codes can be found at Lookup Values ."""

    @overload
    def __init__(
        self,
        *,
        StatusReason: int | None = ...,
        Status: int | None = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        *,
        status_reason: int | None = ...,
        status: int | None = ...,
    ) -> None: ...
