# GENERATED by stonepy._generator. Do not edit by hand.
"""Represents a stop/limit order."""

from __future__ import annotations

from decimal import Decimal

from pydantic import Field

from stonepy._core.models import ResponseModel, StoneXDateTime


class ApiStopLimitOrderDTOv2(ResponseModel):
    """Represents a stop/limit order."""

    guaranteed: bool | None = Field(default=None, alias="Guaranteed")
    """
    Flag to determine whether an order is guaranteed to trigger and fill at the associated
    trigger price
    """
    trigger_price: Decimal | None = Field(default=None, alias="TriggerPrice")
    """
    Price at which the order should be triggered. This is NULL if the order is a trailing stop
    and TrailingDistance is specified instead
    """
    expiry_date_time_utc: StoneXDateTime | None = Field(default=None, alias="ExpiryDateTimeUTC")
    """
    The associated expiry DateTime for a pair of GoodTillDate If/Done orders defined in UNIX
    time format
    """
    applicability: str | None = Field(default=None, alias="Applicability")
    """
    Identifier which relates to the expiry of the order/trade, i.e. GoodTillDate (GTD),
    GoodTillCancelled (GTC) or GoodForDay (GFD)
    """
    parent_order_id: int | None = Field(default=None, alias="ParentOrderId")
    """
    This represents the OrderID of any orders that the current order is related to. If there
    is no parent order as the order in question is the parent order, then the value is NULL
    """
    trailing_distance: Decimal | None = Field(default=None, alias="TrailingDistance")
    """
    Used to set the trail distance in points for trailing stop orders. This is NULL if
    TriggerPrice is specified and it is not a trailing stop
    """
    associated: bool | None = Field(default=None, alias="Associated")
    """
    Flag to indicate if this is an associated order. An associated order is linked to a net
    position rather than to specific individual trades
    """
    trigger_level_calculation_type_id: int | None = Field(
        default=None, alias="TriggerLevelCalculationTypeId"
    )
    """Trigger level calculation type identifier"""
    trigger_level_calculation_value: Decimal | None = Field(
        default=None, alias="TriggerLevelCalculationValue"
    )
    """Trigger level calculation value"""


ApiStopLimitOrderDTOv2.model_rebuild(raise_errors=False)
