# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from decimal import Decimal

from pydantic import Field

from stonepy._core.models import ResponseModel


class ApiStepMarginBandDTO(ResponseModel):
    lower_bound: Decimal | None = Field(default=None, alias="LowerBound")
    margin_factor: Decimal | None = Field(default=None, alias="MarginFactor")


ApiStepMarginBandDTO.model_rebuild(raise_errors=False)
