# GENERATED by stonepy._generator. Do not edit by hand.
"""Request to save a watchlist."""

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ApiClientAccountWatchlistDTO import ApiClientAccountWatchlistDTO


class ApiSaveWatchlistRequestDTOv2(ResponseModel):
    """Request to save a watchlist."""

    client_account_id: int | None = Field(default=None, alias="ClientAccountId")
    """Client Account ID"""
    watchlist: ApiClientAccountWatchlistDTO | None = Field(default=None, alias="Watchlist")
    """
    The watchlist to save. This will update an existing watchlist; or when the watchlist ID is
    omitted or 0 is supplied, it will create a new watchlist.
    """


ApiSaveWatchlistRequestDTOv2.model_rebuild(raise_errors=False)
