# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from stonepy._core.models import ResponseModel


class ApiSaveWatchlistResponseDTO(ResponseModel):
    pass


ApiSaveWatchlistResponseDTO.model_rebuild(raise_errors=False)
