# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from decimal import Decimal

from pydantic import Field

from stonepy._core.models import ResponseModel, StoneXDateTime


class ApiStopLimitOrderHistoryDTO(ResponseModel):
    order_id: int | None = Field(default=None, alias="OrderId")
    market_id: int | None = Field(default=None, alias="MarketId")
    market_name: str | None = Field(default=None, alias="MarketName")
    direction: str | None = Field(default=None, alias="Direction")
    original_quantity: Decimal | None = Field(default=None, alias="OriginalQuantity")
    price: Decimal | None = Field(default=None, alias="Price")
    trigger_price: Decimal | None = Field(default=None, alias="TriggerPrice")
    trailing_distance: Decimal | None = Field(default=None, alias="TrailingDistance")
    trading_account_id: int | None = Field(default=None, alias="TradingAccountId")
    type_id: int | None = Field(default=None, alias="TypeId")
    order_applicability_id: int | None = Field(default=None, alias="OrderApplicabilityId")
    currency: str | None = Field(default=None, alias="Currency")
    status_id: int | None = Field(default=None, alias="StatusId")
    last_changed_date_time_utc: StoneXDateTime | None = Field(
        default=None, alias="LastChangedDateTimeUtc"
    )
    created_date_time_utc: StoneXDateTime | None = Field(default=None, alias="CreatedDateTimeUtc")
    guaranteed: bool | None = Field(default=None, alias="Guaranteed")
    trade_reference: str | None = Field(default=None, alias="TradeReference")
    order_reference: str | None = Field(default=None, alias="OrderReference")
    source: str | None = Field(default=None, alias="Source")


ApiStopLimitOrderHistoryDTO.model_rebuild(raise_errors=False)
