# GENERATED by stonepy._generator. Do not edit by hand.
"""
Details of a CI Connect user that was involved in a community action. Note: for use of the CI
Connect social trading platform.
"""

from __future__ import annotations

from typing import overload

from pydantic import Field

from stonepy._core.models import ResponseModel, StoneXDateTime

class ApiTraderDetailsDTO(ResponseModel):
    """
    Details of a CI Connect user that was involved in a community action. Note: for use of the
    CI Connect social trading platform.
    """

    client_account_id: int | None = Field(default=None, alias="ClientAccountId")
    """The client account ID associated with the CI Connect user."""
    screen_name: str | None = Field(default=None, alias="ScreenName")
    """The CI Connect screen/user name."""
    number_of_followers: int | None = Field(default=None, alias="NumberOfFollowers")
    """The number of other CI Connect users following this trader."""
    average_trade_length: int | None = Field(default=None, alias="AverageTradeLength")
    """The current average trade length (in seconds) for this user."""
    avatar_url: str | None = Field(default=None, alias="AvatarUrl")
    """The URL path to the image file used as the graphic avatar for this CI Connect user."""
    last_traded_market_underlying_type: str | None = Field(
        default=None, alias="LastTradedMarketUnderlyingType"
    )
    """
    Description of the market type. This can be 'Option Market', 'Ordinary Market', or 'Binary
    Market'.
    """
    last_traded_market_id: int | None = Field(default=None, alias="LastTradedMarketId")
    """The unique identifier for the last market traded by the user."""
    last_traded_market: str | None = Field(default=None, alias="LastTradedMarket")
    """The name of the last traded market."""
    date_last_trade_placed: StoneXDateTime | None = Field(default=None, alias="DateLastTradePlaced")
    """The date and time of the last trade placed by this user."""
    number_of_traders_followed: int | None = Field(default=None, alias="NumberOfTradersFollowed")
    """The number of other CI Connect users following this trader."""
    is_following: bool | None = Field(default=None, alias="IsFollowing")
    """Boolean true/false flag indicating if this trader is following the viewing user."""

    @overload
    def __init__(
        self,
        *,
        ClientAccountId: int | None = ...,
        ScreenName: str | None = ...,
        NumberOfFollowers: int | None = ...,
        AverageTradeLength: int | None = ...,
        AvatarUrl: str | None = ...,
        LastTradedMarketUnderlyingType: str | None = ...,
        LastTradedMarketId: int | None = ...,
        LastTradedMarket: str | None = ...,
        DateLastTradePlaced: StoneXDateTime | None = ...,
        NumberOfTradersFollowed: int | None = ...,
        IsFollowing: bool | None = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        *,
        client_account_id: int | None = ...,
        screen_name: str | None = ...,
        number_of_followers: int | None = ...,
        average_trade_length: int | None = ...,
        avatar_url: str | None = ...,
        last_traded_market_underlying_type: str | None = ...,
        last_traded_market_id: int | None = ...,
        last_traded_market: str | None = ...,
        date_last_trade_placed: StoneXDateTime | None = ...,
        number_of_traders_followed: int | None = ...,
        is_following: bool | None = ...,
    ) -> None: ...
