# GENERATED by stonepy._generator. Do not edit by hand.
"""Information about a Trading Account."""

from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class ApiTradingAccountDTOv2(ResponseModel):
    """Information about a Trading Account."""

    client_account_id: int | None = Field(default=None, alias="ClientAccountId")
    """Client account identifier"""
    trading_account_id: int | None = Field(default=None, alias="TradingAccountId")
    """Trading account identifier"""
    trading_account_code: str | None = Field(default=None, alias="TradingAccountCode")
    """Trading account code"""
    trading_account_status: str | None = Field(default=None, alias="TradingAccountStatus")
    """Trading account status with possible values (Open, Closed)"""
    trading_account_type: str | None = Field(default=None, alias="TradingAccountType")
    """Trading account type with possible values (Spread, CFD)"""
    trading_account_name: str | None = Field(default=None, alias="TradingAccountName")
    """Trading account name."""


ApiTradingAccountDTOv2.model_rebuild(raise_errors=False)
