# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ApiOrderActionResponseDTO import ApiOrderActionResponseDTO
    from .ApiOrderResponseDTO import ApiOrderResponseDTO
    from .ApiQuoteResponseDTO import ApiQuoteResponseDTO


class ApiTradeOrderResponseDTO(ResponseModel):
    status: int | None = Field(default=None, alias="Status")
    status_reason: int | None = Field(default=None, alias="StatusReason")
    order_id: int | None = Field(default=None, alias="OrderId")
    orders: list[ApiOrderResponseDTO] | None = Field(default=None, alias="Orders")
    quote: ApiQuoteResponseDTO | None = Field(default=None, alias="Quote")
    actions: list[ApiOrderActionResponseDTO] | None = Field(default=None, alias="Actions")
    error_message: str | None = Field(default=None, alias="ErrorMessage")


ApiTradeOrderResponseDTO.model_rebuild(raise_errors=False)
