# GENERATED by stonepy._generator. Do not edit by hand.
"""The response from the trade request."""

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ApiOrderActionResponseDTO import ApiOrderActionResponseDTO
    from .ApiOrderResponseDTO import ApiOrderResponseDTO
    from .ApiQuoteResponseDTO import ApiQuoteResponseDTO


class ApiTradeOrderResponseDTO(ResponseModel):
    """The response from the trade request."""

    status: int | None = Field(default=None, alias="Status")
    """
    The status of the order (Pending, Accepted, Open, etc.) . The table of lookup codes can be
    found at Lookup Values .
    """
    status_reason: int | None = Field(default=None, alias="StatusReason")
    """
    The ID corresponding to a more descriptive reason for the order status. The table of
    lookup codes can be found at Lookup Values .
    """
    order_id: int | None = Field(default=None, alias="OrderId")
    """The unique identifier associated to the order returned from the underlying trading system."""
    orders: list[ApiOrderResponseDTO] | None = Field(default=None, alias="Orders")
    """List of orders with their associated response."""
    quote: ApiQuoteResponseDTO | None = Field(default=None, alias="Quote")
    """Quote response."""
    actions: list[ApiOrderActionResponseDTO] | None = Field(default=None, alias="Actions")
    """List of order actions with their associated response."""
    error_message: str | None = Field(default=None, alias="ErrorMessage")
    """Contains the error message - this is only used when the Status = -1."""


ApiTradeOrderResponseDTO.model_rebuild(raise_errors=False)
