# GENERATED by stonepy._generator. Do not edit by hand.
"""The response from the trade request."""

from __future__ import annotations

from typing import TYPE_CHECKING, overload

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ApiOrderActionResponseDTO import ApiOrderActionResponseDTO
    from .ApiOrderResponseDTO import ApiOrderResponseDTO
    from .ApiQuoteResponseDTO import ApiQuoteResponseDTO

class ApiTradeOrderResponseDTO(ResponseModel):
    """The response from the trade request."""

    status: int | None = Field(default=None, alias="Status")
    """
    The status of the order (Pending, Accepted, Open, etc.) . The table of lookup codes can be
    found at Lookup Values .

    stonepy decodes this top-level value as InstructionStatus (Accepted=1, RedCard=2,
    YellowCard=3, Error=4, Pending=5), not OrderStatus; the nested Orders[].Status values are
    OrderStatus lifecycle codes.
    """
    status_reason: int | None = Field(default=None, alias="StatusReason")
    """
    The ID corresponding to a more descriptive reason for the order status. The table of
    lookup codes can be found at Lookup Values .
    """
    order_id: int | None = Field(default=None, alias="OrderId")
    """The unique identifier associated to the order returned from the underlying trading system."""
    orders: list[ApiOrderResponseDTO] | None = Field(default=None, alias="Orders")
    """List of orders with their associated response."""
    quote: ApiQuoteResponseDTO | None = Field(default=None, alias="Quote")
    """Quote response."""
    actions: list[ApiOrderActionResponseDTO] | None = Field(default=None, alias="Actions")
    """List of order actions with their associated response."""
    error_message: str | None = Field(default=None, alias="ErrorMessage")
    """Contains the error message - this is only used when the Status = -1."""

    @overload
    def __init__(
        self,
        *,
        Status: int | None = ...,
        StatusReason: int | None = ...,
        OrderId: int | None = ...,
        Orders: list[ApiOrderResponseDTO] | None = ...,
        Quote: ApiQuoteResponseDTO | None = ...,
        Actions: list[ApiOrderActionResponseDTO] | None = ...,
        ErrorMessage: str | None = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        *,
        status: int | None = ...,
        status_reason: int | None = ...,
        order_id: int | None = ...,
        orders: list[ApiOrderResponseDTO] | None = ...,
        quote: ApiQuoteResponseDTO | None = ...,
        actions: list[ApiOrderActionResponseDTO] | None = ...,
        error_message: str | None = ...,
    ) -> None: ...
