# GENERATED by stonepy._generator. Do not edit by hand.
"""
List entry for GetAllTradesWallResponseDTO . Contains information about the trades executed by
CI Connect members.
"""

from __future__ import annotations

from decimal import Decimal

from pydantic import Field

from stonepy._core.models import ResponseModel, StoneXDateTime


class ApiTradeActionDTO(ResponseModel):
    """
    List entry for GetAllTradesWallResponseDTO . Contains information about the trades
    executed by CI Connect members.
    """

    trade_action_id: int | None = Field(default=None, alias="TradeActionId")
    """Identifier that uniquely identifies the trade action."""
    order_id: int | None = Field(default=None, alias="OrderId")
    """The order identifier."""
    direction: str | None = Field(default=None, alias="Direction")
    """Direction of the executed order: Buy or Sell ."""
    quantity: Decimal | None = Field(default=None, alias="Quantity")
    """The size or amount of the executed order."""
    price: Decimal | None = Field(default=None, alias="Price")
    """The price at which the trade/order was executed."""
    trade_type: str | None = Field(default=None, alias="TradeType")
    """The type of trade: Open , Full Close , Part Close ."""
    market_id: int | None = Field(default=None, alias="MarketID")
    """Identifier of the market that was traded."""
    market_name: str | None = Field(default=None, alias="MarketName")
    """The name of the traded market."""
    market_type: str | None = Field(default=None, alias="MarketType")
    """Type of the market traded: Spread , CFD , Option etc."""
    last_changed_date_time_utc: StoneXDateTime | None = Field(
        default=None, alias="LastChangedDateTimeUTC"
    )
    """
    Represents the date and time when the order was last changed. Note: does not include
    things such as the current market price.
    """
    client_id: int | None = Field(default=None, alias="ClientID")
    """The user's account identifier."""
    avatar: str | None = Field(default=None, alias="Avatar")
    """The URL path to the image file used as the graphic avatar for the CI Connect member."""
    facebook_id: str | None = Field(default=None, alias="FacebookID")
    """The user's Facebook identifier."""
    screen_name: str | None = Field(default=None, alias="ScreenName")
    """The registered CI Connect display username."""
    first_name: str | None = Field(default=None, alias="FirstName")
    """First name od the user who made the trade."""
    last_name: str | None = Field(default=None, alias="LastName")
    """Surname of the user who made the trade."""
    roi: Decimal | None = Field(default=None, alias="ROI")
    """The return on investment for closing trades."""


ApiTradeActionDTO.model_rebuild(raise_errors=False)
