# GENERATED by stonepy._generator. Do not edit by hand.
"""
List entry for ApiListTopholdersDTO . Contains the CI Connect details for an individual top
holder user. Note: only users registered with CI Connect are returned.
"""

from __future__ import annotations

from decimal import Decimal
from typing import overload

from pydantic import Field

from stonepy._core.models import ResponseModel

class ApiTopholderDTO(ResponseModel):
    """
    List entry for ApiListTopholdersDTO . Contains the CI Connect details for an individual
    top holder user. Note: only users registered with CI Connect are returned.
    """

    screen_name: str | None = Field(default=None, alias="ScreenName")
    """The registered CI Connect display username of the top holder."""
    avatar: str | None = Field(default=None, alias="Avatar")
    """The URL path to the image file used as the graphic avatar for this CI Connect top holder."""
    quantity: Decimal | None = Field(default=None, alias="Quantity")
    """The position size in the market for this top holder."""
    direction: str | None = Field(default=None, alias="Direction")
    """The trade direction for this top holder: Buy or Sell ."""

    @overload
    def __init__(
        self,
        *,
        ScreenName: str | None = ...,
        Avatar: str | None = ...,
        Quantity: Decimal | None = ...,
        Direction: str | None = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        *,
        screen_name: str | None = ...,
        avatar: str | None = ...,
        quantity: Decimal | None = ...,
        direction: str | None = ...,
    ) -> None: ...
