# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel, StoneXDateTime


class ApiTraderDetailsDTO(ResponseModel):
    client_account_id: int | None = Field(default=None, alias="ClientAccountId")
    screen_name: str | None = Field(default=None, alias="ScreenName")
    number_of_followers: int | None = Field(default=None, alias="NumberOfFollowers")
    average_trade_length: int | None = Field(default=None, alias="AverageTradeLength")
    avatar_url: str | None = Field(default=None, alias="AvatarUrl")
    last_traded_market_underlying_type: str | None = Field(
        default=None, alias="LastTradedMarketUnderlyingType"
    )
    last_traded_market_id: int | None = Field(default=None, alias="LastTradedMarketId")
    last_traded_market: str | None = Field(default=None, alias="LastTradedMarket")
    date_last_trade_placed: StoneXDateTime | None = Field(default=None, alias="DateLastTradePlaced")
    number_of_traders_followed: int | None = Field(default=None, alias="NumberOfTradersFollowed")
    is_following: bool | None = Field(default=None, alias="IsFollowing")


ApiTraderDetailsDTO.model_rebuild(raise_errors=False)
