# GENERATED by stonepy._generator. Do not edit by hand.
"""
List entry for ApiListLatestTradedMarketsResponseDTO . Represents the markets traded by the CI
Connect users.
"""

from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class ApiTradedMarketsDTO(ResponseModel):
    """
    List entry for ApiListLatestTradedMarketsResponseDTO . Represents the markets traded by
    the CI Connect users.
    """

    screen_name: str | None = Field(default=None, alias="ScreenName")
    """The CI connect user screen name."""
    market_ids: list[int] | None = Field(default=None, alias="MarketIds")
    """The list of market IDs for markets traded by this user."""


ApiTradedMarketsDTO.model_rebuild(raise_errors=False)
