# GENERATED by stonepy._generator. Do not edit by hand.
"""Details of a previous trade for use in the Trade History."""

from __future__ import annotations

from decimal import Decimal
from typing import TYPE_CHECKING, overload

from pydantic import Field

from stonepy._core.models import ResponseModel, StoneXDateTime

if TYPE_CHECKING:
    from .ApiManagedTradeHistoryDTO import ApiManagedTradeHistoryDTO

class ApiTradeHistoryDTO(ResponseModel):
    """Details of a previous trade for use in the Trade History."""

    order_id: int | None = Field(default=None, alias="OrderId")
    """The order ID."""
    opening_order_ids: list[int] | None = Field(default=None, alias="OpeningOrderIds")
    """The orders that are being closed / part closed by this order."""
    market_id: int | None = Field(default=None, alias="MarketId")
    """The market ID."""
    market_name: str | None = Field(default=None, alias="MarketName")
    """The name of the market."""
    direction: str | None = Field(default=None, alias="Direction")
    """The direction of the trade, Buy or Sell ."""
    original_quantity: Decimal | None = Field(default=None, alias="OriginalQuantity")
    """The original quantity of the trade, before part closures."""
    quantity: Decimal | None = Field(default=None, alias="Quantity")
    """The current quantity of the trade."""
    price: Decimal | None = Field(default=None, alias="Price")
    """The open price of the trade."""
    trading_account_id: int | None = Field(default=None, alias="TradingAccountId")
    """The Trading Account ID that the order is on."""
    currency: str | None = Field(default=None, alias="Currency")
    """The trade currency."""
    realised_pnl: Decimal | None = Field(default=None, alias="RealisedPnl")
    """The realised profit and loss (P&L)."""
    realised_pnl_currency: str | None = Field(default=None, alias="RealisedPnlCurrency")
    """The realised P&L currency."""
    last_changed_date_time_utc: StoneXDateTime | None = Field(
        default=None, alias="LastChangedDateTimeUtc"
    )
    """
    Represents the date and time when the trade/order was last edited. Note: does not include
    things such as the current market price.
    """
    executed_date_time_utc: StoneXDateTime | None = Field(default=None, alias="ExecutedDateTimeUtc")
    """The time that the order was executed."""
    trade_reference: str | None = Field(default=None, alias="TradeReference")
    """An alternative trade reference."""
    managed_trades: list[ApiManagedTradeHistoryDTO] | None = Field(
        default=None, alias="ManagedTrades"
    )
    """The list of constituent trades for Trading Advisor managed positions (if applicable) ."""
    order_reference: str | None = Field(default=None, alias="OrderReference")
    """The order reference for this trade."""
    source: str | None = Field(default=None, alias="Source")
    """The source for this trade i.e. FIX/MT4/G2."""
    is_close_by: bool | None = Field(default=None, alias="IsCloseBy")
    """Flag to indicate if this order was closed or used to close another order."""
    liquidation: bool | None = Field(default=None, alias="Liquidation")
    """Flag to indicate if this order was placed to liquidate a position."""
    fixed_initial_margin: Decimal | None = Field(default=None, alias="FixedInitialMargin")
    """The fixed amount of trading resources used to place the trade."""

    @overload
    def __init__(
        self,
        *,
        OrderId: int | None = ...,
        OpeningOrderIds: list[int] | None = ...,
        MarketId: int | None = ...,
        MarketName: str | None = ...,
        Direction: str | None = ...,
        OriginalQuantity: Decimal | None = ...,
        Quantity: Decimal | None = ...,
        Price: Decimal | None = ...,
        TradingAccountId: int | None = ...,
        Currency: str | None = ...,
        RealisedPnl: Decimal | None = ...,
        RealisedPnlCurrency: str | None = ...,
        LastChangedDateTimeUtc: StoneXDateTime | None = ...,
        ExecutedDateTimeUtc: StoneXDateTime | None = ...,
        TradeReference: str | None = ...,
        ManagedTrades: list[ApiManagedTradeHistoryDTO] | None = ...,
        OrderReference: str | None = ...,
        Source: str | None = ...,
        IsCloseBy: bool | None = ...,
        Liquidation: bool | None = ...,
        FixedInitialMargin: Decimal | None = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        *,
        order_id: int | None = ...,
        opening_order_ids: list[int] | None = ...,
        market_id: int | None = ...,
        market_name: str | None = ...,
        direction: str | None = ...,
        original_quantity: Decimal | None = ...,
        quantity: Decimal | None = ...,
        price: Decimal | None = ...,
        trading_account_id: int | None = ...,
        currency: str | None = ...,
        realised_pnl: Decimal | None = ...,
        realised_pnl_currency: str | None = ...,
        last_changed_date_time_utc: StoneXDateTime | None = ...,
        executed_date_time_utc: StoneXDateTime | None = ...,
        trade_reference: str | None = ...,
        managed_trades: list[ApiManagedTradeHistoryDTO] | None = ...,
        order_reference: str | None = ...,
        source: str | None = ...,
        is_close_by: bool | None = ...,
        liquidation: bool | None = ...,
        fixed_initial_margin: Decimal | None = ...,
    ) -> None: ...
