# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class ApiUpdateDeleteClientPreferenceResponseDTO(ResponseModel):
    successful: bool | None = Field(default=None, alias="Successful")


ApiUpdateDeleteClientPreferenceResponseDTO.model_rebuild(raise_errors=False)
