# GENERATED by stonepy._generator. Do not edit by hand.
"""
Represents a CI Connect user's profile. Note: for use of the CI Connect social trading
platform.
"""

from __future__ import annotations

from typing import overload

from pydantic import Field

from stonepy._core.models import ResponseModel, StoneXDateTime

class ApiUserProfileDTO(ResponseModel):
    """
    Represents a CI Connect user's profile. Note: for use of the CI Connect social trading
    platform.
    """

    client_account_id: int | None = Field(default=None, alias="ClientAccountId")
    """Internal client account identifier used to uniquely identify the client."""
    facebook_id: str | None = Field(default=None, alias="FacebookId")
    """The user's Facebook ID."""
    screen_name: str | None = Field(default=None, alias="ScreenName")
    """The user's screen name."""
    first_name: str | None = Field(default=None, alias="FirstName")
    """The first name of the user. It is either extracted from Facebook or entered by the user."""
    last_name: str | None = Field(default=None, alias="LastName")
    """The surname of the user. It is either extracted from Facebook or entered by the user."""
    email: str | None = Field(default=None, alias="Email")
    """the user's personal email address. Either extracted from Facebook or entered by the user."""
    allow_app: bool | None = Field(default=None, alias="AllowApp")
    """True if the user has accepted the CI Connect App in Facebook, otherwise False."""
    avatar: str | None = Field(default=None, alias="Avatar")
    """URL to the user's avatar image. Obtained from Facebook or CI Connect profile Edit page."""
    points_spent: int | None = Field(default=None, alias="PointsSpent")
    """Number of points spent by the user."""
    trading_experience_in_years: int | None = Field(default=None, alias="TradingExperienceInYears")
    """The user's trading experience in years."""
    trading_experience: str | None = Field(default=None, alias="TradingExperience")
    """Description of the user's trading experience."""
    biography: str | None = Field(default=None, alias="Biography")
    """The user's personal biography."""
    risk_appetite_id: int | None = Field(default=None, alias="RiskAppetiteId")
    """The user's risk appetite."""
    trading_strategy_ids: int | None = Field(default=None, alias="TradingStrategyIds")
    """The user's preferred trading strategies."""
    risk_limiting_strategy_ids: int | None = Field(default=None, alias="RiskLimitingStrategyIds")
    """The user's preferred risk limiting strategies."""
    last_login_date: StoneXDateTime | None = Field(default=None, alias="LastLoginDate")
    """The date and time that the user last logged into CI Connect."""
    is_demo: bool | None = Field(default=None, alias="IsDemo")
    """Gets or sets a boolean True/False value indicating whether the user has a demo account."""
    culture_id: int | None = Field(default=None, alias="CultureId")
    """Gets or sets a value indicating the culture of the user."""

    @overload
    def __init__(
        self,
        *,
        ClientAccountId: int | None = ...,
        FacebookId: str | None = ...,
        ScreenName: str | None = ...,
        FirstName: str | None = ...,
        LastName: str | None = ...,
        Email: str | None = ...,
        AllowApp: bool | None = ...,
        Avatar: str | None = ...,
        PointsSpent: int | None = ...,
        TradingExperienceInYears: int | None = ...,
        TradingExperience: str | None = ...,
        Biography: str | None = ...,
        RiskAppetiteId: int | None = ...,
        TradingStrategyIds: int | None = ...,
        RiskLimitingStrategyIds: int | None = ...,
        LastLoginDate: StoneXDateTime | None = ...,
        IsDemo: bool | None = ...,
        CultureId: int | None = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        *,
        client_account_id: int | None = ...,
        facebook_id: str | None = ...,
        screen_name: str | None = ...,
        first_name: str | None = ...,
        last_name: str | None = ...,
        email: str | None = ...,
        allow_app: bool | None = ...,
        avatar: str | None = ...,
        points_spent: int | None = ...,
        trading_experience_in_years: int | None = ...,
        trading_experience: str | None = ...,
        biography: str | None = ...,
        risk_appetite_id: int | None = ...,
        trading_strategy_ids: int | None = ...,
        risk_limiting_strategy_ids: int | None = ...,
        last_login_date: StoneXDateTime | None = ...,
        is_demo: bool | None = ...,
        culture_id: int | None = ...,
    ) -> None: ...
