# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class ApiValidateSessionRequestDTOv2(ResponseModel):
    client_account_id: int | None = Field(default=None, alias="ClientAccountId")
    user_name: str | None = Field(default=None, alias="UserName")
    session: str | None = Field(default=None, alias="Session")
    trading_account_id: int | None = Field(default=None, alias="TradingAccountId")
    contract_id: int | None = Field(default=None, alias="ContractId")


ApiValidateSessionRequestDTOv2.model_rebuild(raise_errors=False)
