# GENERATED by stonepy._generator. Do not edit by hand.
"""
List entry for ApiGetWallItemsForUsersResponseDTO . Contains the screen name of a CI Connect
user and the list of their wall items. Note: for use of the CI Connect social trading
platform.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ApiWallItemDTO import ApiWallItemDTO


class ApiWallItemsForUsersDTO(ResponseModel):
    """
    List entry for ApiGetWallItemsForUsersResponseDTO . Contains the screen name of a CI
    Connect user and the list of their wall items. Note: for use of the CI Connect social
    trading platform.
    """

    screen_name: str | None = Field(default=None, alias="ScreenName")
    """The CI Connect screen name for the user."""
    wall_items_for_user: list[ApiWallItemDTO] | None = Field(default=None, alias="WallItemsForUser")
    """The list of wall items for this CI Connect user."""


ApiWallItemsForUsersDTO.model_rebuild(raise_errors=False)
