# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from typing import Any

from pydantic import Field

from stonepy._core.models import ResponseModel, StoneXDateTime

Unresolved = Any


class ApiWallItemDTO(ResponseModel):
    wall_item_id: int | None = Field(default=None, alias="WallItemId")
    parent_wall_item_id: int | None = Field(default=None, alias="ParentWallItemId")
    screen_name: str | None = Field(default=None, alias="ScreenName")
    from_user_screen_name: str | None = Field(default=None, alias="FromUserScreenName")
    from_user_avatar: str | None = Field(default=None, alias="FromUserAvatar")
    comment_text: str | None = Field(default=None, alias="CommentText")
    trade_action: Unresolved | None = Field(default=None, alias="TradeAction")
    user_likes: str | None = Field(default=None, alias="UserLikes")
    flagged_as_inappropriate: bool | None = Field(default=None, alias="FlaggedAsInappropriate")
    create_date: StoneXDateTime | None = Field(default=None, alias="CreateDate")
    no_of_sub_comments: int | None = Field(default=None, alias="NoOfSubComments")


ApiWallItemDTO.model_rebuild(raise_errors=False)
