# GENERATED by stonepy._generator. Do not edit by hand.
"""A cancel order request."""

from __future__ import annotations

from typing import overload

from pydantic import Field

from stonepy._core.models import RequestModel

class CancelOrderRequestDTO(RequestModel):
    """A cancel order request."""

    order_id: int = Field(alias="OrderId")
    """The order identifier."""
    trading_account_id: int = Field(alias="TradingAccountId")
    """ID of the trading account associated with the cancel order request."""
    market_id: int = Field(alias="MarketId")
    """Mandatory parameter - the Market identifier which the OrderId resides on."""
    reference: str = Field(alias="Reference")
    """Reference for the instruction."""

    @overload
    def __init__(
        self,
        *,
        OrderId: int,
        TradingAccountId: int,
        MarketId: int,
        Reference: str,
    ) -> None: ...
    @overload
    def __init__(
        self,
        *,
        order_id: int,
        trading_account_id: int,
        market_id: int,
        reference: str,
    ) -> None: ...
