# GENERATED by stonepy._generator. Do not edit by hand.
"""Information about Cash equity."""

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ApiClientAccountTokenDTOv2 import ApiClientAccountTokenDTOv2


class CashEquity(ResponseModel):
    """Information about Cash equity."""

    client_account_token: list[ApiClientAccountTokenDTOv2] | None = Field(
        default=None, alias="ClientAccountToken"
    )
    """Client account tokens"""


CashEquity.model_rebuild(raise_errors=False)
