# GENERATED by stonepy._generator. Do not edit by hand.
"""Get client preferences stored in a preference key."""

from __future__ import annotations

from typing import overload

from pydantic import Field

from stonepy._core.models import RequestModel

class ClientPreferenceRequestDTO(RequestModel):
    """Get client preferences stored in a preference key."""

    key: str = Field(alias="Key")
    """The client preference key to get."""

    @overload
    def __init__(
        self,
        *,
        Key: str,
    ) -> None: ...
    @overload
    def __init__(
        self,
        *,
        key: str,
    ) -> None: ...
