# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class ClientPreferenceKeyDTO(ResponseModel):
    key: str | None = Field(default=None, alias="Key")
    value: str | None = Field(default=None, alias="Value")


ClientPreferenceKeyDTO.model_rebuild(raise_errors=False)
