# GENERATED by stonepy._generator. Do not edit by hand.
"""ClientPreferenceKey DTO"""

from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class ClientPreferenceKeyDTO(ResponseModel):
    """ClientPreferenceKey DTO"""

    key: str | None = Field(default=None, alias="Key")
    """A unique client preference key identifier"""
    value: str | None = Field(default=None, alias="Value")
    """A value associated for the client preference key"""


ClientPreferenceKeyDTO.model_rebuild(raise_errors=False)
