# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from pydantic import Field

from stonepy._core.models import RequestModel


class ClientPreferenceRequestDTO(RequestModel):
    key: str = Field(alias="Key")


ClientPreferenceRequestDTO.model_rebuild(raise_errors=False)
