# GENERATED by stonepy._generator. Do not edit by hand.
"""Get an array of client preferences stored in preference keys."""

from __future__ import annotations

from typing import overload

from pydantic import Field

from stonepy._core.models import RequestModel

class ClientPreferencesRequestDTO(RequestModel):
    """Get an array of client preferences stored in preference keys."""

    key: list[str] = Field(alias="Key")
    """The array of client preference keys to retrieve."""

    @overload
    def __init__(
        self,
        *,
        Key: list[str],
    ) -> None: ...
    @overload
    def __init__(
        self,
        *,
        key: list[str],
    ) -> None: ...
