# GENERATED by stonepy._generator. Do not edit by hand.
"""Get client preferences stored in a preference key."""

from __future__ import annotations

from pydantic import Field

from stonepy._core.models import RequestModel


class ClientPreferenceRequestDTO(RequestModel):
    """Get client preferences stored in a preference key."""

    key: str = Field(alias="Key")
    """The client preference key to get."""


ClientPreferenceRequestDTO.model_rebuild(raise_errors=False)
