# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class DeleteWatchlistItemRequestDTO(ResponseModel):
    parent_watchlist_display_order_id: int | None = Field(
        default=None, alias="ParentWatchlistDisplayOrderId"
    )
    market_id: int | None = Field(default=None, alias="MarketId")


DeleteWatchlistItemRequestDTO.model_rebuild(raise_errors=False)
