# GENERATED by stonepy._generator. Do not edit by hand.
"""Request to delete a Trading Advisor allocation profile."""

from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class DeleteAllocationProfileRequestDTO(ResponseModel):
    """Request to delete a Trading Advisor allocation profile."""

    id: int | None = Field(default=None, alias="Id")
    """The identifier of the allocation profile that is being deleted."""


DeleteAllocationProfileRequestDTO.model_rebuild(raise_errors=False)
