# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from decimal import Decimal

from pydantic import Field

from stonepy._core.models import ResponseModel, StoneXDateTime


class EnrichedOrderDTO(ResponseModel):
    market_id: int | None = Field(default=None, alias="MarketId")
    market_name: str | None = Field(default=None, alias="MarketName")
    order_direction_id: int | None = Field(default=None, alias="OrderDirectionId")
    order_type_id: int | None = Field(default=None, alias="OrderTypeId")
    quantity: Decimal | None = Field(default=None, alias="Quantity")
    level: Decimal | None = Field(default=None, alias="Level")
    order_expiry_id: int | None = Field(default=None, alias="OrderExpiryId")
    expiry_date_time_utc: StoneXDateTime | None = Field(default=None, alias="ExpiryDateTimeUtc")
    order_id: int | None = Field(default=None, alias="OrderId")
    status_id: int | None = Field(default=None, alias="StatusId")
    currency_id: int | None = Field(default=None, alias="CurrencyId")
    request_id: str | None = Field(default=None, alias="RequestId")
    client_account_id: int | None = Field(default=None, alias="ClientAccountId")
    tax: Decimal | None = Field(default=None, alias="Tax")
    commission: Decimal | None = Field(default=None, alias="Commission")
    order_reason_id: int | None = Field(default=None, alias="OrderReasonId")
    reason_text: str | None = Field(default=None, alias="ReasonText")
    execution_policy_id: int | None = Field(default=None, alias="ExecutionPolicyId")
    transaction_id: str | None = Field(default=None, alias="TransactionId")
    fx_conversion_charge: Decimal | None = Field(default=None, alias="FxConversionCharge")
    fill_level: Decimal | None = Field(default=None, alias="FillLevel")
    request_type_id: int | None = Field(default=None, alias="RequestTypeId")
    version: int | None = Field(default=None, alias="Version")
    order_value: Decimal | None = Field(default=None, alias="OrderValue")
    total_value: Decimal | None = Field(default=None, alias="TotalValue")
    last_changed_date_time_utc: StoneXDateTime | None = Field(
        default=None, alias="LastChangedDateTimeUtc"
    )


EnrichedOrderDTO.model_rebuild(raise_errors=False)
