# GENERATED by stonepy._generator. Do not edit by hand.
"""Information about execution venue request."""

from __future__ import annotations

from decimal import Decimal
from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .OrderRequestDTO import OrderRequestDTO


class ExecutionVenueRequestDTO(ResponseModel):
    """Information about execution venue request."""

    client_account_id: int | None = Field(default=None, alias="ClientAccountId")
    """Client account identifier"""
    app_key: str | None = Field(default=None, alias="AppKey")
    """Information about app key"""
    request_id: str | None = Field(default=None, alias="RequestId")
    """Request identifier"""
    quote_id: int | None = Field(default=None, alias="QuoteId")
    """Quote identifier"""
    market_id: int | None = Field(default=None, alias="MarketId")
    """Market identifier"""
    order_requests: list[OrderRequestDTO] | None = Field(default=None, alias="OrderRequests")
    """List of order requests"""
    request_type_id: int | None = Field(default=None, alias="RequestTypeId")
    """Request type identifier"""
    trading_account_id: int | None = Field(default=None, alias="TradingAccountId")
    """Trading account identifier"""
    user_name: str | None = Field(default=None, alias="UserName")
    """The username"""
    simulation: bool | None = Field(default=None, alias="Simulation")
    """Flag indicating whether it's a simulation"""
    transaction_id: str | None = Field(default=None, alias="TransactionId")
    """Transaction identifier"""
    bid: Decimal | None = Field(default=None, alias="Bid")
    """Bid"""
    ask: Decimal | None = Field(default=None, alias="Ask")
    """Ask"""
    audit_id: str | None = Field(default=None, alias="AuditId")
    """Audit identifier"""


ExecutionVenueRequestDTO.model_rebuild(raise_errors=False)
