# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from decimal import Decimal

from pydantic import Field

from stonepy._core.models import ResponseModel


class FixedMarginOrderResponseDTO(ResponseModel):
    instruction_status_id: int | None = Field(default=None, alias="InstructionStatusId")
    instruction_status_reason_id: int | None = Field(
        default=None, alias="InstructionStatusReasonId"
    )
    order_status_id: int | None = Field(default=None, alias="OrderStatusId")
    order_status_reason_id: int | None = Field(default=None, alias="OrderStatusReasonId")
    order_id: int | None = Field(default=None, alias="OrderId")
    quantity: Decimal | None = Field(default=None, alias="Quantity")
    execution_price: Decimal | None = Field(default=None, alias="ExecutionPrice")
    fixed_initial_margin: Decimal | None = Field(default=None, alias="FixedInitialMargin")
    take_profit_price: Decimal | None = Field(default=None, alias="TakeProfitPrice")
    stop_loss_price: Decimal | None = Field(default=None, alias="StopLossPrice")
    error_message: str | None = Field(default=None, alias="ErrorMessage")


FixedMarginOrderResponseDTO.model_rebuild(raise_errors=False)
