# GENERATED by stonepy._generator. Do not edit by hand.
"""Response containing the active stop limit order."""

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ApiActiveStopLimitOrderDTOv2 import ApiActiveStopLimitOrderDTOv2


class GetActiveStopLimitOrderResponseDTOv2(ResponseModel):
    """Response containing the active stop limit order."""

    active_stop_limit_order: ApiActiveStopLimitOrderDTOv2 | None = Field(
        default=None, alias="ActiveStopLimitOrder"
    )
    """The active stop limit order. If it is null then the active stop limit order does not exist"""


GetActiveStopLimitOrderResponseDTOv2.model_rebuild(raise_errors=False)
