# GENERATED by stonepy._generator. Do not edit by hand.
"""Contains the response to a GetChangedOrders FIX API query."""

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .GetOrderResponseDTOv2 import GetOrderResponseDTOv2


class GetChangedOrdersResponseDTO(ResponseModel):
    """Contains the response to a GetChangedOrders FIX API query."""

    changed_orders: list[GetOrderResponseDTOv2] | None = Field(default=None, alias="ChangedOrders")
    """The requested list of changed orders."""


GetChangedOrdersResponseDTO.model_rebuild(raise_errors=False)
