# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ApiMarketInformationDTOv2 import ApiMarketInformationDTOv2


class GetMarketInformationResponseDTO(ResponseModel):
    market_information: ApiMarketInformationDTOv2 | None = Field(
        default=None, alias="MarketInformation"
    )


GetMarketInformationResponseDTO.model_rebuild(raise_errors=False)
