# GENERATED by stonepy._generator. Do not edit by hand.
"""Response from a market information request."""

from __future__ import annotations

from typing import TYPE_CHECKING, overload

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ApiMarketInformationDTOv2 import ApiMarketInformationDTOv2

class GetMarketInformationResponseDTOv2(ResponseModel):
    """Response from a market information request."""

    market_information: ApiMarketInformationDTOv2 | None = Field(
        default=None, alias="MarketInformation"
    )
    """The requested market information."""

    @overload
    def __init__(
        self,
        *,
        MarketInformation: ApiMarketInformationDTOv2 | None = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        *,
        market_information: ApiMarketInformationDTOv2 | None = ...,
    ) -> None: ...
