# GENERATED by stonepy._generator. Do not edit by hand.
"""
Message popup response denoting whether the client application should display a popup
notification at startup.
"""

from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class GetMessagePopupResponseDTO(ResponseModel):
    """
    Message popup response denoting whether the client application should display a popup
    notification at startup.
    """

    ask_for_client_approval: bool | None = Field(default=None, alias="AskForClientApproval")
    """Flag indicating if the client application asks for client approval."""
    message: str | None = Field(default=None, alias="Message")
    """The message to display to the client."""


GetMessagePopupResponseDTO.model_rebuild(raise_errors=False)
