# GENERATED by stonepy._generator. Do not edit by hand.
"""Response containing the open position information."""

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ApiOpenPositionDTOv2 import ApiOpenPositionDTOv2


class GetOpenPositionResponseDTOv2(ResponseModel):
    """Response containing the open position information."""

    open_position: ApiOpenPositionDTOv2 | None = Field(default=None, alias="OpenPosition")
    """The open position information. If it is null then the open position does not exist"""


GetOpenPositionResponseDTOv2.model_rebuild(raise_errors=False)
