# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ApiStopLimitOrderDTOv2 import ApiStopLimitOrderDTOv2
    from .ApiTradeOrderDTOv2 import ApiTradeOrderDTOv2


class GetOrderResponseDTOv2(ResponseModel):
    trade_order: ApiTradeOrderDTOv2 | None = Field(default=None, alias="TradeOrder")
    stop_limit_order: ApiStopLimitOrderDTOv2 | None = Field(default=None, alias="StopLimitOrder")


GetOrderResponseDTOv2.model_rebuild(raise_errors=False)
