# GENERATED by stonepy._generator. Do not edit by hand.
"""
Response containing the order. Only one of the two fields will be populated depending upon the
type of order (Trade or Stop / Limit) .
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ApiStopLimitOrderDTOv2 import ApiStopLimitOrderDTOv2
    from .ApiTradeOrderDTOv2 import ApiTradeOrderDTOv2


class GetOrderResponseDTOv2(ResponseModel):
    """
    Response containing the order. Only one of the two fields will be populated depending upon
    the type of order (Trade or Stop / Limit) .
    """

    trade_order: ApiTradeOrderDTOv2 | None = Field(default=None, alias="TradeOrder")
    """The details of the order if it is a trade / open position"""
    stop_limit_order: ApiStopLimitOrderDTOv2 | None = Field(default=None, alias="StopLimitOrder")
    """The details of the order if it is a stop limit order"""


GetOrderResponseDTOv2.model_rebuild(raise_errors=False)
