# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .PriceBarDTO import PriceBarDTO


class GetPriceBarResponseDTO(ResponseModel):
    price_bars: list[PriceBarDTO] | None = Field(default=None, alias="PriceBars")
    partial_price_bar: PriceBarDTO | None = Field(default=None, alias="PartialPriceBar")


GetPriceBarResponseDTO.model_rebuild(raise_errors=False)
