# GENERATED by stonepy._generator. Do not edit by hand.
"""The response containing version information and upgrade URL of the client application."""

from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class GetVersionInformationResponseDTO(ResponseModel):
    """The response containing version information and upgrade URL of the client application."""

    minimum_required_version: str | None = Field(default=None, alias="MinimumRequiredVersion")
    """
    The minimum version of the client application that can be used. If the installed version
    is less than this it shouldn't be used.
    """
    latest_version: str | None = Field(default=None, alias="LatestVersion")
    """The latest version of the client application that can be used."""
    upgrade_url: str | None = Field(default=None, alias="UpgradeUrl")
    """The URL of the upgrade."""


GetVersionInformationResponseDTO.model_rebuild(raise_errors=False)
