# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class GetVersionInformationResponseDTO(ResponseModel):
    minimum_required_version: str | None = Field(default=None, alias="MinimumRequiredVersion")
    latest_version: str | None = Field(default=None, alias="LatestVersion")
    upgrade_url: str | None = Field(default=None, alias="UpgradeUrl")


GetVersionInformationResponseDTO.model_rebuild(raise_errors=False)
