# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .HistoricalOrderDTO import HistoricalOrderDTO


class HistoricalOrdersResponseDTO(ResponseModel):
    historical_orders: list[HistoricalOrderDTO] | None = Field(
        default=None, alias="HistoricalOrders"
    )


HistoricalOrdersResponseDTO.model_rebuild(raise_errors=False)
