# GENERATED by stonepy._generator. Do not edit by hand.
"""
All service calls and DTOs related to Predicted Markets are for internal StoneX use only.
Response to a GetHistoricalOrders call containing the list of historical orders.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .HistoricalOrderDTO import HistoricalOrderDTO


class HistoricalOrdersResponseDTO(ResponseModel):
    """
    All service calls and DTOs related to Predicted Markets are for internal StoneX use only.
    Response to a GetHistoricalOrders call containing the list of historical orders.
    """

    historical_orders: list[HistoricalOrderDTO] | None = Field(
        default=None, alias="HistoricalOrders"
    )
    """The list of historical orders."""


HistoricalOrdersResponseDTO.model_rebuild(raise_errors=False)
