# GENERATED by stonepy._generator. Do not edit by hand.
"""Update watchlist with item request."""

from __future__ import annotations

from typing import overload

from pydantic import Field

from stonepy._core.models import ResponseModel

class InsertWatchlistItemRequestDTO(ResponseModel):
    """Update watchlist with item request."""

    parent_watchlist_display_order_id: int | None = Field(
        default=None, alias="ParentWatchlistDisplayOrderId"
    )
    """The watchlist display order ID to add the item."""
    market_id: int | None = Field(default=None, alias="MarketId")
    """The market item to add into the watchlist."""

    @overload
    def __init__(
        self,
        *,
        ParentWatchlistDisplayOrderId: int | None = ...,
        MarketId: int | None = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        *,
        parent_watchlist_display_order_id: int | None = ...,
        market_id: int | None = ...,
    ) -> None: ...
