# GENERATED by stonepy._generator. Do not edit by hand.
"""Represents the legal party entity."""

from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class LegalPartyDTO(ResponseModel):
    """Represents the legal party entity."""

    party_id: int | None = Field(default=None, alias="PartyId")
    """Party identifier"""
    personal_email_address: str | None = Field(default=None, alias="PersonalEmailAddress")
    """Personal email address"""
    has_multiple_email_addresses: bool | None = Field(
        default=None, alias="HasMultipleEmailAddresses"
    )
    """Flag which show if user has multiple email addresses"""
    legal_party_unique_reference: int | None = Field(
        default=None, alias="LegalPartyUniqueReference"
    )
    """Legal party unique identifier"""
    is_piis_provided: bool | None = Field(default=None, alias="IsPiisProvided")
    """Is piis provided flag"""


LegalPartyDTO.model_rebuild(raise_errors=False)
