# GENERATED by stonepy._generator. Do not edit by hand.
"""Information about a Linked account."""

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ApiAccountHolderDTO import ApiAccountHolderDTO
    from .ApiAccountOperatorDTOv2 import ApiAccountOperatorDTOv2
    from .ApiClientAccountDTO import ApiClientAccountDTO
    from .ApiContractDTOv2 import ApiContractDTOv2
    from .ApiRestrictionDTOv2 import ApiRestrictionDTOv2
    from .ApiTradingAccountDTOv2 import ApiTradingAccountDTOv2
    from .LegalPartyDTO import LegalPartyDTO
    from .LogonUser import LogonUser


class LinkedAccountResult(ResponseModel):
    """Information about a Linked account."""

    logon_user: LogonUser | None = Field(default=None, alias="LogonUser")
    """Logon user"""
    legal_parties: list[LegalPartyDTO] | None = Field(default=None, alias="LegalParties")
    """Legal parties"""
    account_holders: list[ApiAccountHolderDTO] | None = Field(default=None, alias="AccountHolders")
    """Account holders"""
    client_accounts: list[ApiClientAccountDTO] | None = Field(default=None, alias="ClientAccounts")
    """Client accounts"""
    trading_accounts: list[ApiTradingAccountDTOv2] | None = Field(
        default=None, alias="TradingAccounts"
    )
    """Trading accounts"""
    account_operators: list[ApiAccountOperatorDTOv2] | None = Field(
        default=None, alias="AccountOperators"
    )
    """Account operators"""
    contracts: list[ApiContractDTOv2] | None = Field(default=None, alias="Contracts")
    """Contracts"""
    restrictions: list[ApiRestrictionDTOv2] | None = Field(default=None, alias="Restrictions")
    """Restrictions"""


LinkedAccountResult.model_rebuild(raise_errors=False)
