# GENERATED by stonepy._generator. Do not edit by hand.
"""Response from a market information search request."""

from __future__ import annotations

from typing import TYPE_CHECKING, overload

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ApiMarketInformationDTOv2 import ApiMarketInformationDTOv2

class ListMarketInformationSearchResponseDTO(ResponseModel):
    """Response from a market information search request."""

    market_information: list[ApiMarketInformationDTOv2] | None = Field(
        default=None, alias="MarketInformation"
    )
    """The requested list of market information."""

    @overload
    def __init__(
        self,
        *,
        MarketInformation: list[ApiMarketInformationDTOv2] | None = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        *,
        market_information: list[ApiMarketInformationDTOv2] | None = ...,
    ) -> None: ...
