# GENERATED by stonepy._generator. Do not edit by hand.
"""The request containing the specified watchlist IDs to retrieve."""

from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class ListWatchlistRequestDTO(ResponseModel):
    """The request containing the specified watchlist IDs to retrieve."""

    watch_list_ids: list[int] | None = Field(default=None, alias="WatchListIds")
    """
    The collection of watchlist IDs to retrieve. An empty collection represents the request
    should retrieve all client watchlists.
    """
    include_market_information: bool | None = Field(default=None, alias="IncludeMarketInformation")
    """
    Flag indicating whether to retrieve market information for the watchlist markets. Default
    is FALSE.
    """
    include_items: bool | None = Field(default=None, alias="IncludeItems")
    """Flag indicating whether to retrieve the watchlist items. Default is TRUE."""


ListWatchlistRequestDTO.model_rebuild(raise_errors=False)
