# GENERATED by stonepy._generator. Do not edit by hand.
"""Response to a request for a list of Trading Advisor allocation profiles."""

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ManagedClientDTO import ManagedClientDTO


class ListManagedClientsResponseDTO(ResponseModel):
    """Response to a request for a list of Trading Advisor allocation profiles."""

    client_account_id: int | None = Field(default=None, alias="ClientAccountId")
    """The identifier of the Trading Advisor's client account."""
    managed_clients: list[ManagedClientDTO] | None = Field(default=None, alias="ManagedClients")
    """The list of clients managed by the Trading Advisor."""


ListManagedClientsResponseDTO.model_rebuild(raise_errors=False)
