# GENERATED by stonepy._generator. Do not edit by hand.
"""An (empty) response to indicate that the save market information operation was completed."""

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ApiMarketInformationDTOv2 import ApiMarketInformationDTOv2


class ListMarketInformationResponseDTO(ResponseModel):
    """An (empty) response to indicate that the save market information operation was completed."""

    market_informations: list[ApiMarketInformationDTOv2] | None = Field(
        default=None, alias="MarketInformations"
    )
    """Save Market Information for the specified list of markets"""


ListMarketInformationResponseDTO.model_rebuild(raise_errors=False)
