# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class ListMarketSearchPaginatedResponseDTO(ResponseModel):
    total_number_of_results: int | None = Field(default=None, alias="TotalNumberOfResults")


ListMarketSearchPaginatedResponseDTO.model_rebuild(raise_errors=False)
