# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ApiOpenPositionDTOv2 import ApiOpenPositionDTOv2


class ListOpenPositionsResponseDTO(ResponseModel):
    open_positions: list[ApiOpenPositionDTOv2] | None = Field(default=None, alias="OpenPositions")


ListOpenPositionsResponseDTO.model_rebuild(raise_errors=False)
