# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ApiClientAccountWatchlistDTO import ApiClientAccountWatchlistDTO


class ListWatchlistResponseDTO(ResponseModel):
    client_account_id: int | None = Field(default=None, alias="ClientAccountId")
    client_account_watchlists: list[ApiClientAccountWatchlistDTO] | None = Field(
        default=None, alias="ClientAccountWatchlists"
    )


ListWatchlistResponseDTO.model_rebuild(raise_errors=False)
