# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class ListMarketInformationRequestDTO(ResponseModel):
    market_ids: list[int] | None = Field(default=None, alias="MarketIds")
    trading_account_id: int | None = Field(default=None, alias="TradingAccountId")


ListMarketInformationRequestDTO.model_rebuild(raise_errors=False)
