# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ApiActiveOrderDTO import ApiActiveOrderDTO


class ListActiveOrdersResponseDTO(ResponseModel):
    active_orders: list[ApiActiveOrderDTO] | None = Field(default=None, alias="ActiveOrders")


ListActiveOrdersResponseDTO.model_rebuild(raise_errors=False)
