# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ManagedClientDTO import ManagedClientDTO


class ListManagedClientsResponseDTO(ResponseModel):
    client_account_id: int | None = Field(default=None, alias="ClientAccountId")
    managed_clients: list[ManagedClientDTO] | None = Field(default=None, alias="ManagedClients")


ListManagedClientsResponseDTO.model_rebuild(raise_errors=False)
