# GENERATED by stonepy._generator. Do not edit by hand.
"""Contains the result of a ListStopLimitOrderHistory query."""

from __future__ import annotations

from typing import TYPE_CHECKING, overload

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ApiStopLimitOrderHistoryDTO import ApiStopLimitOrderHistoryDTO

class ListStopLimitOrderHistoryResponseDTO(ResponseModel):
    """Contains the result of a ListStopLimitOrderHistory query."""

    stop_limit_order_history: list[ApiStopLimitOrderHistoryDTO] | None = Field(
        default=None, alias="StopLimitOrderHistory"
    )
    """A list of historical stop / limit orders."""

    @overload
    def __init__(
        self,
        *,
        StopLimitOrderHistory: list[ApiStopLimitOrderHistoryDTO] | None = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        *,
        stop_limit_order_history: list[ApiStopLimitOrderHistoryDTO] | None = ...,
    ) -> None: ...
