# GENERATED by stonepy._generator. Do not edit by hand.
"""Contains the result of a ListTradeHistory query."""

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ApiTradeHistoryDTO import ApiTradeHistoryDTO


class ListTradeHistoryResponseDTO(ResponseModel):
    """Contains the result of a ListTradeHistory query."""

    trade_history: list[ApiTradeHistoryDTO] | None = Field(default=None, alias="TradeHistory")
    """A list of historical trades."""
    supplemental_open_orders: list[ApiTradeHistoryDTO] | None = Field(
        default=None, alias="SupplementalOpenOrders"
    )
    """
    A list of trades which are referenced as OpenOrderId 's in the trade history list - but do
    not actually exist in that list.
    """


ListTradeHistoryResponseDTO.model_rebuild(raise_errors=False)
