# GENERATED by stonepy._generator. Do not edit by hand.
"""Contains the result of a ListSpreadMarkets query."""

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ApiMarketDTO import ApiMarketDTO


class ListSpreadMarketsResponseDTO(ResponseModel):
    """Contains the result of a ListSpreadMarkets query."""

    markets: list[ApiMarketDTO] | None = Field(default=None, alias="Markets")
    """A list of Spread Betting markets."""


ListSpreadMarketsResponseDTO.model_rebuild(raise_errors=False)
