# GENERATED by stonepy._generator. Do not edit by hand.
"""Response to a client watchlist GET request."""

from __future__ import annotations

from typing import TYPE_CHECKING, overload

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ApiClientAccountWatchlistDTO import ApiClientAccountWatchlistDTO

class ListWatchlistResponseDTO(ResponseModel):
    """Response to a client watchlist GET request."""

    client_account_id: int | None = Field(default=None, alias="ClientAccountId")
    """Client account identifier"""
    client_account_watchlists: list[ApiClientAccountWatchlistDTO] | None = Field(
        default=None, alias="ClientAccountWatchlists"
    )
    """List of client account watchlists"""

    @overload
    def __init__(
        self,
        *,
        ClientAccountId: int | None = ...,
        ClientAccountWatchlists: list[ApiClientAccountWatchlistDTO] | None = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        *,
        client_account_id: int | None = ...,
        client_account_watchlists: list[ApiClientAccountWatchlistDTO] | None = ...,
    ) -> None: ...
