# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ApiTradeHistoryDTO import ApiTradeHistoryDTO


class ListTradeHistoryResponseDTO(ResponseModel):
    trade_history: list[ApiTradeHistoryDTO] | None = Field(default=None, alias="TradeHistory")
    supplemental_open_orders: list[ApiTradeHistoryDTO] | None = Field(
        default=None, alias="SupplementalOpenOrders"
    )


ListTradeHistoryResponseDTO.model_rebuild(raise_errors=False)
