# GENERATED by stonepy._generator. Do not edit by hand.
"""Information about a Logon user."""

from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class LogonUser(ResponseModel):
    """Information about a Logon user."""

    logon_user_name: str | None = Field(default=None, alias="LogonUserName")
    """Logon username"""


LogonUser.model_rebuild(raise_errors=False)
