# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .MarketSearchResultDTO import MarketSearchResultDTO


class MarketInformationSearchWithoutTagsResponseDTO(ResponseModel):
    markets: list[MarketSearchResultDTO] | None = Field(default=None, alias="Markets")


MarketInformationSearchWithoutTagsResponseDTO.model_rebuild(raise_errors=False)
