# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from decimal import Decimal

from pydantic import Field

from stonepy._core.models import ResponseModel


class MarketSpreadData(ResponseModel):
    market_id: int | None = Field(default=None, alias="MarketId")
    out_of_hours: Decimal | None = Field(default=None, alias="OutOfHours")
    in_hours: Decimal | None = Field(default=None, alias="InHours")
    mark_up: Decimal | None = Field(default=None, alias="MarkUp")
    mark_up_units: Decimal | None = Field(default=None, alias="MarkUpUnits")
    typical_spread: Decimal | None = Field(default=None, alias="TypicalSpread")
    min_spread: Decimal | None = Field(default=None, alias="MinSpread")


MarketSpreadData.model_rebuild(raise_errors=False)
