# GENERATED by stonepy._generator. Do not edit by hand.
"""Response from a market information search with tags request."""

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .ApiMarketDTO import ApiMarketDTO
    from .ApiMarketTagDTO import ApiMarketTagDTO


class MarketInformationSearchWithTagsResponseDTO(ResponseModel):
    """Response from a market information search with tags request."""

    markets: list[ApiMarketDTO] | None = Field(default=None, alias="Markets")
    """The requested list of market information."""
    tags: list[ApiMarketTagDTO] | None = Field(default=None, alias="Tags")
    """The requested list of market tags."""


MarketInformationSearchWithTagsResponseDTO.model_rebuild(raise_errors=False)
