# GENERATED by stonepy._generator. Do not edit by hand.
"""Contains information about market spread."""

from __future__ import annotations

from decimal import Decimal

from pydantic import Field

from stonepy._core.models import ResponseModel


class MarketSpreadData(ResponseModel):
    """Contains information about market spread."""

    market_id: int | None = Field(default=None, alias="MarketId")
    """Market identifier"""
    out_of_hours: Decimal | None = Field(default=None, alias="OutOfHours")
    """Average spread outside Indices market hours"""
    in_hours: Decimal | None = Field(default=None, alias="InHours")
    """Average spread inside Indices market hours"""
    mark_up: Decimal | None = Field(default=None, alias="MarkUp")
    """Spread markup on Equities markets"""
    mark_up_units: Decimal | None = Field(default=None, alias="MarkUpUnits")
    """Units of spread markup on Equities markets (26 = Percentage, 27 = Points)"""
    typical_spread: Decimal | None = Field(default=None, alias="TypicalSpread")
    """Average spread on FX markets"""
    min_spread: Decimal | None = Field(default=None, alias="MinSpread")
    """Minimum spread on FX and Options markets"""


MarketSpreadData.model_rebuild(raise_errors=False)
