# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from pydantic import Field

from stonepy._core.models import RequestModel


class MultipleMarketInformationRequestDTO(RequestModel):
    client_account_id: int = Field(alias="ClientAccountId")
    market_ids: list[int] = Field(alias="MarketIds")


MultipleMarketInformationRequestDTO.model_rebuild(raise_errors=False)
