# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from typing import Any

from pydantic import Field

from stonepy._core.models import ResponseModel

Unresolved = Any


class NewsResponseDTO(ResponseModel):
    news: Unresolved | None = Field(default=None, alias="News")


NewsResponseDTO.model_rebuild(raise_errors=False)
