# GENERATED by stonepy._generator. Do not edit by hand.
"""The response containing the news story details from the GetNews request."""

from __future__ import annotations

from typing import Any

from pydantic import Field

from stonepy._core.models import ResponseModel

Unresolved = Any


class NewsResponseDTO(ResponseModel):
    """The response containing the news story details from the GetNews request."""

    news: Unresolved | None = Field(default=None, alias="News")
    """The details of the news story."""


NewsResponseDTO.model_rebuild(raise_errors=False)
