# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from decimal import Decimal
from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import RequestModel, StoneXDateTime

if TYPE_CHECKING:
    from .ApiIfDoneDTOv2 import ApiIfDoneDTOv2


class NewStopLimitOrderRequestDTO(RequestModel):
    order_id: int = Field(alias="OrderId")
    market_id: int = Field(alias="MarketId")
    currency: str = Field(alias="Currency")
    auto_rollover: bool = Field(alias="AutoRollover")
    direction: str = Field(alias="Direction")
    position_method_id: int = Field(alias="PositionMethodId")
    quantity: Decimal = Field(alias="Quantity")
    bid_price: Decimal = Field(alias="BidPrice")
    offer_price: Decimal = Field(alias="OfferPrice")
    audit_id: str = Field(alias="AuditId")
    trading_account_id: int = Field(alias="TradingAccountId")
    if_done: list[ApiIfDoneDTOv2] | None = Field(default=None, alias="IfDone")
    oco_order: NewStopLimitOrderRequestDTO | None = Field(default=None, alias="OcoOrder")
    applicability: str = Field(alias="Applicability")
    expiry_date_time_utc: StoneXDateTime = Field(alias="ExpiryDateTimeUTC")
    guaranteed: bool = Field(alias="Guaranteed")
    trigger_price: Decimal = Field(alias="TriggerPrice")
    reference: str = Field(alias="Reference")
    allocation_profile_id: int = Field(alias="AllocationProfileId")
    order_reference: str = Field(alias="OrderReference")
    source: str = Field(alias="Source")


NewStopLimitOrderRequestDTO.model_rebuild(raise_errors=False)
