# GENERATED by stonepy._generator. Do not edit by hand.
"""
All service calls and DTOs related to Predicted Markets are for internal StoneX use only.
Response to a GetOpenOrders call containing the list of open orders.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, overload

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .OpenOrderDTO import OpenOrderDTO

class OpenOrdersResponseDTO(ResponseModel):
    """
    All service calls and DTOs related to Predicted Markets are for internal StoneX use only.
    Response to a GetOpenOrders call containing the list of open orders.
    """

    open_orders: list[OpenOrderDTO] | None = Field(default=None, alias="OpenOrders")
    """The list of open orders."""

    @overload
    def __init__(
        self,
        *,
        OpenOrders: list[OpenOrderDTO] | None = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        *,
        open_orders: list[OpenOrderDTO] | None = ...,
    ) -> None: ...
