# GENERATED by stonepy._generator. Do not edit by hand.
"""
All service calls and DTOs related to Predicted Markets are for internal StoneX use only.
Contains information about the open orders.
"""

from __future__ import annotations

from typing import overload

from pydantic import Field

from stonepy._core.models import ResponseModel

class OpenOrderDTO(ResponseModel):
    """
    All service calls and DTOs related to Predicted Markets are for internal StoneX use only.
    Contains information about the open orders.
    """

    market_id: int | None = Field(default=None, alias="MarketId")
    """The market's unique identifier."""

    @overload
    def __init__(
        self,
        *,
        MarketId: int | None = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        *,
        market_id: int | None = ...,
    ) -> None: ...
