# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .OpenOrderDTO import OpenOrderDTO


class OpenOrdersResponseDTO(ResponseModel):
    open_orders: list[OpenOrderDTO] | None = Field(default=None, alias="OpenOrders")


OpenOrdersResponseDTO.model_rebuild(raise_errors=False)
