# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class OpenOrderDTO(ResponseModel):
    market_id: int | None = Field(default=None, alias="MarketId")


OpenOrderDTO.model_rebuild(raise_errors=False)
