# GENERATED by stonepy._generator. Do not edit by hand.
"""Information about order history."""

from __future__ import annotations

from decimal import Decimal
from typing import TYPE_CHECKING, overload

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .Timestamp import Timestamp

class OrderHistoryDTO(ResponseModel):
    """Information about order history."""

    market_id: int | None = Field(default=None, alias="MarketId")
    """The unique identifier for the market"""
    market_name: str | None = Field(default=None, alias="MarketName")
    """The market name"""
    created_date_time_utc: Timestamp | None = Field(default=None, alias="CreatedDateTimeUtc")
    """The date and time the order was created"""
    direction_id: str | None = Field(default=None, alias="DirectionId")
    """The direction, Buy or Sell"""
    original_quantity: Decimal | None = Field(default=None, alias="OriginalQuantity")
    """The original size of the order before user modification."""
    trigger_price: Decimal | None = Field(default=None, alias="TriggerPrice")
    """The marked to market price at which the order will trigger at"""
    expiry_type_id: int | None = Field(default=None, alias="ExpiryTypeId")
    """The unique identifier for the market"""
    expiry: Timestamp | None = Field(default=None, alias="Expiry")
    """The date and time when the order expires"""
    status_id: int | None = Field(default=None, alias="StatusId")
    """
    Status ID of order (as represented in the trading system) . The table of lookup codes can
    be found at Lookup Values .
    """
    order_type_id: int | None = Field(default=None, alias="OrderTypeId")
    """
    The type of the order: trade, stop or limit. The table of lookup codes can be found at
    Lookup Values
    """
    currency_id: int | None = Field(default=None, alias="CurrencyId")
    """The trade currency identifier"""
    order_id: int | None = Field(default=None, alias="OrderId")
    """The unique identifier for the order"""
    filled_quantity: Decimal | None = Field(default=None, alias="FilledQuantity")
    """The filled quantity of a product"""
    client_account_id: int | None = Field(default=None, alias="ClientAccountId")
    """The identifier of the Client Account associated with the order"""
    execution_policy_id: int | None = Field(default=None, alias="ExecutionPolicyId")
    """Execution policy identifier"""
    fill_level: Decimal | None = Field(default=None, alias="FillLevel")
    """The fill level"""

    @overload
    def __init__(
        self,
        *,
        MarketId: int | None = ...,
        MarketName: str | None = ...,
        CreatedDateTimeUtc: Timestamp | None = ...,
        DirectionId: str | None = ...,
        OriginalQuantity: Decimal | None = ...,
        TriggerPrice: Decimal | None = ...,
        ExpiryTypeId: int | None = ...,
        Expiry: Timestamp | None = ...,
        StatusId: int | None = ...,
        OrderTypeId: int | None = ...,
        CurrencyId: int | None = ...,
        OrderId: int | None = ...,
        FilledQuantity: Decimal | None = ...,
        ClientAccountId: int | None = ...,
        ExecutionPolicyId: int | None = ...,
        FillLevel: Decimal | None = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        *,
        market_id: int | None = ...,
        market_name: str | None = ...,
        created_date_time_utc: Timestamp | None = ...,
        direction_id: str | None = ...,
        original_quantity: Decimal | None = ...,
        trigger_price: Decimal | None = ...,
        expiry_type_id: int | None = ...,
        expiry: Timestamp | None = ...,
        status_id: int | None = ...,
        order_type_id: int | None = ...,
        currency_id: int | None = ...,
        order_id: int | None = ...,
        filled_quantity: Decimal | None = ...,
        client_account_id: int | None = ...,
        execution_policy_id: int | None = ...,
        fill_level: Decimal | None = ...,
    ) -> None: ...
