# GENERATED by stonepy._generator. Do not edit by hand.
"""An order for a specific Trading Account."""

from __future__ import annotations

from decimal import Decimal

from pydantic import Field

from stonepy._core.models import ResponseModel, StoneXDateTime


class OrderDTO(ResponseModel):
    """An order for a specific Trading Account."""

    order_id: int | None = Field(default=None, alias="OrderId")
    """The Order identifier."""
    market_id: int | None = Field(default=None, alias="MarketId")
    """The Market identifier."""
    client_account_id: int | None = Field(default=None, alias="ClientAccountId")
    """Client account ID."""
    trading_account_id: int | None = Field(default=None, alias="TradingAccountId")
    """Trading account ID."""
    currency_id: int | None = Field(default=None, alias="CurrencyId")
    """Trade currency ID."""
    currency_iso: str | None = Field(default=None, alias="CurrencyISO")
    """Trade currency ISO code."""
    direction: int | None = Field(default=None, alias="Direction")
    """Direction of the order (1 == buy, 0 == sell)."""
    auto_rollover: bool | None = Field(default=None, alias="AutoRollover")
    """
    Flag indicating whether the order automatically rolls over. Only applies to markets where
    the underlying is a futures contract.
    """
    execution_price: Decimal | None = Field(default=None, alias="ExecutionPrice")
    """The price at which the order was executed."""
    last_changed_time: StoneXDateTime | None = Field(default=None, alias="LastChangedTime")
    """The date and time that the order was last changed. Always expressed in UTC."""
    open_price: Decimal | None = Field(default=None, alias="OpenPrice")
    """The open price of the order."""
    original_last_changed_date_time: StoneXDateTime | None = Field(
        default=None, alias="OriginalLastChangedDateTime"
    )
    """The date of the order. Always expressed in UTC."""
    original_quantity: Decimal | None = Field(default=None, alias="OriginalQuantity")
    """The orders original quantity, before any part / full closures."""
    position_method_id: int | None = Field(default=None, alias="PositionMethodId")
    """Indicates the position of the trade. 1 == LongOrShortOnly, 2 == LongAndShort."""
    quantity: Decimal | None = Field(default=None, alias="Quantity")
    """The current quantity of the order."""
    type: str | None = Field(default=None, alias="Type")
    """
    The type of the order (1 = Trade / 2 = Stop / 3 = Limit) . The table of lookup codes can
    be found at Lookup Values .
    """
    status: str | None = Field(default=None, alias="Status")
    """The order status ID. The table of lookup codes can be found at Lookup Values ."""
    reason_id: int | None = Field(default=None, alias="ReasonId")
    """
    The order status reason identifier. The table of lookup codes can be found at Lookup
    Values .
    """


OrderDTO.model_rebuild(raise_errors=False)
