# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from decimal import Decimal
from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .Timestamp import Timestamp


class OrderHistoryDTO(ResponseModel):
    market_id: int | None = Field(default=None, alias="MarketId")
    market_name: str | None = Field(default=None, alias="MarketName")
    created_date_time_utc: Timestamp | None = Field(default=None, alias="CreatedDateTimeUtc")
    direction_id: str | None = Field(default=None, alias="DirectionId")
    original_quantity: Decimal | None = Field(default=None, alias="OriginalQuantity")
    trigger_price: Decimal | None = Field(default=None, alias="TriggerPrice")
    expiry_type_id: int | None = Field(default=None, alias="ExpiryTypeId")
    expiry: Timestamp | None = Field(default=None, alias="Expiry")
    status_id: int | None = Field(default=None, alias="StatusId")
    order_type_id: int | None = Field(default=None, alias="OrderTypeId")
    currency_id: int | None = Field(default=None, alias="CurrencyId")
    order_id: int | None = Field(default=None, alias="OrderId")
    filled_quantity: Decimal | None = Field(default=None, alias="FilledQuantity")
    client_account_id: int | None = Field(default=None, alias="ClientAccountId")
    execution_policy_id: int | None = Field(default=None, alias="ExecutionPolicyId")
    fill_level: Decimal | None = Field(default=None, alias="FillLevel")


OrderHistoryDTO.model_rebuild(raise_errors=False)
