# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from decimal import Decimal

from pydantic import Field

from stonepy._core.models import ResponseModel


class PendingOrderDTO(ResponseModel):
    trigger_price: Decimal | None = Field(default=None, alias="TriggerPrice")
    market_id: int | None = Field(default=None, alias="MarketId")


PendingOrderDTO.model_rebuild(raise_errors=False)
