# GENERATED by stonepy._generator. Do not edit by hand.
"""
All service calls and DTOs related to Predicted Markets are for internal StoneX use only.
Contains information about the pending orders.
"""

from __future__ import annotations

from decimal import Decimal

from pydantic import Field

from stonepy._core.models import ResponseModel


class PendingOrderDTO(ResponseModel):
    """
    All service calls and DTOs related to Predicted Markets are for internal StoneX use only.
    Contains information about the pending orders.
    """

    trigger_price: Decimal | None = Field(default=None, alias="TriggerPrice")
    """The order trigger price."""
    market_id: int | None = Field(default=None, alias="MarketId")
    """The market's unique identifier."""


PendingOrderDTO.model_rebuild(raise_errors=False)
