# GENERATED by stonepy._generator. Do not edit by hand.
"""Information about preference"""

from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class PreferenceDTO(ResponseModel):
    """Information about preference"""

    key: str | None = Field(default=None, alias="Key")
    """Key identifier"""
    value: str | None = Field(default=None, alias="Value")
    """Value for specific key"""


PreferenceDTO.model_rebuild(raise_errors=False)
