# GENERATED by stonepy._generator. Do not edit by hand.
"""
Array data point for GetPriceTickResponseDTO . Contains the mid price (default setting) at the
point in time the pricing engine is updated - the price tick.
"""

from __future__ import annotations

from decimal import Decimal

from pydantic import Field

from stonepy._core.models import ResponseModel, StoneXDateTime


class PriceTickDTO(ResponseModel):
    """
    Array data point for GetPriceTickResponseDTO . Contains the mid price (default setting) at
    the point in time the pricing engine is updated - the price tick.
    """

    tick_date: StoneXDateTime | None = Field(default=None, alias="TickDate")
    """The date time at which a price tick occurred. Accurate to the millisecond."""
    price: Decimal | None = Field(default=None, alias="Price")
    """The price of the tick, which is the mid price by default."""


PriceTickDTO.model_rebuild(raise_errors=False)
