# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from decimal import Decimal

from pydantic import Field

from stonepy._core.models import ResponseModel, StoneXDateTime


class PriceTickDTO(ResponseModel):
    tick_date: StoneXDateTime | None = Field(default=None, alias="TickDate")
    price: Decimal | None = Field(default=None, alias="Price")


PriceTickDTO.model_rebuild(raise_errors=False)
