# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from decimal import Decimal

from pydantic import Field

from stonepy._core.models import ResponseModel, StoneXDateTime


class PriceBarDTO(ResponseModel):
    bar_date: StoneXDateTime | None = Field(default=None, alias="BarDate")
    open: Decimal | None = Field(default=None, alias="Open")
    high: Decimal | None = Field(default=None, alias="High")
    low: Decimal | None = Field(default=None, alias="Low")
    close: Decimal | None = Field(default=None, alias="Close")


PriceBarDTO.model_rebuild(raise_errors=False)
