# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from decimal import Decimal

from pydantic import Field

from stonepy._core.models import ResponseModel, StoneXDateTime


class QuoteDTO(ResponseModel):
    quote_id: int | None = Field(default=None, alias="QuoteId")
    order_id: int | None = Field(default=None, alias="OrderId")
    market_id: int | None = Field(default=None, alias="MarketId")
    bid_price: Decimal | None = Field(default=None, alias="BidPrice")
    bid_adjust: Decimal | None = Field(default=None, alias="BidAdjust")
    offer_price: Decimal | None = Field(default=None, alias="OfferPrice")
    offer_adjust: Decimal | None = Field(default=None, alias="OfferAdjust")
    quantity: Decimal | None = Field(default=None, alias="Quantity")
    currency_id: int | None = Field(default=None, alias="CurrencyId")
    status_id: int | None = Field(default=None, alias="StatusId")
    type_id: int | None = Field(default=None, alias="TypeId")
    request_date_time_utc: StoneXDateTime | None = Field(default=None, alias="RequestDateTimeUTC")
    approval_date_time_utc: StoneXDateTime | None = Field(default=None, alias="ApprovalDateTimeUTC")
    breath_time_secs: int | None = Field(default=None, alias="BreathTimeSecs")
    is_oversize: bool | None = Field(default=None, alias="IsOversize")
    reason_id: int | None = Field(default=None, alias="ReasonId")
    trading_account_id: int | None = Field(default=None, alias="TradingAccountId")


QuoteDTO.model_rebuild(raise_errors=False)
