# GENERATED by stonepy._generator. Do not edit by hand.
"""A quote for a specific order request."""

from __future__ import annotations

from decimal import Decimal
from typing import overload

from pydantic import Field

from stonepy._core.models import ResponseModel, StoneXDateTime

class QuoteDTO(ResponseModel):
    """A quote for a specific order request."""

    quote_id: int | None = Field(default=None, alias="QuoteId")
    """The unique ID of the Quote."""
    order_id: int | None = Field(default=None, alias="OrderId")
    """The ID of the Order that the Quote is related to."""
    market_id: int | None = Field(default=None, alias="MarketId")
    """The Market the Quote is related to."""
    bid_price: Decimal | None = Field(default=None, alias="BidPrice")
    """The Price of the original Order request for a Buy."""
    bid_adjust: Decimal | None = Field(default=None, alias="BidAdjust")
    """
    The amount the bid price will be adjusted to become an order when the customer is buying
    (BidPrice + BidAdjust = BuyPrice) .
    """
    offer_price: Decimal | None = Field(default=None, alias="OfferPrice")
    """The Price of the original Order request for a Sell."""
    offer_adjust: Decimal | None = Field(default=None, alias="OfferAdjust")
    """
    The amount the offer price will be adjusted to become an order when the customer is
    selling (OfferPrice + OfferAdjust = OfferPrice) .
    """
    quantity: Decimal | None = Field(default=None, alias="Quantity")
    """
    The Quantity is the number of units for the trade i.e CFD Quantity = Number of CFDs to Buy
    or Sell , FX Quantity = amount in base currency.
    """
    currency_id: int | None = Field(default=None, alias="CurrencyId")
    """
    The system internal ID for the ISO Currency. An API call will be available in the near
    future to look up the equivalent ISO Code.
    """
    status_id: int | None = Field(default=None, alias="StatusId")
    """
    The Status ID of the Quote. An API call will be available in the near future to look up
    the Status values. The table of lookup codes can be found at Lookup Values .
    """
    type_id: int | None = Field(default=None, alias="TypeId")
    """The quote type ID. The table of lookup codes can be found at Lookup Values ."""
    request_date_time_utc: StoneXDateTime | None = Field(default=None, alias="RequestDateTimeUTC")
    """The timestamp the quote was requested. Always expressed in UTC."""
    approval_date_time_utc: StoneXDateTime | None = Field(default=None, alias="ApprovalDateTimeUTC")
    """The timestamp the quote was approved. Always expressed in UTC."""
    breath_time_secs: int | None = Field(default=None, alias="BreathTimeSecs")
    """Amount of time in seconds the quote is valid for."""
    is_oversize: bool | None = Field(default=None, alias="IsOversize")
    """Is the quote oversize."""
    reason_id: int | None = Field(default=None, alias="ReasonId")
    """The reason for generating the quote."""
    trading_account_id: int | None = Field(default=None, alias="TradingAccountId")
    """The trading account identifier that generated the quote."""

    @overload
    def __init__(
        self,
        *,
        QuoteId: int | None = ...,
        OrderId: int | None = ...,
        MarketId: int | None = ...,
        BidPrice: Decimal | None = ...,
        BidAdjust: Decimal | None = ...,
        OfferPrice: Decimal | None = ...,
        OfferAdjust: Decimal | None = ...,
        Quantity: Decimal | None = ...,
        CurrencyId: int | None = ...,
        StatusId: int | None = ...,
        TypeId: int | None = ...,
        RequestDateTimeUTC: StoneXDateTime | None = ...,
        ApprovalDateTimeUTC: StoneXDateTime | None = ...,
        BreathTimeSecs: int | None = ...,
        IsOversize: bool | None = ...,
        ReasonId: int | None = ...,
        TradingAccountId: int | None = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        *,
        quote_id: int | None = ...,
        order_id: int | None = ...,
        market_id: int | None = ...,
        bid_price: Decimal | None = ...,
        bid_adjust: Decimal | None = ...,
        offer_price: Decimal | None = ...,
        offer_adjust: Decimal | None = ...,
        quantity: Decimal | None = ...,
        currency_id: int | None = ...,
        status_id: int | None = ...,
        type_id: int | None = ...,
        request_date_time_utc: StoneXDateTime | None = ...,
        approval_date_time_utc: StoneXDateTime | None = ...,
        breath_time_secs: int | None = ...,
        is_oversize: bool | None = ...,
        reason_id: int | None = ...,
        trading_account_id: int | None = ...,
    ) -> None: ...
