# GENERATED by stonepy._generator. Do not edit by hand.
"""
Request-side variant of ApiClientPreferencesOverridenSettingsSaveDTO: rejects unknown fields.
All overridden client preference settings to save.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, overload

from pydantic import Field

from stonepy._core.models import RequestVariantModel

if TYPE_CHECKING:
    from .RequestApiClientPreferencesOverridenSettingSaveDTO import (
        RequestApiClientPreferencesOverridenSettingSaveDTO,
    )

class RequestApiClientPreferencesOverridenSettingsSaveDTO(RequestVariantModel):
    """All overridden client preference settings to save."""

    price_tolerance: RequestApiClientPreferencesOverridenSettingSaveDTO | None = Field(
        default=None, alias="Price Tolerance"
    )
    """The overridden price tolerance value to save - cannot be null."""
    margin_factor_percentage: RequestApiClientPreferencesOverridenSettingSaveDTO | None = Field(
        default=None, alias="MarginFactorPercentage"
    )
    """The overridden margin factor value to save - cannot be null."""

    @overload
    def __init__(
        self,
        *,
        price_tolerance: RequestApiClientPreferencesOverridenSettingSaveDTO | None = ...,
        MarginFactorPercentage: RequestApiClientPreferencesOverridenSettingSaveDTO | None = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        *,
        price_tolerance: RequestApiClientPreferencesOverridenSettingSaveDTO | None = ...,
        margin_factor_percentage: RequestApiClientPreferencesOverridenSettingSaveDTO | None = ...,
    ) -> None: ...
