# GENERATED by stonepy._generator. Do not edit by hand.
"""Request-side variant of IdentifierDTO: rejects unknown fields. Information about identifiers."""

from __future__ import annotations

from pydantic import Field

from stonepy._core.models import RequestVariantModel


class RequestIdentifierDTO(RequestVariantModel):
    """Information about identifiers."""

    identifier_code: str | None = Field(default=None, alias="IdentifierCode")
    """Identifier code"""
    isin: str | None = Field(default=None, alias="Isin")
    """International Securities Identification Number"""
    sedol: str | None = Field(default=None, alias="Sedol")
    """Stock Exchange Daily Official List"""


RequestIdentifierDTO.model_rebuild(raise_errors=False)
