# GENERATED by stonepy._generator. Do not edit by hand.
"""
Request-side variant of CorporateActionsDTO: rejects unknown fields. Corporate actions
information.
"""

from __future__ import annotations

from pydantic import Field

from stonepy._core.models import RequestVariantModel


class RequestCorporateActionsDTO(RequestVariantModel):
    """Corporate actions information."""

    corporate_action_id: int | None = Field(default=None, alias="CorporateActionId")
    """Corporate action identifier"""


RequestCorporateActionsDTO.model_rebuild(raise_errors=False)
