# GENERATED by stonepy._generator. Do not edit by hand.
"""
Request-side variant of ApiIfDoneDTOv2: rejects unknown fields. Contains the If/Done stop and
limit orders. An If/Done order is comprised of two separate orders linked together and
requested as a single order. When the first order is executed, the second order becomes an
active order. For example, attaching a stop/limit to a trade or order.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import RequestVariantModel

if TYPE_CHECKING:
    from .RequestApiStopLimitOrderDTOv2 import RequestApiStopLimitOrderDTOv2


class RequestApiIfDoneDTOv2(RequestVariantModel):
    """
    Contains the If/Done stop and limit orders. An If/Done order is comprised of two separate
    orders linked together and requested as a single order. When the first order is executed,
    the second order becomes an active order. For example, attaching a stop/limit to a trade
    or order.
    """

    stop: RequestApiStopLimitOrderDTOv2 | None = Field(default=None, alias="Stop")
    """The price at which the stop order will be filled"""
    limit: RequestApiStopLimitOrderDTOv2 | None = Field(default=None, alias="Limit")
    """The price at which the limit order will be filled"""


RequestApiIfDoneDTOv2.model_rebuild(raise_errors=False)
