# GENERATED by stonepy._generator. Do not edit by hand.
"""
Request-side variant of ApiMarketInformationSaveDTO: rejects unknown fields. Contains market
information to be modified and saved.
"""

from __future__ import annotations

from decimal import Decimal
from typing import overload

from pydantic import Field

from stonepy._core.models import RequestVariantModel

class RequestApiMarketInformationSaveDTO(RequestVariantModel):
    """Contains market information to be modified and saved."""

    market_id: int | None = Field(default=None, alias="MarketId")
    """The ID of the market to be modified."""
    price_tolerance: Decimal | None = Field(default=None, alias="PriceTolerance")
    """Setting to indicate the user's price tolerance for the given market."""
    price_tolerance_is_dirty: bool | None = Field(default=None, alias="PriceToleranceIsDirty")
    """Flag to indicate if the price tolerance value has changed."""
    margin_factor: Decimal | None = Field(default=None, alias="MarginFactor")
    """The user's margin factor for the given market."""
    margin_factor_is_dirty: bool | None = Field(default=None, alias="MarginFactorIsDirty")
    """Flag to indicate if the margin factor value has changed."""

    @overload
    def __init__(
        self,
        *,
        MarketId: int | None = ...,
        PriceTolerance: Decimal | None = ...,
        PriceToleranceIsDirty: bool | None = ...,
        MarginFactor: Decimal | None = ...,
        MarginFactorIsDirty: bool | None = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        *,
        market_id: int | None = ...,
        price_tolerance: Decimal | None = ...,
        price_tolerance_is_dirty: bool | None = ...,
        margin_factor: Decimal | None = ...,
        margin_factor_is_dirty: bool | None = ...,
    ) -> None: ...
