# GENERATED by stonepy._generator. Do not edit by hand.
"""Request-side variant of Timestamp: rejects unknown fields. Timestamp DTO."""

from __future__ import annotations

from typing import overload

from pydantic import Field

from stonepy._core.models import RequestVariantModel

class RequestTimestamp(RequestVariantModel):
    """Timestamp DTO."""

    seconds: int | None = Field(default=None, alias="Seconds")
    """Number of seconds"""
    nanos: int | None = Field(default=None, alias="Nanos")
    """Number of nanoseconds"""

    @overload
    def __init__(
        self,
        *,
        Seconds: int | None = ...,
        Nanos: int | None = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        *,
        seconds: int | None = ...,
        nanos: int | None = ...,
    ) -> None: ...
