# GENERATED by stonepy._generator. Do not edit by hand.
"""
Request-side variant of ApiClientPreferencesOverriddenSettingsSaveDTO: rejects unknown fields.
All overridden client preference settings to save.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, overload

from pydantic import Field

from stonepy._core.models import RequestVariantModel

if TYPE_CHECKING:
    from .RequestApiClientPreferencesOverriddenSettingSaveDTO import (
        RequestApiClientPreferencesOverriddenSettingSaveDTO,
    )

class RequestApiClientPreferencesOverriddenSettingsSaveDTO(RequestVariantModel):
    """All overridden client preference settings to save."""

    price_tolerance: RequestApiClientPreferencesOverriddenSettingSaveDTO | None = Field(
        default=None, alias="Price Tolerance"
    )
    """The overridden price tolerance value to save - cannot be null"""
    margin_factor_percentage: RequestApiClientPreferencesOverriddenSettingSaveDTO | None = Field(
        default=None, alias="MarginFactorPercentage"
    )
    """The overridden margin factor value to save - cannot be null"""

    @overload
    def __init__(
        self,
        *,
        price_tolerance: RequestApiClientPreferencesOverriddenSettingSaveDTO | None = ...,
        MarginFactorPercentage: RequestApiClientPreferencesOverriddenSettingSaveDTO | None = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        *,
        price_tolerance: RequestApiClientPreferencesOverriddenSettingSaveDTO | None = ...,
        margin_factor_percentage: RequestApiClientPreferencesOverriddenSettingSaveDTO | None = ...,
    ) -> None: ...
