# GENERATED by stonepy._generator. Do not edit by hand.
"""
Request-side variant of ApiStepMarginBandDTO: rejects unknown fields. Represents a single step
margin band as expressed by the trading API.
"""

from __future__ import annotations

from decimal import Decimal

from pydantic import Field

from stonepy._core.models import RequestVariantModel


class RequestApiStepMarginBandDTO(RequestVariantModel):
    """Represents a single step margin band as expressed by the trading API."""

    lower_bound: Decimal | None = Field(default=None, alias="LowerBound")
    """Minimum threshold for this band, expressed in terms of the client's trade quantity"""
    margin_factor: Decimal | None = Field(default=None, alias="MarginFactor")
    """
    The margin factor that is used for this band. It can be expressed as a percentage or in
    points based on the market's margin factor type
    """


RequestApiStepMarginBandDTO.model_rebuild(raise_errors=False)
