# GENERATED by stonepy._generator. Do not edit by hand.
"""
Request-side variant of ApiMarketEodDTO: rejects unknown fields. Market end of day (EOD)
information.
"""

from __future__ import annotations

from pydantic import Field

from stonepy._core.models import RequestVariantModel


class RequestApiMarketEodDTO(RequestVariantModel):
    """Market end of day (EOD) information."""

    market_eod_unit: str | None = Field(default=None, alias="MarketEodUnit")
    """Unit"""
    market_eod_amount: int | None = Field(default=None, alias="MarketEodAmount")
    """End of day amount"""


RequestApiMarketEodDTO.model_rebuild(raise_errors=False)
