# GENERATED by stonepy._generator. Do not edit by hand.
"""Request-side variant of MarketPricesDTO: rejects unknown fields. Market prices information."""

from __future__ import annotations

from decimal import Decimal
from typing import overload

from pydantic import Field

from stonepy._core.models import RequestVariantModel

from .enums import MarketState

class RequestMarketPricesDTO(RequestVariantModel):
    """Market prices information."""

    bid_price: Decimal | None = Field(default=None, alias="BidPrice")
    """Bid price"""
    offer_price: Decimal | None = Field(default=None, alias="OfferPrice")
    """Offer price"""
    market_state: MarketState | None = Field(default=None, alias="MarketState")
    """List of market states"""

    @overload
    def __init__(
        self,
        *,
        BidPrice: Decimal | None = ...,
        OfferPrice: Decimal | None = ...,
        MarketState: MarketState | None = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        *,
        bid_price: Decimal | None = ...,
        offer_price: Decimal | None = ...,
        market_state: MarketState | None = ...,
    ) -> None: ...
