# GENERATED by stonepy._generator. Do not edit by hand.
"""Save client preferences."""

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import RequestModel

if TYPE_CHECKING:
    from .ClientPreferenceKeyDTO import ClientPreferenceKeyDTO


class SaveClientPreferenceRequestDTO(RequestModel):
    """Save client preferences."""

    client_preference: list[ClientPreferenceKeyDTO] | None = Field(
        default=None, alias="ClientPreference"
    )
    """The list of client preferences key value pairs to be saved."""


SaveClientPreferenceRequestDTO.model_rebuild(raise_errors=False)
