# GENERATED by stonepy._generator. Do not edit by hand.
"""Request to save a price alert on the specified market."""

from __future__ import annotations

from decimal import Decimal

from pydantic import Field

from stonepy._core.models import RequestModel, StoneXDateTime

from .enums import AlertCriterion, AlertDirection, AlertExpiry, AlertNotification


class SaveAlertRequestDTOv2(RequestModel):
    """Request to save a price alert on the specified market."""

    client_account_id: int = Field(alias="ClientAccountId")
    """Client account identifier"""
    alert_id: int = Field(alias="AlertId")
    """Price alert identifier"""
    market_id: int = Field(alias="MarketId")
    """Identifier of the market upon which the price alert is placed"""
    criterion: AlertCriterion = Field(alias="Criterion")
    """The condition to trigger the price alert"""
    direction: AlertDirection = Field(alias="Direction")
    """The market price type to use for the price alert - Buy price or Sell price"""
    fill_rate: Decimal = Field(alias="FillRate")
    """The market price at which the price alert will be triggered"""
    email_address: str = Field(alias="EmailAddress")
    """The user's email address"""
    expiry: AlertExpiry = Field(alias="Expiry")
    """The expiry type of the alert such as Good Till Cancelled (GTC) or Good Till Date (GTD)"""
    expiry_date: StoneXDateTime = Field(alias="ExpiryDate")
    """The price alert expiry date /time. Is Null in the case of GTC expiry"""
    comment: str = Field(alias="Comment")
    """User comment for this price alert"""
    notification_method: AlertNotification = Field(alias="NotificationMethod")
    """The communication method to notify the client when a price alert is triggered"""


SaveAlertRequestDTOv2.model_rebuild(raise_errors=False)
