# GENERATED by stonepy._generator. Do not edit by hand.
"""Response to save a price alert on the specified market."""

from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class SaveAlertResponseDTOv2(ResponseModel):
    """Response to save a price alert on the specified market."""

    alert_id: int | None = Field(default=None, alias="AlertId")
    """Alert identifier"""


SaveAlertResponseDTOv2.model_rebuild(raise_errors=False)
