# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from stonepy._core.models import ResponseModel


class SaveAllocationProfileResponseDTO(ResponseModel):
    pass


SaveAllocationProfileResponseDTO.model_rebuild(raise_errors=False)
