# GENERATED by stonepy._generator. Do not edit by hand.
"""Save market information request for a list of markets."""

from __future__ import annotations

from typing import TYPE_CHECKING, overload

from pydantic import Field

from stonepy._core.models import RequestModel

if TYPE_CHECKING:
    from .RequestApiMarketInformationSaveDTO import RequestApiMarketInformationSaveDTO

class SaveMarketInformationRequestDTO(RequestModel):
    """Save market information request for a list of markets."""

    market_information: list[RequestApiMarketInformationSaveDTO] | None = Field(
        default=None, alias="MarketInformation"
    )
    """The list of market information objects to be saved."""
    trading_account_id: int = Field(alias="TradingAccountId")
    """The trading account on which the market information objects should be saved."""

    @overload
    def __init__(
        self,
        *,
        MarketInformation: list[RequestApiMarketInformationSaveDTO] | None = ...,
        TradingAccountId: int,
    ) -> None: ...
    @overload
    def __init__(
        self,
        *,
        market_information: list[RequestApiMarketInformationSaveDTO] | None = ...,
        trading_account_id: int,
    ) -> None: ...
