# GENERATED by stonepy._generator. Do not edit by hand.
"""Save client preferences."""

from __future__ import annotations

from typing import TYPE_CHECKING, overload

from pydantic import Field

from stonepy._core.models import RequestModel

if TYPE_CHECKING:
    from .RequestClientPreferenceKeyDTO import RequestClientPreferenceKeyDTO

class SaveClientPreferenceRequestDTO(RequestModel):
    """Save client preferences."""

    client_preference: RequestClientPreferenceKeyDTO | None = Field(
        default=None, alias="ClientPreference"
    )
    """The list of client preferences key value pairs to be saved."""

    @overload
    def __init__(
        self,
        *,
        ClientPreference: RequestClientPreferenceKeyDTO | None = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        *,
        client_preference: RequestClientPreferenceKeyDTO | None = ...,
    ) -> None: ...
