# GENERATED by stonepy._generator. Do not edit by hand.
"""Request to create or update a Trading Advisor allocation profile."""

from __future__ import annotations

from stonepy._core.models import ResponseModel


class SaveAllocationProfileRequestDTO(ResponseModel):
    """Request to create or update a Trading Advisor allocation profile."""


SaveAllocationProfileRequestDTO.model_rebuild(raise_errors=False)
