# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class SaveAlertResponseDTOv2(ResponseModel):
    alert_id: int | None = Field(default=None, alias="AlertId")


SaveAlertResponseDTOv2.model_rebuild(raise_errors=False)
