# GENERATED by stonepy._generator. Do not edit by hand.
"""
All service calls and DTOs related to Predicted Markets are for internal StoneX use only.
Contains information on the performance of a trade signal.
"""

from __future__ import annotations

from decimal import Decimal

from pydantic import Field

from stonepy._core.models import ResponseModel, StoneXDateTime


class SignalPerformanceDTO(ResponseModel):
    """
    All service calls and DTOs related to Predicted Markets are for internal StoneX use only.
    Contains information on the performance of a trade signal.
    """

    signal_id: int | None = Field(default=None, alias="SignalId")
    """The unique identifier for the trade signal."""
    market_name: str | None = Field(default=None, alias="MarketName")
    """The name of the market where the trading signal applies."""
    percentage: Decimal | None = Field(default=None, alias="Percentage")
    """The signal performance as a percentage."""
    expiration_date_time: StoneXDateTime | None = Field(default=None, alias="ExpirationDateTime")
    """Expiry date and time for the signal."""
    trade_type: int | None = Field(default=None, alias="TradeType")
    """Indicates the trade type for the signal."""
    pn_l: Decimal | None = Field(default=None, alias="PnL")
    """The amount of profit or loss."""
    hot: bool | None = Field(default=None, alias="Hot")
    """Flag indicating whether the signal has hot status."""


SignalPerformanceDTO.model_rebuild(raise_errors=False)
