# GENERATED by stonepy._generator. Do not edit by hand.
"""
All service calls and DTOs related to Predicted Markets are for internal StoneX use only.
Response to a GetSignalPerformance call containing the list of top/bottom performing signals
and the number of wins and losses.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from stonepy._core.models import ResponseModel

if TYPE_CHECKING:
    from .SignalPerformanceDTO import SignalPerformanceDTO


class SignalPerformanceResponseDTO(ResponseModel):
    """
    All service calls and DTOs related to Predicted Markets are for internal StoneX use only.
    Response to a GetSignalPerformance call containing the list of top/bottom performing
    signals and the number of wins and losses.
    """

    wins: int | None = Field(default=None, alias="Wins")
    """Count of signals over the time period where PNL > 0."""
    losses: int | None = Field(default=None, alias="Losses")
    """Count of signals over the time period where PNL <= 0."""
    top_performers: list[SignalPerformanceDTO] | None = Field(default=None, alias="TopPerformers")
    """The list of top performing signals."""
    bottom_performers: list[SignalPerformanceDTO] | None = Field(
        default=None, alias="BottomPerformers"
    )
    """The list of bottom performing signals."""


SignalPerformanceResponseDTO.model_rebuild(raise_errors=False)
