# GENERATED by stonepy._generator. Do not edit by hand.
"""
All service calls and DTOs related to Predicted Markets are for internal StoneX use only.
Basic information about a Predicted Markets trading signal.
"""

from __future__ import annotations

from decimal import Decimal
from typing import overload

from pydantic import Field

from stonepy._core.models import ResponseModel, StoneXDateTime

class SignalDTO(ResponseModel):
    """
    All service calls and DTOs related to Predicted Markets are for internal StoneX use only.
    Basic information about a Predicted Markets trading signal.
    """

    signal_id: int | None = Field(default=None, alias="SignalId")
    """The unique identifier for the trade signal."""
    percentage: Decimal | None = Field(default=None, alias="Percentage")
    """The percentage."""
    market_id: int | None = Field(default=None, alias="MarketId")
    """The market's unique identifier."""
    rank: int | None = Field(default=None, alias="Rank")
    """Signal rank."""
    trigger_price: Decimal | None = Field(default=None, alias="TriggerPrice")
    """The signal trigger price."""
    stop_price: Decimal | None = Field(default=None, alias="StopPrice")
    """The signal stop price."""
    expiration_date_time: StoneXDateTime | None = Field(default=None, alias="ExpirationDateTime")
    """Expiry date and time for the trade signal."""
    trade_type: int | None = Field(default=None, alias="TradeType")
    """Indicates the trade type for the signal."""
    possible_action: int | None = Field(default=None, alias="PossibleAction")
    """
    If PossibleAction = 4 or 6, then return 0 = nothing. When PossibleAction = 2, then return
    1 = CanPlaceLimitOrders. When PossibleAction = 3, then return 2 = CanPlaceMarketOrders.
    """
    study_id: int | None = Field(default=None, alias="StudyId")
    """The study unique identifier."""
    start_date_time: StoneXDateTime | None = Field(default=None, alias="StartDateTime")
    """Start date and time for the trade signal."""
    hv_c: Decimal | None = Field(default=None, alias="HvC")
    """The HvC value."""
    hv_c_pct: Decimal | None = Field(default=None, alias="HvCPct")
    """Percentage value for the HvC."""
    lv_c: Decimal | None = Field(default=None, alias="LvC")
    """The LvC value."""
    lv_c_pct: Decimal | None = Field(default=None, alias="LvCPct")
    """Percentage value for the LvC."""
    cv_c: Decimal | None = Field(default=None, alias="CvC")
    """The CvC value."""
    cv_c_pct: Decimal | None = Field(default=None, alias="CvCPct")
    """Percentage value for the CvC."""
    cv_c_pct_previous: Decimal | None = Field(default=None, alias="CvCPctPrevious")
    """The previous CvC percentage value."""
    cv_h: Decimal | None = Field(default=None, alias="CvH")
    """The CvH value."""
    cv_h_pct: Decimal | None = Field(default=None, alias="CvHPct")
    """Percentage value for the CvH."""
    cv_l: Decimal | None = Field(default=None, alias="CvL")
    """The CvL value."""
    cv_l_pct: Decimal | None = Field(default=None, alias="CvLPct")
    """Percentage value for the CvL."""
    close: Decimal | None = Field(default=None, alias="Close")
    """The close value."""
    over_how_many_bars: int | None = Field(default=None, alias="OverHowManyBars")
    """The number of bars value."""
    threshold: Decimal | None = Field(default=None, alias="Threshold")
    """Signal threshold value."""
    threshold_pct: Decimal | None = Field(default=None, alias="ThresholdPct")
    """Percentage signal threshold value."""
    lower_bound: Decimal | None = Field(default=None, alias="LowerBound")
    """The lower bound value."""
    upper_bound: Decimal | None = Field(default=None, alias="UpperBound")
    """The upper bound value."""
    move: Decimal | None = Field(default=None, alias="Move")
    """The move value."""
    move_pct: Decimal | None = Field(default=None, alias="MovePct")
    """Percentage value for the move."""
    new_low_of_more_than: Decimal | None = Field(default=None, alias="NewLowOfMoreThan")
    """New low value."""
    new_high_of_more_than: Decimal | None = Field(default=None, alias="NewHighOfMoreThan")
    """New high value."""
    hot: bool | None = Field(default=None, alias="Hot")
    """Flag indicating whether the signal has hot status."""

    @overload
    def __init__(
        self,
        *,
        SignalId: int | None = ...,
        Percentage: Decimal | None = ...,
        MarketId: int | None = ...,
        Rank: int | None = ...,
        TriggerPrice: Decimal | None = ...,
        StopPrice: Decimal | None = ...,
        ExpirationDateTime: StoneXDateTime | None = ...,
        TradeType: int | None = ...,
        PossibleAction: int | None = ...,
        StudyId: int | None = ...,
        StartDateTime: StoneXDateTime | None = ...,
        HvC: Decimal | None = ...,
        HvCPct: Decimal | None = ...,
        LvC: Decimal | None = ...,
        LvCPct: Decimal | None = ...,
        CvC: Decimal | None = ...,
        CvCPct: Decimal | None = ...,
        CvCPctPrevious: Decimal | None = ...,
        CvH: Decimal | None = ...,
        CvHPct: Decimal | None = ...,
        CvL: Decimal | None = ...,
        CvLPct: Decimal | None = ...,
        Close: Decimal | None = ...,
        OverHowManyBars: int | None = ...,
        Threshold: Decimal | None = ...,
        ThresholdPct: Decimal | None = ...,
        LowerBound: Decimal | None = ...,
        UpperBound: Decimal | None = ...,
        Move: Decimal | None = ...,
        MovePct: Decimal | None = ...,
        NewLowOfMoreThan: Decimal | None = ...,
        NewHighOfMoreThan: Decimal | None = ...,
        Hot: bool | None = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        *,
        signal_id: int | None = ...,
        percentage: Decimal | None = ...,
        market_id: int | None = ...,
        rank: int | None = ...,
        trigger_price: Decimal | None = ...,
        stop_price: Decimal | None = ...,
        expiration_date_time: StoneXDateTime | None = ...,
        trade_type: int | None = ...,
        possible_action: int | None = ...,
        study_id: int | None = ...,
        start_date_time: StoneXDateTime | None = ...,
        hv_c: Decimal | None = ...,
        hv_c_pct: Decimal | None = ...,
        lv_c: Decimal | None = ...,
        lv_c_pct: Decimal | None = ...,
        cv_c: Decimal | None = ...,
        cv_c_pct: Decimal | None = ...,
        cv_c_pct_previous: Decimal | None = ...,
        cv_h: Decimal | None = ...,
        cv_h_pct: Decimal | None = ...,
        cv_l: Decimal | None = ...,
        cv_l_pct: Decimal | None = ...,
        close: Decimal | None = ...,
        over_how_many_bars: int | None = ...,
        threshold: Decimal | None = ...,
        threshold_pct: Decimal | None = ...,
        lower_bound: Decimal | None = ...,
        upper_bound: Decimal | None = ...,
        move: Decimal | None = ...,
        move_pct: Decimal | None = ...,
        new_low_of_more_than: Decimal | None = ...,
        new_high_of_more_than: Decimal | None = ...,
        hot: bool | None = ...,
    ) -> None: ...
