# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class StoryResponseDTO(ResponseModel):
    story: str | None = Field(default=None, alias="Story")
    story_in_html: str | None = Field(default=None, alias="StoryInHtml")


StoryResponseDTO.model_rebuild(raise_errors=False)
