# GENERATED by stonepy._generator. Do not edit by hand.
"""Response containing the system status."""

from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class SystemStatusDTO(ResponseModel):
    """Response containing the system status."""

    status_message: str | None = Field(default=None, alias="StatusMessage")
    """The status message."""


SystemStatusDTO.model_rebuild(raise_errors=False)
