# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class SystemStatusRequestDTO(ResponseModel):
    test_depth: str | None = Field(default=None, alias="TestDepth")


SystemStatusRequestDTO.model_rebuild(raise_errors=False)
