# GENERATED by stonepy._generator. Do not edit by hand.
"""System status request."""

from __future__ import annotations

from typing import overload

from pydantic import Field

from stonepy._core.models import ResponseModel

class SystemStatusRequestDTO(ResponseModel):
    """System status request."""

    test_depth: str | None = Field(default=None, alias="TestDepth")
    """Depth to test."""

    @overload
    def __init__(
        self,
        *,
        TestDepth: str | None = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        *,
        test_depth: str | None = ...,
    ) -> None: ...
