# GENERATED by stonepy._generator. Do not edit by hand.
"""Timestamp DTO."""

from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class Timestamp(ResponseModel):
    """Timestamp DTO."""

    seconds: int | None = Field(default=None, alias="Seconds")
    """Number of seconds"""
    nanos: int | None = Field(default=None, alias="Nanos")
    """Number of nanoseconds"""


Timestamp.model_rebuild(raise_errors=False)
