# GENERATED by stonepy._generator. Do not edit by hand.
"""
This is only applicable to the GTS back-end. The current margin and other account balance data
for a specific client account used in the stream.
"""

from __future__ import annotations

from decimal import Decimal

from pydantic import Field

from stonepy._core.models import ResponseModel


class TradingAccountMarginDTO(ResponseModel):
    """
    This is only applicable to the GTS back-end. The current margin and other account balance
    data for a specific client account used in the stream.
    """

    cash: Decimal | None = Field(default=None, alias="Cash")
    """Cash balance expressed in the clients base currency."""
    margin: Decimal | None = Field(default=None, alias="Margin")
    """The client account's total margin requirement expressed in base currency."""
    margin_indicator: Decimal | None = Field(default=None, alias="MarginIndicator")
    """Margin indicator expressed as a percentage."""
    net_equity: Decimal | None = Field(default=None, alias="NetEquity")
    """Net equity expressed in the clients base currency."""
    open_trade_equity: Decimal | None = Field(default=None, alias="OpenTradeEquity")
    """Open trade equity (open / unrealised PNL) expressed in the client's base currency."""
    tradeable_funds: Decimal | None = Field(default=None, alias="TradeableFunds")
    """Tradable funds expressed in the client's base currency."""
    pending_funds: Decimal | None = Field(default=None, alias="PendingFunds")
    """N/A"""
    trading_resource: Decimal | None = Field(default=None, alias="TradingResource")
    """Trading resource expressed in the client's base currency."""
    total_margin_requirement: Decimal | None = Field(default=None, alias="TotalMarginRequirement")
    """Total margin requirement expressed in the client's base currency."""
    trading_account_id: int | None = Field(default=None, alias="TradingAccountId")
    """The identifier for the trading account."""
    currency_id: int | None = Field(default=None, alias="CurrencyId")
    """The clients base currency ID."""
    currency_iso: str | None = Field(default=None, alias="CurrencyISO")
    """The clients base currency ISO code."""


TradingAccountMarginDTO.model_rebuild(raise_errors=False)
