# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from decimal import Decimal

from pydantic import Field

from stonepy._core.models import ResponseModel


class UpdateFixedMarginTradeOrderRequestDTO(ResponseModel):
    trading_account_id: int | None = Field(default=None, alias="TradingAccountId")
    market_id: int | None = Field(default=None, alias="MarketId")
    order_id: int | None = Field(default=None, alias="OrderId")
    take_profit_price: Decimal | None = Field(default=None, alias="TakeProfitPrice")
    stop_loss_price: Decimal | None = Field(default=None, alias="StopLossPrice")
    trailing_stop_distance: Decimal | None = Field(default=None, alias="TrailingStopDistance")


UpdateFixedMarginTradeOrderRequestDTO.model_rebuild(raise_errors=False)
