# GENERATED by stonepy._generator. Do not edit by hand.
"""Request to update the display order of items in a watchlist."""

from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class UpdateWatchlistDisplayOrderRequestDTO(ResponseModel):
    """Request to update the display order of items in a watchlist."""

    new_display_order_id_sequence: list[int] | None = Field(
        default=None, alias="NewDisplayOrderIdSequence"
    )
    """Represents the new client watchlist displayOrderId list sequence."""


UpdateWatchlistDisplayOrderRequestDTO.model_rebuild(raise_errors=False)
