# GENERATED by stonepy._generator. Do not edit by hand.
"""A boolean result to signify status of completed operation."""

from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class UpdateDeleteClientPreferenceResponseDTO(ResponseModel):
    """A boolean result to signify status of completed operation."""

    successful: bool | None = Field(default=None, alias="Successful")
    """Flag indicating if the save operation completed successfully."""


UpdateDeleteClientPreferenceResponseDTO.model_rebuild(raise_errors=False)
