# GENERATED by stonepy._generator. Do not edit by hand.
from __future__ import annotations

from pydantic import Field

from stonepy._core.models import ResponseModel


class UpdateWatchlistDisplayOrderRequestDTO(ResponseModel):
    new_display_order_id_sequence: list[int] | None = Field(
        default=None, alias="NewDisplayOrderIdSequence"
    )


UpdateWatchlistDisplayOrderRequestDTO.model_rebuild(raise_errors=False)
