# GENERATED by stonepy._generator. Do not edit by hand.
"""Resource method: ListNewsHeadlines."""

from __future__ import annotations

from stonepy._core.resource import BaseResource
from stonepy._endpoints import news as _ep
from stonepy.models import ListNewsHeadlinesRequestDTO, ListNewsHeadlinesResponseDTO


class _ListNewsHeadlinesMixin(BaseResource):
    def list_news_headlines(
        self, request: ListNewsHeadlinesRequestDTO
    ) -> ListNewsHeadlinesResponseDTO:
        """
        Get a list of current news headlines matching the request parameters. The list of
        news headlines can be filtered by various criteria such as market, or geographic
        region.
        """
        return _ep.list_news_headlines(self._ctx, request)
