# GENERATED by stonepy._generator. Do not edit by hand.
"""Resource method: GetMarketInformationExtended v2."""

from __future__ import annotations

from stonepy._core.resource import BaseResource
from stonepy._endpoints import market as _ep
from stonepy.models import ApiGetMarketInformationExtendedResponseDTOv2


class _GetMarketInformationExtendedMixin(BaseResource):
    def get_market_information_extended(
        self, market_id: int, client_account_id: int
    ) -> ApiGetMarketInformationExtendedResponseDTOv2:
        """
        Get extended Market Information for the single specified market supplied in the
        parameter.
        """
        return _ep.get_market_information_extended(self._ctx, market_id, client_account_id)
