# GENERATED by stonepy._generator. Do not edit by hand.
"""Resource method: GetLatestPriceBars."""

from __future__ import annotations

from stonepy._core.resource import BaseResource
from stonepy._endpoints import market as _ep
from stonepy.models import GetPriceBarResponseDTO


class _GetLatestPriceBarsMixin(BaseResource):
    def get_latest_price_bars(
        self, market_id: str, interval: str, span: int, price_bars: int, price_type: str
    ) -> GetPriceBarResponseDTO:
        """
        Get historic price bars for the specified market in OHLC (open, high, low, close)
        format, suitable for plotting in candlestick charts. Returns price bars in
        ascending order up to the current time. When there are no prices for a particular
        time period, no price bar is returned. Thus, it can appear that the array of price
        bars has "gaps", i.e. the gap between the date & time of each price bar might not
        be equal to interval x span. Sample Urls:
        /market/1234/barhistory?interval=MINUTE&span=15&PriceBars=180
        /market/735/barhistory?interval=HOUR&span=1&PriceBars=240
        /market/1577/barhistory?interval=DAY&span=1&PriceBars=10
        """
        return _ep.get_latest_price_bars(
            self._ctx, market_id, interval, span, price_bars, price_type
        )
