# GENERATED by stonepy._generator. Do not edit by hand.
"""Resource method: ListMarketInformationSearch."""

from __future__ import annotations

from stonepy._core.resource import BaseResource
from stonepy._endpoints import market as _ep
from stonepy.models import ListMarketInformationSearchResponseDTO


class _ListMarketInformationSearchMixin(BaseResource):
    def list_market_information_search(
        self,
        search_by_market_code: bool,
        search_by_market_name: bool,
        spread_product_type: bool,
        cfd_product_type: bool,
        binary_product_type: bool,
        include_options: bool,
        query: str,
        trading_account_id: int,
        max_results: int,
        client_account_id: int,
        *,
        use_mobile_short_name: bool | None = False,
    ) -> ListMarketInformationSearchResponseDTO:
        """
        Returns market information for the markets that meet the search criteria. The
        search can be performed by market code and/or market name, and can include CFDs
        and Spread Bet markets.
        """
        return _ep.list_market_information_search(
            self._ctx,
            search_by_market_code,
            search_by_market_name,
            spread_product_type,
            cfd_product_type,
            binary_product_type,
            include_options,
            query,
            trading_account_id,
            max_results,
            client_account_id,
            use_mobile_short_name=use_mobile_short_name,
        )
