# GENERATED by stonepy._generator. Do not edit by hand.
"""Resource method: SearchWithTags."""

from __future__ import annotations

from stonepy._core.resource import BaseResource
from stonepy._endpoints import market as _ep
from stonepy.models import MarketInformationSearchWithTagsResponseDTO


class _SearchWithTagsMixin(BaseResource):
    def search_with_tags(
        self,
        query: str,
        search_by_market_code: bool,
        search_by_market_name: bool,
        spread_product_type: bool,
        cfd_product_type: bool,
        binary_product_type: bool,
        include_options: bool,
        max_results: int,
        client_account_id: int,
        *,
        tag_id: int | None = None,
        trading_account_id: int | None = None,
        use_mobile_short_name: bool | None = False,
    ) -> MarketInformationSearchWithTagsResponseDTO:
        """
        Returns a list of markets that meet the search criteria. This search extends
        ListMarketSearch by optionally searching within a specified market tag and only
        returning matching markets from the specified tag. Leave the query string empty to
        return all markets available to the user. The results contain the summarised
        MarketId and MarketName properties. The market tag is optional and if not used,
        then this service call will behave the same as ListMarketSearch . The list of
        market tag IDs are provided in the table at Market Tag IDs .
        """
        return _ep.search_with_tags(
            self._ctx,
            query,
            search_by_market_code,
            search_by_market_name,
            spread_product_type,
            cfd_product_type,
            binary_product_type,
            include_options,
            max_results,
            client_account_id,
            tag_id=tag_id,
            trading_account_id=trading_account_id,
            use_mobile_short_name=use_mobile_short_name,
        )
